"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Device(_message.Message):
    """设备信息
    gRPC头部:x-bili-device-bin
    """

    DESCRIPTOR: _descriptor.Descriptor

    APP_ID_FIELD_NUMBER: _builtins.int
    BUILD_FIELD_NUMBER: _builtins.int
    BUVID_FIELD_NUMBER: _builtins.int
    MOBI_APP_FIELD_NUMBER: _builtins.int
    PLATFORM_FIELD_NUMBER: _builtins.int
    DEVICE_FIELD_NUMBER: _builtins.int
    CHANNEL_FIELD_NUMBER: _builtins.int
    BRAND_FIELD_NUMBER: _builtins.int
    MODEL_FIELD_NUMBER: _builtins.int
    OSVER_FIELD_NUMBER: _builtins.int
    FP_LOCAL_FIELD_NUMBER: _builtins.int
    FP_REMOTE_FIELD_NUMBER: _builtins.int
    VERSION_NAME_FIELD_NUMBER: _builtins.int
    FP_FIELD_NUMBER: _builtins.int
    FTS_FIELD_NUMBER: _builtins.int
    app_id: _builtins.int
    """产品id
    粉 白 蓝 直播姬 HD 海外 OTT 漫画 TV野版 小视频 网易漫画 网易漫画 网易漫画HD 国际版 东南亚版
    1  2  3    4    5   6    7   8     9     10      11       12       13       14       30
    """
    build: _builtins.int
    """构建id"""
    buvid: _builtins.str
    """设备buvid"""
    mobi_app: _builtins.str
    """包类型"""
    platform: _builtins.str
    """平台类型
    ios android
    """
    device: _builtins.str
    """设备类型"""
    channel: _builtins.str
    """渠道"""
    brand: _builtins.str
    """手机品牌"""
    model: _builtins.str
    """手机型号"""
    osver: _builtins.str
    """系统版本"""
    fp_local: _builtins.str
    """本地设备指纹"""
    fp_remote: _builtins.str
    """远程设备指纹"""
    version_name: _builtins.str
    """APP版本号"""
    fp: _builtins.str
    """设备指纹, 不区分本地或远程设备指纹，作为推送目标的索引"""
    fts: _builtins.int
    """首次启动时的毫秒时间戳"""
    def __init__(
        self,
        *,
        app_id: _builtins.int = ...,
        build: _builtins.int = ...,
        buvid: _builtins.str = ...,
        mobi_app: _builtins.str = ...,
        platform: _builtins.str = ...,
        device: _builtins.str = ...,
        channel: _builtins.str = ...,
        brand: _builtins.str = ...,
        model: _builtins.str = ...,
        osver: _builtins.str = ...,
        fp_local: _builtins.str = ...,
        fp_remote: _builtins.str = ...,
        version_name: _builtins.str = ...,
        fp: _builtins.str = ...,
        fts: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_id", b"app_id", "brand", b"brand", "build", b"build", "buvid", b"buvid", "channel", b"channel", "device", b"device", "fp", b"fp", "fp_local", b"fp_local", "fp_remote", b"fp_remote", "fts", b"fts", "mobi_app", b"mobi_app", "model", b"model", "osver", b"osver", "platform", b"platform", "version_name", b"version_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Device: _TypeAlias = Device  # noqa: Y015
