"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from bilibili.dynamic.common import dynamic_pb2 as _dynamic_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ConfigABEntry:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ConfigABEntryEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ConfigABEntry.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CONFIG_AB_ENTRY_NONE: _ConfigABEntry.ValueType  # 0
    CONFIG_AB_ENTRY_PUB_PAGE_TITLE: _ConfigABEntry.ValueType  # 1
    CONFIG_AB_ENTRY_SELECT_PIC_PANEL: _ConfigABEntry.ValueType  # 2

class ConfigABEntry(_ConfigABEntry, metaclass=_ConfigABEntryEnumTypeWrapper):
    """"""

CONFIG_AB_ENTRY_NONE: ConfigABEntry.ValueType  # 0
CONFIG_AB_ENTRY_PUB_PAGE_TITLE: ConfigABEntry.ValueType  # 1
CONFIG_AB_ENTRY_SELECT_PIC_PANEL: ConfigABEntry.ValueType  # 2
Global___ConfigABEntry: _TypeAlias = ConfigABEntry  # noqa: Y015

class _DynamicButtonClickBizType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DynamicButtonClickBizTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DynamicButtonClickBizType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DYNAMIC_BUTTON_CLICK_BIZ_TYPE_NONE: _DynamicButtonClickBizType.ValueType  # 0
    """"""
    DYNAMIC_BUTTON_CLICK_BIZ_TYPE_LIVE: _DynamicButtonClickBizType.ValueType  # 1
    """"""
    DYNAMIC_BUTTON_CLICK_BIZ_TYPE_DYN_UP: _DynamicButtonClickBizType.ValueType  # 2
    """"""

class DynamicButtonClickBizType(_DynamicButtonClickBizType, metaclass=_DynamicButtonClickBizTypeEnumTypeWrapper):
    """"""

DYNAMIC_BUTTON_CLICK_BIZ_TYPE_NONE: DynamicButtonClickBizType.ValueType  # 0
""""""
DYNAMIC_BUTTON_CLICK_BIZ_TYPE_LIVE: DynamicButtonClickBizType.ValueType  # 1
""""""
DYNAMIC_BUTTON_CLICK_BIZ_TYPE_DYN_UP: DynamicButtonClickBizType.ValueType  # 2
""""""
Global___DynamicButtonClickBizType: _TypeAlias = DynamicButtonClickBizType  # noqa: Y015

class _POI_TYPE:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _POI_TYPEEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_POI_TYPE.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TENCENT: _POI_TYPE.ValueType  # 0
    CITY: _POI_TYPE.ValueType  # 1
    NATION: _POI_TYPE.ValueType  # 2
    BILI: _POI_TYPE.ValueType  # 3

class POI_TYPE(_POI_TYPE, metaclass=_POI_TYPEEnumTypeWrapper): ...

TENCENT: POI_TYPE.ValueType  # 0
CITY: POI_TYPE.ValueType  # 1
NATION: POI_TYPE.ValueType  # 2
BILI: POI_TYPE.ValueType  # 3
Global___POI_TYPE: _TypeAlias = POI_TYPE  # noqa: Y015

class _ReserveButtonMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ReserveButtonModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ReserveButtonMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    RESERVE_BUTTON_MODE_NONE: _ReserveButtonMode.ValueType  # 0
    """"""
    RESERVE_BUTTON_MODE_RESERVE: _ReserveButtonMode.ValueType  # 1
    """"""
    RESERVE_BUTTON_MODE_UP_CANCEL: _ReserveButtonMode.ValueType  # 2
    """"""

class ReserveButtonMode(_ReserveButtonMode, metaclass=_ReserveButtonModeEnumTypeWrapper):
    """"""

RESERVE_BUTTON_MODE_NONE: ReserveButtonMode.ValueType  # 0
""""""
RESERVE_BUTTON_MODE_RESERVE: ReserveButtonMode.ValueType  # 1
""""""
RESERVE_BUTTON_MODE_UP_CANCEL: ReserveButtonMode.ValueType  # 2
""""""
Global___ReserveButtonMode: _TypeAlias = ReserveButtonMode  # noqa: Y015

class _ReserveButtonStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ReserveButtonStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ReserveButtonStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    RESERVE_BUTTON_STATUS_NONE: _ReserveButtonStatus.ValueType  # 0
    """"""
    RESERVE_BUTTON_STATUS_UNCHECK: _ReserveButtonStatus.ValueType  # 1
    """"""
    RESERVE_BUTTON_STATUS_CHECK: _ReserveButtonStatus.ValueType  # 2
    """"""

class ReserveButtonStatus(_ReserveButtonStatus, metaclass=_ReserveButtonStatusEnumTypeWrapper):
    """"""

RESERVE_BUTTON_STATUS_NONE: ReserveButtonStatus.ValueType  # 0
""""""
RESERVE_BUTTON_STATUS_UNCHECK: ReserveButtonStatus.ValueType  # 1
""""""
RESERVE_BUTTON_STATUS_CHECK: ReserveButtonStatus.ValueType  # 2
""""""
Global___ReserveButtonStatus: _TypeAlias = ReserveButtonStatus  # noqa: Y015

@_typing.final
class AddDynamicReportReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    ACCUSED_UID_FIELD_NUMBER: _builtins.int
    DYNAMIC_ID_FIELD_NUMBER: _builtins.int
    REASON_TYPE_FIELD_NUMBER: _builtins.int
    REASON_DESC_FIELD_NUMBER: _builtins.int
    accused_uid: _builtins.int
    """"""
    dynamic_id: _builtins.str
    """"""
    reason_type: _builtins.int
    """"""
    reason_desc: _builtins.str
    """"""
    def __init__(
        self,
        *,
        accused_uid: _builtins.int = ...,
        dynamic_id: _builtins.str = ...,
        reason_type: _builtins.int = ...,
        reason_desc: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accused_uid", b"accused_uid", "dynamic_id", b"dynamic_id", "reason_desc", b"reason_desc", "reason_type", b"reason_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddDynamicReportReq: _TypeAlias = AddDynamicReportReq  # noqa: Y015

@_typing.final
class AddDynamicReportRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddDynamicReportRsp: _TypeAlias = AddDynamicReportRsp  # noqa: Y015

@_typing.final
class AdInfoDetail(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    NATION_FIELD_NUMBER: _builtins.int
    PROVINCE_FIELD_NUMBER: _builtins.int
    CITY_FIELD_NUMBER: _builtins.int
    DISTRICT_FIELD_NUMBER: _builtins.int
    nation: _builtins.str
    """"""
    province: _builtins.str
    """"""
    city: _builtins.str
    """"""
    district: _builtins.str
    """"""
    def __init__(
        self,
        *,
        nation: _builtins.str = ...,
        province: _builtins.str = ...,
        city: _builtins.str = ...,
        district: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["city", b"city", "district", b"district", "nation", b"nation", "province", b"province"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AdInfoDetail: _TypeAlias = AdInfoDetail  # noqa: Y015

@_typing.final
class AttachCardButtonReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    CUR_BTN_STATUS_FIELD_NUMBER: _builtins.int
    DYNAMIC_ID_FIELD_NUMBER: _builtins.int
    ATTACH_CARD_TYPE_FIELD_NUMBER: _builtins.int
    SPM_ID_FIELD_NUMBER: _builtins.int
    RESERVE_TOTAL_FIELD_NUMBER: _builtins.int
    DYNAMIC_ID_STR_FIELD_NUMBER: _builtins.int
    CARD_TYPE_FIELD_NUMBER: _builtins.int
    cur_btn_status: _builtins.int
    """"""
    dynamic_id: _builtins.int
    """"""
    attach_card_type: _dynamic_pb2.AttachCardType.ValueType
    """"""
    spm_id: _builtins.str
    """"""
    reserve_total: _builtins.int
    """"""
    dynamic_id_str: _builtins.str
    """"""
    card_type: _builtins.str
    """"""
    def __init__(
        self,
        *,
        cur_btn_status: _builtins.int = ...,
        dynamic_id: _builtins.int = ...,
        attach_card_type: _dynamic_pb2.AttachCardType.ValueType = ...,
        spm_id: _builtins.str = ...,
        reserve_total: _builtins.int = ...,
        dynamic_id_str: _builtins.str = ...,
        card_type: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attach_card_type", b"attach_card_type", "card_type", b"card_type", "cur_btn_status", b"cur_btn_status", "dynamic_id", b"dynamic_id", "dynamic_id_str", b"dynamic_id_str", "reserve_total", b"reserve_total", "spm_id", b"spm_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AttachCardButtonReq: _TypeAlias = AttachCardButtonReq  # noqa: Y015

@_typing.final
class AttachCardButtonRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    FINAL_BTN_STATUS_FIELD_NUMBER: _builtins.int
    TOAST_FIELD_NUMBER: _builtins.int
    DESC_UPDATE_FIELD_NUMBER: _builtins.int
    RESERVE_UPDATE_FIELD_NUMBER: _builtins.int
    final_btn_status: _builtins.int
    """"""
    toast: _builtins.str
    """"""
    desc_update: _builtins.str
    """"""
    reserve_update: _builtins.int
    """"""
    def __init__(
        self,
        *,
        final_btn_status: _builtins.int = ...,
        toast: _builtins.str = ...,
        desc_update: _builtins.str = ...,
        reserve_update: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["desc_update", b"desc_update", "final_btn_status", b"final_btn_status", "reserve_update", b"reserve_update", "toast", b"toast"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AttachCardButtonRsp: _TypeAlias = AttachCardButtonRsp  # noqa: Y015

@_typing.final
class ConfigAB(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    ENTRY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    entry: Global___ConfigABEntry.ValueType
    """"""
    value: _builtins.int
    """"""
    def __init__(
        self,
        *,
        entry: Global___ConfigABEntry.ValueType = ...,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entry", b"entry", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ConfigAB: _TypeAlias = ConfigAB  # noqa: Y015

@_typing.final
class ConfigReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ConfigReq: _TypeAlias = ConfigReq  # noqa: Y015

@_typing.final
class ConfigRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    AB_ENTRIES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ab_entries(self) -> _containers.RepeatedCompositeFieldContainer[Global___ConfigAB]:
        """"""

    def __init__(
        self,
        *,
        ab_entries: _abc.Iterable[Global___ConfigAB] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ab_entries", b"ab_entries"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ConfigRsp: _TypeAlias = ConfigRsp  # noqa: Y015

@_typing.final
class CreateDynReq(_message.Message):
    """创建动态-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    META_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    SCENE_FIELD_NUMBER: _builtins.int
    PICS_FIELD_NUMBER: _builtins.int
    REPOST_SRC_FIELD_NUMBER: _builtins.int
    VIDEO_FIELD_NUMBER: _builtins.int
    SKETCH_TYPE_FIELD_NUMBER: _builtins.int
    SKETCH_FIELD_NUMBER: _builtins.int
    PROGRAM_FIELD_NUMBER: _builtins.int
    DYN_TAG_FIELD_NUMBER: _builtins.int
    ATTACH_CARD_FIELD_NUMBER: _builtins.int
    OPTION_FIELD_NUMBER: _builtins.int
    TOPIC_FIELD_NUMBER: _builtins.int
    UPLOAD_ID_FIELD_NUMBER: _builtins.int
    scene: _dynamic_pb2.CreateScene.ValueType
    """发布类型"""
    sketch_type: _builtins.int
    """通用模板类型：2048方图 2049竖图 其他值无效"""
    upload_id: _builtins.str
    """"""
    @_builtins.property
    def meta(self) -> _dynamic_pb2.UserCreateMeta:
        """用户创建接口meta信息"""

    @_builtins.property
    def content(self) -> _dynamic_pb2.CreateContent:
        """发布的内容"""

    @_builtins.property
    def pics(self) -> _containers.RepeatedCompositeFieldContainer[_dynamic_pb2.CreatePic]:
        """图片内容"""

    @_builtins.property
    def repost_src(self) -> _dynamic_pb2.DynIdentity:
        """转发源"""

    @_builtins.property
    def video(self) -> _dynamic_pb2.CreateDynVideo:
        """动态视频"""

    @_builtins.property
    def sketch(self) -> _dynamic_pb2.Sketch:
        """通用模板的元内容（网页内容）"""

    @_builtins.property
    def program(self) -> _dynamic_pb2.Program:
        """小程序的内容"""

    @_builtins.property
    def dyn_tag(self) -> _dynamic_pb2.CreateTag:
        """动态附加小卡"""

    @_builtins.property
    def attach_card(self) -> _dynamic_pb2.CreateAttachCard:
        """动态附加大卡"""

    @_builtins.property
    def option(self) -> _dynamic_pb2.CreateOption:
        """特殊的创建选项"""

    @_builtins.property
    def topic(self) -> _dynamic_pb2.CreateTopic:
        """"""

    def __init__(
        self,
        *,
        meta: _dynamic_pb2.UserCreateMeta | None = ...,
        content: _dynamic_pb2.CreateContent | None = ...,
        scene: _dynamic_pb2.CreateScene.ValueType = ...,
        pics: _abc.Iterable[_dynamic_pb2.CreatePic] | None = ...,
        repost_src: _dynamic_pb2.DynIdentity | None = ...,
        video: _dynamic_pb2.CreateDynVideo | None = ...,
        sketch_type: _builtins.int = ...,
        sketch: _dynamic_pb2.Sketch | None = ...,
        program: _dynamic_pb2.Program | None = ...,
        dyn_tag: _dynamic_pb2.CreateTag | None = ...,
        attach_card: _dynamic_pb2.CreateAttachCard | None = ...,
        option: _dynamic_pb2.CreateOption | None = ...,
        topic: _dynamic_pb2.CreateTopic | None = ...,
        upload_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["attach_card", b"attach_card", "content", b"content", "dyn_tag", b"dyn_tag", "meta", b"meta", "option", b"option", "program", b"program", "repost_src", b"repost_src", "sketch", b"sketch", "topic", b"topic", "video", b"video"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attach_card", b"attach_card", "content", b"content", "dyn_tag", b"dyn_tag", "meta", b"meta", "option", b"option", "pics", b"pics", "program", b"program", "repost_src", b"repost_src", "scene", b"scene", "sketch", b"sketch", "sketch_type", b"sketch_type", "topic", b"topic", "upload_id", b"upload_id", "video", b"video"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateDynReq: _TypeAlias = CreateDynReq  # noqa: Y015

@_typing.final
class CreateInitCheckReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    SCENE_FIELD_NUMBER: _builtins.int
    META_FIELD_NUMBER: _builtins.int
    REPOST_FIELD_NUMBER: _builtins.int
    scene: _dynamic_pb2.CreateInitCheckScene.ValueType
    """"""
    @_builtins.property
    def meta(self) -> _dynamic_pb2.MetaDataCtrl:
        """"""

    @_builtins.property
    def repost(self) -> _dynamic_pb2.RepostInitCheck:
        """"""

    def __init__(
        self,
        *,
        scene: _dynamic_pb2.CreateInitCheckScene.ValueType = ...,
        meta: _dynamic_pb2.MetaDataCtrl | None = ...,
        repost: _dynamic_pb2.RepostInitCheck | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["meta", b"meta", "repost", b"repost"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["meta", b"meta", "repost", b"repost", "scene", b"scene"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateInitCheckReq: _TypeAlias = CreateInitCheckReq  # noqa: Y015

@_typing.final
class CreatePageCommercialInfo(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    LABEL_TEXT_FIELD_NUMBER: _builtins.int
    DESC_FIELD_NUMBER: _builtins.int
    label_text: _builtins.str
    """"""
    desc: _builtins.str
    """"""
    def __init__(
        self,
        *,
        label_text: _builtins.str = ...,
        desc: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["desc", b"desc", "label_text", b"label_text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreatePageCommercialInfo: _TypeAlias = CreatePageCommercialInfo  # noqa: Y015

@_typing.final
class CreatePageInfosReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TOPIC_ID_FIELD_NUMBER: _builtins.int
    COMMERCIAL_ENTITY_TYPE_FIELD_NUMBER: _builtins.int
    COMMERCIAL_ENTITY_ID_FIELD_NUMBER: _builtins.int
    topic_id: _builtins.int
    """"""
    commercial_entity_type: _builtins.int
    """"""
    commercial_entity_id: _builtins.int
    """"""
    def __init__(
        self,
        *,
        topic_id: _builtins.int = ...,
        commercial_entity_type: _builtins.int = ...,
        commercial_entity_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commercial_entity_id", b"commercial_entity_id", "commercial_entity_type", b"commercial_entity_type", "topic_id", b"topic_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreatePageInfosReq: _TypeAlias = CreatePageInfosReq  # noqa: Y015

@_typing.final
class CreatePageInfosRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TOPIC_FIELD_NUMBER: _builtins.int
    COMMERCIAL_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def topic(self) -> Global___CreatePageTopicInfo:
        """"""

    @_builtins.property
    def commercial(self) -> Global___CreatePageCommercialInfo:
        """"""

    def __init__(
        self,
        *,
        topic: Global___CreatePageTopicInfo | None = ...,
        commercial: Global___CreatePageCommercialInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["commercial", b"commercial", "topic", b"topic"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commercial", b"commercial", "topic", b"topic"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreatePageInfosRsp: _TypeAlias = CreatePageInfosRsp  # noqa: Y015

@_typing.final
class CreatePageTopicInfo(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TOPIC_ID_FIELD_NUMBER: _builtins.int
    TOPIC_NAME_FIELD_NUMBER: _builtins.int
    topic_id: _builtins.int
    """"""
    topic_name: _builtins.str
    """"""
    def __init__(
        self,
        *,
        topic_id: _builtins.int = ...,
        topic_name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["topic_id", b"topic_id", "topic_name", b"topic_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreatePageTopicInfo: _TypeAlias = CreatePageTopicInfo  # noqa: Y015

@_typing.final
class CreatePermissionButtonClickReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    type: Global___DynamicButtonClickBizType.ValueType
    """"""
    def __init__(
        self,
        *,
        type: Global___DynamicButtonClickBizType.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreatePermissionButtonClickReq: _TypeAlias = CreatePermissionButtonClickReq  # noqa: Y015

@_typing.final
class CreatePermissionButtonClickRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreatePermissionButtonClickRsp: _TypeAlias = CreatePermissionButtonClickRsp  # noqa: Y015

@_typing.final
class CreatePlusButtonClickReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreatePlusButtonClickReq: _TypeAlias = CreatePlusButtonClickReq  # noqa: Y015

@_typing.final
class CreatePlusButtonClickRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreatePlusButtonClickRsp: _TypeAlias = CreatePlusButtonClickRsp  # noqa: Y015

@_typing.final
class DynamicButtonClickReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BIZ_TYPE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def biz_type(self) -> _containers.RepeatedScalarFieldContainer[Global___DynamicButtonClickBizType.ValueType]:
        """"""

    def __init__(
        self,
        *,
        biz_type: _abc.Iterable[Global___DynamicButtonClickBizType.ValueType] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["biz_type", b"biz_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DynamicButtonClickReq: _TypeAlias = DynamicButtonClickReq  # noqa: Y015

@_typing.final
class DynamicButtonClickRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DynamicButtonClickRsp: _TypeAlias = DynamicButtonClickRsp  # noqa: Y015

@_typing.final
class DynamicRepostReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    UID_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    REPOST_SRC_FIELD_NUMBER: _builtins.int
    OPTION_FIELD_NUMBER: _builtins.int
    TOPIC_FIELD_NUMBER: _builtins.int
    UPLOAD_ID_FIELD_NUMBER: _builtins.int
    uid: _builtins.int
    """"""
    upload_id: _builtins.str
    """"""
    @_builtins.property
    def content(self) -> _dynamic_pb2.CreateContent:
        """"""

    @_builtins.property
    def repost_src(self) -> _dynamic_pb2.DynIdentity:
        """"""

    @_builtins.property
    def option(self) -> _dynamic_pb2.CreateOption:
        """"""

    @_builtins.property
    def topic(self) -> _dynamic_pb2.CreateTopic:
        """"""

    def __init__(
        self,
        *,
        uid: _builtins.int = ...,
        content: _dynamic_pb2.CreateContent | None = ...,
        repost_src: _dynamic_pb2.DynIdentity | None = ...,
        option: _dynamic_pb2.CreateOption | None = ...,
        topic: _dynamic_pb2.CreateTopic | None = ...,
        upload_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "option", b"option", "repost_src", b"repost_src", "topic", b"topic"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "option", b"option", "repost_src", b"repost_src", "topic", b"topic", "uid", b"uid", "upload_id", b"upload_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DynamicRepostReq: _TypeAlias = DynamicRepostReq  # noqa: Y015

@_typing.final
class DynamicThumbReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    UID_FIELD_NUMBER: _builtins.int
    DYN_ID_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    RID_FIELD_NUMBER: _builtins.int
    SPEC_TYPE_FIELD_NUMBER: _builtins.int
    UP_FIELD_NUMBER: _builtins.int
    FROM_FIELD_NUMBER: _builtins.int
    uid: _builtins.int
    """"""
    dyn_id: _builtins.int
    """"""
    type: _builtins.int
    """"""
    rid: _builtins.int
    """"""
    spec_type: _builtins.int
    """"""
    up: _builtins.int
    """"""
    def __init__(
        self,
        *,
        uid: _builtins.int = ...,
        dyn_id: _builtins.int = ...,
        type: _builtins.int = ...,
        rid: _builtins.int = ...,
        spec_type: _builtins.int = ...,
        up: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dyn_id", b"dyn_id", "from", b"from", "rid", b"rid", "spec_type", b"spec_type", "type", b"type", "uid", b"uid", "up", b"up"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DynamicThumbReq: _TypeAlias = DynamicThumbReq  # noqa: Y015

@_typing.final
class DynamicThumbRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DynamicThumbRsp: _TypeAlias = DynamicThumbRsp  # noqa: Y015

@_typing.final
class EditDynReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    DYN_ID_FIELD_NUMBER: _builtins.int
    SCENE_FIELD_NUMBER: _builtins.int
    META_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    PICS_FIELD_NUMBER: _builtins.int
    REPOST_SRC_FIELD_NUMBER: _builtins.int
    DYN_TAG_FIELD_NUMBER: _builtins.int
    ATTACH_CARD_FIELD_NUMBER: _builtins.int
    OPTION_FIELD_NUMBER: _builtins.int
    TOPIC_FIELD_NUMBER: _builtins.int
    UPLOAD_ID_FIELD_NUMBER: _builtins.int
    dyn_id: _builtins.int
    """"""
    scene: _dynamic_pb2.CreateScene.ValueType
    """"""
    upload_id: _builtins.str
    """"""
    @_builtins.property
    def meta(self) -> _dynamic_pb2.UserCreateMeta:
        """"""

    @_builtins.property
    def content(self) -> _dynamic_pb2.CreateContent:
        """"""

    @_builtins.property
    def pics(self) -> _containers.RepeatedCompositeFieldContainer[_dynamic_pb2.CreatePic]:
        """"""

    @_builtins.property
    def repost_src(self) -> _dynamic_pb2.DynIdentity:
        """"""

    @_builtins.property
    def dyn_tag(self) -> _dynamic_pb2.CreateTag:
        """"""

    @_builtins.property
    def attach_card(self) -> _dynamic_pb2.CreateAttachCard:
        """"""

    @_builtins.property
    def option(self) -> _dynamic_pb2.CreateOption:
        """"""

    @_builtins.property
    def topic(self) -> _dynamic_pb2.CreateTopic:
        """"""

    def __init__(
        self,
        *,
        dyn_id: _builtins.int = ...,
        scene: _dynamic_pb2.CreateScene.ValueType = ...,
        meta: _dynamic_pb2.UserCreateMeta | None = ...,
        content: _dynamic_pb2.CreateContent | None = ...,
        pics: _abc.Iterable[_dynamic_pb2.CreatePic] | None = ...,
        repost_src: _dynamic_pb2.DynIdentity | None = ...,
        dyn_tag: _dynamic_pb2.CreateTag | None = ...,
        attach_card: _dynamic_pb2.CreateAttachCard | None = ...,
        option: _dynamic_pb2.CreateOption | None = ...,
        topic: _dynamic_pb2.CreateTopic | None = ...,
        upload_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["attach_card", b"attach_card", "content", b"content", "dyn_tag", b"dyn_tag", "meta", b"meta", "option", b"option", "repost_src", b"repost_src", "topic", b"topic"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attach_card", b"attach_card", "content", b"content", "dyn_id", b"dyn_id", "dyn_tag", b"dyn_tag", "meta", b"meta", "option", b"option", "pics", b"pics", "repost_src", b"repost_src", "scene", b"scene", "topic", b"topic", "upload_id", b"upload_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EditDynReq: _TypeAlias = EditDynReq  # noqa: Y015

@_typing.final
class EditDynRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    STATE_FIELD_NUMBER: _builtins.int
    TOTAST_FIELD_NUMBER: _builtins.int
    state: _builtins.int
    """"""
    totast: _builtins.str
    """"""
    def __init__(
        self,
        *,
        state: _builtins.int = ...,
        totast: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["state", b"state", "totast", b"totast"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EditDynRsp: _TypeAlias = EditDynRsp  # noqa: Y015

@_typing.final
class GetEditDynInfoReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    DYN_ID_FIELD_NUMBER: _builtins.int
    SCENE_FIELD_NUMBER: _builtins.int
    META_FIELD_NUMBER: _builtins.int
    REPOST_FIELD_NUMBER: _builtins.int
    dyn_id: _builtins.int
    """"""
    scene: _dynamic_pb2.CreateScene.ValueType
    """"""
    @_builtins.property
    def meta(self) -> _dynamic_pb2.MetaDataCtrl:
        """"""

    @_builtins.property
    def repost(self) -> _dynamic_pb2.RepostInitCheck:
        """"""

    def __init__(
        self,
        *,
        dyn_id: _builtins.int = ...,
        scene: _dynamic_pb2.CreateScene.ValueType = ...,
        meta: _dynamic_pb2.MetaDataCtrl | None = ...,
        repost: _dynamic_pb2.RepostInitCheck | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["meta", b"meta", "repost", b"repost"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dyn_id", b"dyn_id", "meta", b"meta", "repost", b"repost", "scene", b"scene"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetEditDynInfoReq: _TypeAlias = GetEditDynInfoReq  # noqa: Y015

@_typing.final
class GetEditDynInfoRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    PICS_FIELD_NUMBER: _builtins.int
    ORIG_DYN_ID_FIELD_NUMBER: _builtins.int
    PRE_DYN_ID_FIELD_NUMBER: _builtins.int
    TOPIC_INFOS_FIELD_NUMBER: _builtins.int
    ATTACH_CARD_FIELD_NUMBER: _builtins.int
    SETTING_FIELD_NUMBER: _builtins.int
    PERMISSION_FIELD_NUMBER: _builtins.int
    SHARE_INFO_FIELD_NUMBER: _builtins.int
    YELLOW_BAR_FIELD_NUMBER: _builtins.int
    PLUS_RED_DOT_FIELD_NUMBER: _builtins.int
    ONLY_FANS_FIELD_NUMBER: _builtins.int
    EDIT_ALERT_MSG_FIELD_NUMBER: _builtins.int
    orig_dyn_id: _builtins.int
    """"""
    pre_dyn_id: _builtins.int
    """"""
    only_fans: _builtins.int
    """"""
    edit_alert_msg: _builtins.str
    """"""
    @_builtins.property
    def pics(self) -> _containers.RepeatedCompositeFieldContainer[_dynamic_pb2.CreatePic]:
        """"""

    @_builtins.property
    def topic_infos(self) -> _containers.RepeatedCompositeFieldContainer[Global___CreatePageTopicInfo]:
        """"""

    @_builtins.property
    def attach_card(self) -> _dynamic_pb2.CreateAttachCard:
        """"""

    @_builtins.property
    def setting(self) -> _dynamic_pb2.PublishSetting:
        """"""

    @_builtins.property
    def permission(self) -> _dynamic_pb2.UpPermission:
        """"""

    @_builtins.property
    def share_info(self) -> _dynamic_pb2.ShareChannel:
        """"""

    @_builtins.property
    def yellow_bar(self) -> _dynamic_pb2.PublishYellowBar:
        """"""

    @_builtins.property
    def plus_red_dot(self) -> _dynamic_pb2.PlusRedDot:
        """"""

    def __init__(
        self,
        *,
        pics: _abc.Iterable[_dynamic_pb2.CreatePic] | None = ...,
        orig_dyn_id: _builtins.int = ...,
        pre_dyn_id: _builtins.int = ...,
        topic_infos: _abc.Iterable[Global___CreatePageTopicInfo] | None = ...,
        attach_card: _dynamic_pb2.CreateAttachCard | None = ...,
        setting: _dynamic_pb2.PublishSetting | None = ...,
        permission: _dynamic_pb2.UpPermission | None = ...,
        share_info: _dynamic_pb2.ShareChannel | None = ...,
        yellow_bar: _dynamic_pb2.PublishYellowBar | None = ...,
        plus_red_dot: _dynamic_pb2.PlusRedDot | None = ...,
        only_fans: _builtins.int = ...,
        edit_alert_msg: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["attach_card", b"attach_card", "permission", b"permission", "plus_red_dot", b"plus_red_dot", "setting", b"setting", "share_info", b"share_info", "yellow_bar", b"yellow_bar"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attach_card", b"attach_card", "edit_alert_msg", b"edit_alert_msg", "only_fans", b"only_fans", "orig_dyn_id", b"orig_dyn_id", "permission", b"permission", "pics", b"pics", "plus_red_dot", b"plus_red_dot", "pre_dyn_id", b"pre_dyn_id", "setting", b"setting", "share_info", b"share_info", "topic_infos", b"topic_infos", "yellow_bar", b"yellow_bar"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetEditDynInfoRsp: _TypeAlias = GetEditDynInfoRsp  # noqa: Y015

@_typing.final
class GoodsAttachCardPreviewReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    ITEM_IDS_FIELD_NUMBER: _builtins.int
    DYN_ID_FIELD_NUMBER: _builtins.int
    MID_FIELD_NUMBER: _builtins.int
    META_FIELD_NUMBER: _builtins.int
    dyn_id: _builtins.int
    """"""
    mid: _builtins.int
    """"""
    @_builtins.property
    def item_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """"""

    @_builtins.property
    def meta(self) -> _dynamic_pb2.MetaDataCtrl:
        """"""

    def __init__(
        self,
        *,
        item_ids: _abc.Iterable[_builtins.int] | None = ...,
        dyn_id: _builtins.int = ...,
        mid: _builtins.int = ...,
        meta: _dynamic_pb2.MetaDataCtrl | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["meta", b"meta"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dyn_id", b"dyn_id", "item_ids", b"item_ids", "meta", b"meta", "mid", b"mid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GoodsAttachCardPreviewReq: _TypeAlias = GoodsAttachCardPreviewReq  # noqa: Y015

@_typing.final
class GoodsAttachCardPreviewRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class GoodsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        @_builtins.property
        def value(self) -> Global___GoodsItem: ...
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: Global___GoodsItem | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    GOODS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def goods(self) -> _containers.MessageMap[_builtins.int, Global___GoodsItem]:
        """"""

    def __init__(
        self,
        *,
        goods: _abc.Mapping[_builtins.int, Global___GoodsItem] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["goods", b"goods"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GoodsAttachCardPreviewRsp: _TypeAlias = GoodsAttachCardPreviewRsp  # noqa: Y015

@_typing.final
class GoodsItem(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    ITEMS_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    BRIEF_FIELD_NUMBER: _builtins.int
    IMG_FIELD_NUMBER: _builtins.int
    PRICE_FIELD_NUMBER: _builtins.int
    PRICE_STR_FIELD_NUMBER: _builtins.int
    ICON_NAME_FIELD_NUMBER: _builtins.int
    ICON_URL_FIELD_NUMBER: _builtins.int
    JUMP_LINK_FIELD_NUMBER: _builtins.int
    JUMP_LINK_DESC_FIELD_NUMBER: _builtins.int
    items_id: _builtins.int
    """"""
    name: _builtins.str
    """"""
    brief: _builtins.str
    """"""
    img: _builtins.str
    """"""
    price: _builtins.float
    """"""
    price_str: _builtins.str
    """"""
    icon_name: _builtins.str
    """"""
    icon_url: _builtins.str
    """"""
    jump_link: _builtins.str
    """"""
    jump_link_desc: _builtins.str
    """"""
    def __init__(
        self,
        *,
        items_id: _builtins.int = ...,
        name: _builtins.str = ...,
        brief: _builtins.str = ...,
        img: _builtins.str = ...,
        price: _builtins.float = ...,
        price_str: _builtins.str = ...,
        icon_name: _builtins.str = ...,
        icon_url: _builtins.str = ...,
        jump_link: _builtins.str = ...,
        jump_link_desc: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["brief", b"brief", "icon_name", b"icon_name", "icon_url", b"icon_url", "img", b"img", "items_id", b"items_id", "jump_link", b"jump_link", "jump_link_desc", b"jump_link_desc", "name", b"name", "price", b"price", "price_str", b"price_str"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GoodsItem: _TypeAlias = GoodsItem  # noqa: Y015

@_typing.final
class HomeBubbleReportReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TRACK_ID_FIELD_NUMBER: _builtins.int
    track_id: _builtins.str
    """"""
    def __init__(
        self,
        *,
        track_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["track_id", b"track_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HomeBubbleReportReq: _TypeAlias = HomeBubbleReportReq  # noqa: Y015

@_typing.final
class HomeBubbleReportRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HomeBubbleReportRsp: _TypeAlias = HomeBubbleReportRsp  # noqa: Y015

@_typing.final
class HotSearchReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HotSearchReq: _TypeAlias = HotSearchReq  # noqa: Y015

@_typing.final
class HotSearchRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Item(_message.Message):
        """"""

        DESCRIPTOR: _descriptor.Descriptor

        WORDS_FIELD_NUMBER: _builtins.int
        words: _builtins.str
        """"""
        def __init__(
            self,
            *,
            words: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["words", b"words"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    ITEMS_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    version: _builtins.str
    """"""
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___HotSearchRsp.Item]:
        """"""

    def __init__(
        self,
        *,
        items: _abc.Iterable[Global___HotSearchRsp.Item] | None = ...,
        version: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HotSearchRsp: _TypeAlias = HotSearchRsp  # noqa: Y015

@_typing.final
class ICreateGoodsReplySyncReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    UID_FIELD_NUMBER: _builtins.int
    GOODS_ID_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    SCENE_FIELD_NUMBER: _builtins.int
    PICS_FIELD_NUMBER: _builtins.int
    uid: _builtins.int
    """"""
    goods_id: _builtins.int
    """"""
    scene: _dynamic_pb2.CreateScene.ValueType
    """"""
    @_builtins.property
    def content(self) -> _dynamic_pb2.CreateContent:
        """"""

    @_builtins.property
    def pics(self) -> _containers.RepeatedCompositeFieldContainer[_dynamic_pb2.CreatePic]:
        """"""

    def __init__(
        self,
        *,
        uid: _builtins.int = ...,
        goods_id: _builtins.int = ...,
        content: _dynamic_pb2.CreateContent | None = ...,
        scene: _dynamic_pb2.CreateScene.ValueType = ...,
        pics: _abc.Iterable[_dynamic_pb2.CreatePic] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["content", b"content"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "goods_id", b"goods_id", "pics", b"pics", "scene", b"scene", "uid", b"uid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ICreateGoodsReplySyncReq: _TypeAlias = ICreateGoodsReplySyncReq  # noqa: Y015

@_typing.final
class ICreateResp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    DYN_ID_FIELD_NUMBER: _builtins.int
    DYN_TYPE_FIELD_NUMBER: _builtins.int
    DYN_RID_FIELD_NUMBER: _builtins.int
    dyn_id: _builtins.int
    """"""
    dyn_type: _builtins.int
    """"""
    dyn_rid: _builtins.int
    """"""
    def __init__(
        self,
        *,
        dyn_id: _builtins.int = ...,
        dyn_type: _builtins.int = ...,
        dyn_rid: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dyn_id", b"dyn_id", "dyn_rid", b"dyn_rid", "dyn_type", b"dyn_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ICreateResp: _TypeAlias = ICreateResp  # noqa: Y015

@_typing.final
class LbsLocation(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    LAT_FIELD_NUMBER: _builtins.int
    LNG_FIELD_NUMBER: _builtins.int
    lat: _builtins.float
    """"""
    lng: _builtins.float
    """"""
    def __init__(
        self,
        *,
        lat: _builtins.float = ...,
        lng: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["lat", b"lat", "lng", b"lng"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LbsLocation: _TypeAlias = LbsLocation  # noqa: Y015

@_typing.final
class NearbyPoiDetail(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    LOCATION_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    POI_FIELD_NUMBER: _builtins.int
    ADDRESS_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    SHOW_TITLE_FIELD_NUMBER: _builtins.int
    DISTANCE_FIELD_NUMBER: _builtins.int
    SHOW_DISTANCE_FIELD_NUMBER: _builtins.int
    AD_INFO_FIELD_NUMBER: _builtins.int
    ANCESTORS_FIELD_NUMBER: _builtins.int
    type: Global___POI_TYPE.ValueType
    """"""
    poi: _builtins.str
    """"""
    address: _builtins.str
    """"""
    title: _builtins.str
    """"""
    show_title: _builtins.str
    """"""
    distance: _builtins.float
    """"""
    show_distance: _builtins.str
    """"""
    @_builtins.property
    def location(self) -> Global___LbsLocation:
        """"""

    @_builtins.property
    def ad_info(self) -> Global___AdInfoDetail:
        """"""

    @_builtins.property
    def ancestors(self) -> _containers.RepeatedCompositeFieldContainer[Global___PoiId]:
        """"""

    def __init__(
        self,
        *,
        location: Global___LbsLocation | None = ...,
        type: Global___POI_TYPE.ValueType = ...,
        poi: _builtins.str = ...,
        address: _builtins.str = ...,
        title: _builtins.str = ...,
        show_title: _builtins.str = ...,
        distance: _builtins.float = ...,
        show_distance: _builtins.str = ...,
        ad_info: Global___AdInfoDetail | None = ...,
        ancestors: _abc.Iterable[Global___PoiId] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ad_info", b"ad_info", "location", b"location"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ad_info", b"ad_info", "address", b"address", "ancestors", b"ancestors", "distance", b"distance", "location", b"location", "poi", b"poi", "show_distance", b"show_distance", "show_title", b"show_title", "title", b"title", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NearbyPoiDetail: _TypeAlias = NearbyPoiDetail  # noqa: Y015

@_typing.final
class NearbyPoiListItem(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    POI_INFO_FIELD_NUMBER: _builtins.int
    USER_COUNT_FIELD_NUMBER: _builtins.int
    user_count: _builtins.int
    """"""
    @_builtins.property
    def poi_info(self) -> Global___NearbyPoiDetail:
        """"""

    def __init__(
        self,
        *,
        poi_info: Global___NearbyPoiDetail | None = ...,
        user_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["poi_info", b"poi_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["poi_info", b"poi_info", "user_count", b"user_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NearbyPoiListItem: _TypeAlias = NearbyPoiListItem  # noqa: Y015

@_typing.final
class NearbyPoiListReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    LAT_FIELD_NUMBER: _builtins.int
    LNG_FIELD_NUMBER: _builtins.int
    PAGE_FIELD_NUMBER: _builtins.int
    PAGE_SIZE_FIELD_NUMBER: _builtins.int
    lat: _builtins.float
    """"""
    lng: _builtins.float
    """"""
    page: _builtins.int
    """"""
    page_size: _builtins.int
    """"""
    def __init__(
        self,
        *,
        lat: _builtins.float = ...,
        lng: _builtins.float = ...,
        page: _builtins.int = ...,
        page_size: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["lat", b"lat", "lng", b"lng", "page", b"page", "page_size", b"page_size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NearbyPoiListReq: _TypeAlias = NearbyPoiListReq  # noqa: Y015

@_typing.final
class NearbyPoiListRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    HAS_MORE_FIELD_NUMBER: _builtins.int
    POIS_FIELD_NUMBER: _builtins.int
    has_more: _builtins.bool
    """"""
    @_builtins.property
    def pois(self) -> _containers.RepeatedCompositeFieldContainer[Global___NearbyPoiListItem]:
        """"""

    def __init__(
        self,
        *,
        has_more: _builtins.bool = ...,
        pois: _abc.Iterable[Global___NearbyPoiListItem] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["has_more", b"has_more", "pois", b"pois"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NearbyPoiListRsp: _TypeAlias = NearbyPoiListRsp  # noqa: Y015

@_typing.final
class PoiDetail(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    LOCATION_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    POI_FIELD_NUMBER: _builtins.int
    ADDRESS_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    SHOW_TITLE_FIELD_NUMBER: _builtins.int
    DISTANCE_FIELD_NUMBER: _builtins.int
    SHOW_DISTANCE_FIELD_NUMBER: _builtins.int
    AD_INFO_FIELD_NUMBER: _builtins.int
    ANCESTORS_FIELD_NUMBER: _builtins.int
    type: Global___POI_TYPE.ValueType
    """"""
    poi: _builtins.str
    """"""
    address: _builtins.str
    """"""
    title: _builtins.str
    """"""
    show_title: _builtins.str
    """"""
    distance: _builtins.float
    """"""
    show_distance: _builtins.str
    """"""
    @_builtins.property
    def location(self) -> Global___LbsLocation:
        """"""

    @_builtins.property
    def ad_info(self) -> Global___AdInfoDetail:
        """"""

    @_builtins.property
    def ancestors(self) -> Global___PoiId:
        """"""

    def __init__(
        self,
        *,
        location: Global___LbsLocation | None = ...,
        type: Global___POI_TYPE.ValueType = ...,
        poi: _builtins.str = ...,
        address: _builtins.str = ...,
        title: _builtins.str = ...,
        show_title: _builtins.str = ...,
        distance: _builtins.float = ...,
        show_distance: _builtins.str = ...,
        ad_info: Global___AdInfoDetail | None = ...,
        ancestors: Global___PoiId | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ad_info", b"ad_info", "ancestors", b"ancestors", "location", b"location"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ad_info", b"ad_info", "address", b"address", "ancestors", b"ancestors", "distance", b"distance", "location", b"location", "poi", b"poi", "show_distance", b"show_distance", "show_title", b"show_title", "title", b"title", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PoiDetail: _TypeAlias = PoiDetail  # noqa: Y015

@_typing.final
class PoiId(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    POI_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    poi: _builtins.str
    """"""
    type: _builtins.int
    """"""
    def __init__(
        self,
        *,
        poi: _builtins.str = ...,
        type: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["poi", b"poi", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PoiId: _TypeAlias = PoiId  # noqa: Y015

@_typing.final
class PoiListItem(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    POI_INFO_FIELD_NUMBER: _builtins.int
    USER_COUNT_FIELD_NUMBER: _builtins.int
    user_count: _builtins.int
    """"""
    @_builtins.property
    def poi_info(self) -> Global___PoiDetail:
        """"""

    def __init__(
        self,
        *,
        poi_info: Global___PoiDetail | None = ...,
        user_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["poi_info", b"poi_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["poi_info", b"poi_info", "user_count", b"user_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PoiListItem: _TypeAlias = PoiListItem  # noqa: Y015

@_typing.final
class ReserveButtonClickReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    UID_FIELD_NUMBER: _builtins.int
    RESERVE_ID_FIELD_NUMBER: _builtins.int
    RESERVE_TOTAL_FIELD_NUMBER: _builtins.int
    CUR_BTN_STATUS_FIELD_NUMBER: _builtins.int
    SPMID_FIELD_NUMBER: _builtins.int
    DYN_ID_FIELD_NUMBER: _builtins.int
    DYN_TYPE_FIELD_NUMBER: _builtins.int
    uid: _builtins.int
    """"""
    reserve_id: _builtins.int
    """"""
    reserve_total: _builtins.int
    """"""
    cur_btn_status: _builtins.int
    """"""
    spmid: _builtins.str
    """"""
    dyn_id: _builtins.int
    """"""
    dyn_type: _builtins.int
    """"""
    def __init__(
        self,
        *,
        uid: _builtins.int = ...,
        reserve_id: _builtins.int = ...,
        reserve_total: _builtins.int = ...,
        cur_btn_status: _builtins.int = ...,
        spmid: _builtins.str = ...,
        dyn_id: _builtins.int = ...,
        dyn_type: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cur_btn_status", b"cur_btn_status", "dyn_id", b"dyn_id", "dyn_type", b"dyn_type", "reserve_id", b"reserve_id", "reserve_total", b"reserve_total", "spmid", b"spmid", "uid", b"uid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReserveButtonClickReq: _TypeAlias = ReserveButtonClickReq  # noqa: Y015

@_typing.final
class ReserveButtonClickResp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    FINAL_BTN_STATUS_FIELD_NUMBER: _builtins.int
    BTN_MODE_FIELD_NUMBER: _builtins.int
    RESERVE_UPDATE_FIELD_NUMBER: _builtins.int
    DESC_UPDATE_FIELD_NUMBER: _builtins.int
    HAS_ACTIVITY_FIELD_NUMBER: _builtins.int
    ACTIVITY_URL_FIELD_NUMBER: _builtins.int
    TOAST_FIELD_NUMBER: _builtins.int
    final_btn_status: Global___ReserveButtonStatus.ValueType
    """"""
    btn_mode: Global___ReserveButtonMode.ValueType
    """"""
    reserve_update: _builtins.int
    """"""
    desc_update: _builtins.str
    """"""
    has_activity: _builtins.bool
    """"""
    activity_url: _builtins.str
    """"""
    toast: _builtins.str
    """"""
    def __init__(
        self,
        *,
        final_btn_status: Global___ReserveButtonStatus.ValueType = ...,
        btn_mode: Global___ReserveButtonMode.ValueType = ...,
        reserve_update: _builtins.int = ...,
        desc_update: _builtins.str = ...,
        has_activity: _builtins.bool = ...,
        activity_url: _builtins.str = ...,
        toast: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activity_url", b"activity_url", "btn_mode", b"btn_mode", "desc_update", b"desc_update", "final_btn_status", b"final_btn_status", "has_activity", b"has_activity", "reserve_update", b"reserve_update", "toast", b"toast"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReserveButtonClickResp: _TypeAlias = ReserveButtonClickResp  # noqa: Y015

@_typing.final
class ReserveCalendarInfo(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TITLE_FIELD_NUMBER: _builtins.int
    STARTTS_FIELD_NUMBER: _builtins.int
    ENDTS_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    BUSSINESSID_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    """"""
    startts: _builtins.int
    """"""
    endts: _builtins.int
    """"""
    description: _builtins.str
    """"""
    bussinessid: _builtins.str
    """"""
    def __init__(
        self,
        *,
        title: _builtins.str = ...,
        startts: _builtins.int = ...,
        endts: _builtins.int = ...,
        description: _builtins.str = ...,
        bussinessid: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bussinessid", b"bussinessid", "description", b"description", "endts", b"endts", "startts", b"startts", "title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReserveCalendarInfo: _TypeAlias = ReserveCalendarInfo  # noqa: Y015

@_typing.final
class RmDynReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    DYN_ID_FIELD_NUMBER: _builtins.int
    DYN_ID_STR_FIELD_NUMBER: _builtins.int
    dyn_id: _builtins.int
    """"""
    dyn_id_str: _builtins.str
    """"""
    def __init__(
        self,
        *,
        dyn_id: _builtins.int = ...,
        dyn_id_str: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dyn_id", b"dyn_id", "dyn_id_str", b"dyn_id_str"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RmDynReq: _TypeAlias = RmDynReq  # noqa: Y015

@_typing.final
class RmDynRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RmDynRsp: _TypeAlias = RmDynRsp  # noqa: Y015

@_typing.final
class RmSpaceTopReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    DYN_ID_FIELD_NUMBER: _builtins.int
    TEENAGERS_MODE_FIELD_NUMBER: _builtins.int
    dyn_id: _builtins.int
    """"""
    teenagers_mode: _builtins.int
    """"""
    def __init__(
        self,
        *,
        dyn_id: _builtins.int = ...,
        teenagers_mode: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dyn_id", b"dyn_id", "teenagers_mode", b"teenagers_mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RmSpaceTopReq: _TypeAlias = RmSpaceTopReq  # noqa: Y015

@_typing.final
class RmSpaceTopRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RmSpaceTopRsp: _TypeAlias = RmSpaceTopRsp  # noqa: Y015

@_typing.final
class SearchPoiListReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    LAT_FIELD_NUMBER: _builtins.int
    LNG_FIELD_NUMBER: _builtins.int
    PAGE_FIELD_NUMBER: _builtins.int
    PAGE_SIZE_FIELD_NUMBER: _builtins.int
    KEYWORD_FIELD_NUMBER: _builtins.int
    lat: _builtins.float
    """"""
    lng: _builtins.float
    """"""
    page: _builtins.int
    """"""
    page_size: _builtins.int
    """"""
    keyword: _builtins.str
    """"""
    def __init__(
        self,
        *,
        lat: _builtins.float = ...,
        lng: _builtins.float = ...,
        page: _builtins.int = ...,
        page_size: _builtins.int = ...,
        keyword: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["keyword", b"keyword", "lat", b"lat", "lng", b"lng", "page", b"page", "page_size", b"page_size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SearchPoiListReq: _TypeAlias = SearchPoiListReq  # noqa: Y015

@_typing.final
class SearchPoiListRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    HAS_MORE_FIELD_NUMBER: _builtins.int
    POIS_FIELD_NUMBER: _builtins.int
    has_more: _builtins.bool
    """"""
    @_builtins.property
    def pois(self) -> _containers.RepeatedCompositeFieldContainer[Global___PoiListItem]:
        """"""

    def __init__(
        self,
        *,
        has_more: _builtins.bool = ...,
        pois: _abc.Iterable[Global___PoiListItem] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["has_more", b"has_more", "pois", b"pois"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SearchPoiListRsp: _TypeAlias = SearchPoiListRsp  # noqa: Y015

@_typing.final
class SetSpaceTopReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    DYN_ID_FIELD_NUMBER: _builtins.int
    TEENAGERS_MODE_FIELD_NUMBER: _builtins.int
    dyn_id: _builtins.int
    """"""
    teenagers_mode: _builtins.int
    """"""
    def __init__(
        self,
        *,
        dyn_id: _builtins.int = ...,
        teenagers_mode: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dyn_id", b"dyn_id", "teenagers_mode", b"teenagers_mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetSpaceTopReq: _TypeAlias = SetSpaceTopReq  # noqa: Y015

@_typing.final
class SetSpaceTopRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetSpaceTopRsp: _TypeAlias = SetSpaceTopRsp  # noqa: Y015

@_typing.final
class SubmitCheckReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    CONTENT_FIELD_NUMBER: _builtins.int
    PICS_FIELD_NUMBER: _builtins.int
    ATTACH_CARD_FIELD_NUMBER: _builtins.int
    SCENE_FIELD_NUMBER: _builtins.int
    CREATE_OPTION_FIELD_NUMBER: _builtins.int
    OPUS_FIELD_NUMBER: _builtins.int
    scene: _dynamic_pb2.CreateScene.ValueType
    """"""
    @_builtins.property
    def content(self) -> _dynamic_pb2.CreateContent:
        """"""

    @_builtins.property
    def pics(self) -> _containers.RepeatedCompositeFieldContainer[_dynamic_pb2.CreatePic]:
        """"""

    @_builtins.property
    def attach_card(self) -> _dynamic_pb2.CreateAttachCard:
        """"""

    @_builtins.property
    def create_option(self) -> _dynamic_pb2.CreateOption:
        """"""

    @_builtins.property
    def opus(self) -> _dynamic_pb2.Opus:
        """"""

    def __init__(
        self,
        *,
        content: _dynamic_pb2.CreateContent | None = ...,
        pics: _abc.Iterable[_dynamic_pb2.CreatePic] | None = ...,
        attach_card: _dynamic_pb2.CreateAttachCard | None = ...,
        scene: _dynamic_pb2.CreateScene.ValueType = ...,
        create_option: _dynamic_pb2.CreateOption | None = ...,
        opus: _dynamic_pb2.Opus | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["attach_card", b"attach_card", "content", b"content", "create_option", b"create_option", "opus", b"opus"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attach_card", b"attach_card", "content", b"content", "create_option", b"create_option", "opus", b"opus", "pics", b"pics", "scene", b"scene"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubmitCheckReq: _TypeAlias = SubmitCheckReq  # noqa: Y015

@_typing.final
class SubmitCheckRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubmitCheckRsp: _TypeAlias = SubmitCheckRsp  # noqa: Y015

@_typing.final
class SuggestReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    S_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    s: _builtins.str
    """"""
    type: _builtins.int
    """"""
    def __init__(
        self,
        *,
        s: _builtins.str = ...,
        type: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["s", b"s", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SuggestReq: _TypeAlias = SuggestReq  # noqa: Y015

@_typing.final
class SuggestRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    LIST_FIELD_NUMBER: _builtins.int
    TRACK_ID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    track_id: _builtins.str
    """"""
    version: _builtins.str
    """"""
    @_builtins.property
    def list(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """"""

    def __init__(
        self,
        *,
        list: _abc.Iterable[_builtins.str] | None = ...,
        track_id: _builtins.str = ...,
        version: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["list", b"list", "track_id", b"track_id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SuggestRsp: _TypeAlias = SuggestRsp  # noqa: Y015
