"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DefaultWordsReply(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TRACKID_FIELD_NUMBER: _builtins.int
    PARAM_FIELD_NUMBER: _builtins.int
    SHOW_FIELD_NUMBER: _builtins.int
    WORD_FIELD_NUMBER: _builtins.int
    SHOW_FRONT_FIELD_NUMBER: _builtins.int
    EXP_STR_FIELD_NUMBER: _builtins.int
    GOTO_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    URI_FIELD_NUMBER: _builtins.int
    trackid: _builtins.str
    """"""
    param: _builtins.str
    """"""
    show: _builtins.str
    """"""
    word: _builtins.str
    """"""
    show_front: _builtins.int
    """"""
    exp_str: _builtins.str
    """"""
    goto: _builtins.str
    """"""
    value: _builtins.str
    """"""
    uri: _builtins.str
    """"""
    def __init__(
        self,
        *,
        trackid: _builtins.str = ...,
        param: _builtins.str = ...,
        show: _builtins.str = ...,
        word: _builtins.str = ...,
        show_front: _builtins.int = ...,
        exp_str: _builtins.str = ...,
        goto: _builtins.str = ...,
        value: _builtins.str = ...,
        uri: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["exp_str", b"exp_str", "goto", b"goto", "param", b"param", "show", b"show", "show_front", b"show_front", "trackid", b"trackid", "uri", b"uri", "value", b"value", "word", b"word"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DefaultWordsReply: _TypeAlias = DefaultWordsReply  # noqa: Y015

@_typing.final
class NftFaceIcon(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    REGION_TYPE_FIELD_NUMBER: _builtins.int
    ICON_FIELD_NUMBER: _builtins.int
    SHOW_STATUS_FIELD_NUMBER: _builtins.int
    region_type: _builtins.int
    """"""
    icon: _builtins.str
    """"""
    show_status: _builtins.int
    """"""
    def __init__(
        self,
        *,
        region_type: _builtins.int = ...,
        icon: _builtins.str = ...,
        show_status: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["icon", b"icon", "region_type", b"region_type", "show_status", b"show_status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NftFaceIcon: _TypeAlias = NftFaceIcon  # noqa: Y015

@_typing.final
class DefaultWordsReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    FROM_FIELD_NUMBER: _builtins.int
    LOGIN_EVENT_FIELD_NUMBER: _builtins.int
    TEENAGERS_MODE_FIELD_NUMBER: _builtins.int
    LESSONS_MODE_FIELD_NUMBER: _builtins.int
    TAB_FIELD_NUMBER: _builtins.int
    EVENT_ID_FIELD_NUMBER: _builtins.int
    AVID_FIELD_NUMBER: _builtins.int
    QUERY_FIELD_NUMBER: _builtins.int
    AN_FIELD_NUMBER: _builtins.int
    IS_FRESH_FIELD_NUMBER: _builtins.int
    login_event: _builtins.int
    """"""
    teenagers_mode: _builtins.int
    """"""
    lessons_mode: _builtins.int
    """"""
    tab: _builtins.str
    """"""
    event_id: _builtins.str
    """"""
    avid: _builtins.str
    """"""
    query: _builtins.str
    """"""
    an: _builtins.int
    """"""
    is_fresh: _builtins.int
    """"""
    def __init__(
        self,
        *,
        login_event: _builtins.int = ...,
        teenagers_mode: _builtins.int = ...,
        lessons_mode: _builtins.int = ...,
        tab: _builtins.str = ...,
        event_id: _builtins.str = ...,
        avid: _builtins.str = ...,
        query: _builtins.str = ...,
        an: _builtins.int = ...,
        is_fresh: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["an", b"an", "avid", b"avid", "event_id", b"event_id", "from", b"from", "is_fresh", b"is_fresh", "lessons_mode", b"lessons_mode", "login_event", b"login_event", "query", b"query", "tab", b"tab", "teenagers_mode", b"teenagers_mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DefaultWordsReq: _TypeAlias = DefaultWordsReq  # noqa: Y015

@_typing.final
class SuggestionResult3Reply(_message.Message):
    """获取搜索建议-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    TRACKID_FIELD_NUMBER: _builtins.int
    LIST_FIELD_NUMBER: _builtins.int
    EXP_STR_FIELD_NUMBER: _builtins.int
    trackid: _builtins.str
    """搜索追踪id"""
    exp_str: _builtins.str
    """搜索的abtest 实验信息"""
    @_builtins.property
    def list(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResultItem]:
        """搜索建议条目列表"""

    def __init__(
        self,
        *,
        trackid: _builtins.str = ...,
        list: _abc.Iterable[Global___ResultItem] | None = ...,
        exp_str: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["exp_str", b"exp_str", "list", b"list", "trackid", b"trackid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SuggestionResult3Reply: _TypeAlias = SuggestionResult3Reply  # noqa: Y015

@_typing.final
class SuggestionResult3Req(_message.Message):
    """获取搜索建议-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    KEYWORD_FIELD_NUMBER: _builtins.int
    HIGHLIGHT_FIELD_NUMBER: _builtins.int
    TEENAGERS_MODE_FIELD_NUMBER: _builtins.int
    keyword: _builtins.str
    """关键字"""
    highlight: _builtins.int
    """是否语法高亮
    0:不显示 1:显示
    """
    teenagers_mode: _builtins.int
    """是否青少年模式
    1:开启青少年模式
    """
    def __init__(
        self,
        *,
        keyword: _builtins.str = ...,
        highlight: _builtins.int = ...,
        teenagers_mode: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["highlight", b"highlight", "keyword", b"keyword", "teenagers_mode", b"teenagers_mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SuggestionResult3Req: _TypeAlias = SuggestionResult3Req  # noqa: Y015

@_typing.final
class ResultItem(_message.Message):
    """搜索建议条目"""

    DESCRIPTOR: _descriptor.Descriptor

    FROM_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    KEYWORD_FIELD_NUMBER: _builtins.int
    POSITION_FIELD_NUMBER: _builtins.int
    COVER_FIELD_NUMBER: _builtins.int
    COVER_SIZE_FIELD_NUMBER: _builtins.int
    SUG_TYPE_FIELD_NUMBER: _builtins.int
    TERM_TYPE_FIELD_NUMBER: _builtins.int
    GOTO_FIELD_NUMBER: _builtins.int
    URI_FIELD_NUMBER: _builtins.int
    OFFICIAL_VERIFY_FIELD_NUMBER: _builtins.int
    PARAM_FIELD_NUMBER: _builtins.int
    MID_FIELD_NUMBER: _builtins.int
    FANS_FIELD_NUMBER: _builtins.int
    LEVEL_FIELD_NUMBER: _builtins.int
    ARCHIVES_FIELD_NUMBER: _builtins.int
    PTIME_FIELD_NUMBER: _builtins.int
    SEASON_TYPE_NAME_FIELD_NUMBER: _builtins.int
    AREA_FIELD_NUMBER: _builtins.int
    STYLE_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    RATING_FIELD_NUMBER: _builtins.int
    VOTE_FIELD_NUMBER: _builtins.int
    BADGES_FIELD_NUMBER: _builtins.int
    STYLES_FIELD_NUMBER: _builtins.int
    MODULE_ID_FIELD_NUMBER: _builtins.int
    LIVE_LINK_FIELD_NUMBER: _builtins.int
    FACE_NFT_NEW_FIELD_NUMBER: _builtins.int
    NFT_FACE_ICON_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    """显示结果(语法高亮)"""
    keyword: _builtins.str
    """搜索关键字"""
    position: _builtins.int
    """序号"""
    cover: _builtins.str
    """图片"""
    cover_size: _builtins.float
    """图片尺寸"""
    sug_type: _builtins.str
    """sug词类型"""
    term_type: _builtins.int
    """词条大类型"""
    goto: _builtins.str
    """跳转类型"""
    uri: _builtins.str
    """跳转uri"""
    param: _builtins.str
    """跳转参数"""
    mid: _builtins.int
    """up主mid"""
    fans: _builtins.int
    """粉丝数"""
    level: _builtins.int
    """up主等级"""
    archives: _builtins.int
    """up主稿件数"""
    ptime: _builtins.int
    """投稿时间"""
    season_type_name: _builtins.str
    """season类型名称"""
    area: _builtins.str
    """地区"""
    style: _builtins.str
    """作品风格"""
    label: _builtins.str
    """描述信息"""
    rating: _builtins.float
    """评分"""
    vote: _builtins.int
    """投票数"""
    styles: _builtins.str
    """"""
    module_id: _builtins.int
    """"""
    live_link: _builtins.str
    """"""
    face_nft_new: _builtins.int
    """"""
    @_builtins.property
    def official_verify(self) -> Global___OfficialVerify:
        """认证信息"""

    @_builtins.property
    def badges(self) -> _containers.RepeatedCompositeFieldContainer[Global___ReasonStyle]:
        """角标"""

    @_builtins.property
    def nft_face_icon(self) -> Global___NftFaceIcon:
        """"""

    def __init__(
        self,
        *,
        title: _builtins.str = ...,
        keyword: _builtins.str = ...,
        position: _builtins.int = ...,
        cover: _builtins.str = ...,
        cover_size: _builtins.float = ...,
        sug_type: _builtins.str = ...,
        term_type: _builtins.int = ...,
        goto: _builtins.str = ...,
        uri: _builtins.str = ...,
        official_verify: Global___OfficialVerify | None = ...,
        param: _builtins.str = ...,
        mid: _builtins.int = ...,
        fans: _builtins.int = ...,
        level: _builtins.int = ...,
        archives: _builtins.int = ...,
        ptime: _builtins.int = ...,
        season_type_name: _builtins.str = ...,
        area: _builtins.str = ...,
        style: _builtins.str = ...,
        label: _builtins.str = ...,
        rating: _builtins.float = ...,
        vote: _builtins.int = ...,
        badges: _abc.Iterable[Global___ReasonStyle] | None = ...,
        styles: _builtins.str = ...,
        module_id: _builtins.int = ...,
        live_link: _builtins.str = ...,
        face_nft_new: _builtins.int = ...,
        nft_face_icon: Global___NftFaceIcon | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["nft_face_icon", b"nft_face_icon", "official_verify", b"official_verify"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["archives", b"archives", "area", b"area", "badges", b"badges", "cover", b"cover", "cover_size", b"cover_size", "face_nft_new", b"face_nft_new", "fans", b"fans", "from", b"from", "goto", b"goto", "keyword", b"keyword", "label", b"label", "level", b"level", "live_link", b"live_link", "mid", b"mid", "module_id", b"module_id", "nft_face_icon", b"nft_face_icon", "official_verify", b"official_verify", "param", b"param", "position", b"position", "ptime", b"ptime", "rating", b"rating", "season_type_name", b"season_type_name", "style", b"style", "styles", b"styles", "sug_type", b"sug_type", "term_type", b"term_type", "title", b"title", "uri", b"uri", "vote", b"vote"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResultItem: _TypeAlias = ResultItem  # noqa: Y015

@_typing.final
class OfficialVerify(_message.Message):
    """认证信息"""

    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    DESC_FIELD_NUMBER: _builtins.int
    type: _builtins.int
    """认证类型
    127:未认证 0:个人 1:机构
    """
    desc: _builtins.str
    """认证描述"""
    def __init__(
        self,
        *,
        type: _builtins.int = ...,
        desc: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["desc", b"desc", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___OfficialVerify: _TypeAlias = OfficialVerify  # noqa: Y015

@_typing.final
class ReasonStyle(_message.Message):
    """角标"""

    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    TEXT_COLOR_FIELD_NUMBER: _builtins.int
    TEXT_COLOR_NIGHT_FIELD_NUMBER: _builtins.int
    BG_COLOR_FIELD_NUMBER: _builtins.int
    BG_COLOR_NIGHT_FIELD_NUMBER: _builtins.int
    BORDER_COLOR_FIELD_NUMBER: _builtins.int
    BORDER_COLOR_NIGHT_FIELD_NUMBER: _builtins.int
    BG_STYLE_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    """角标文案"""
    text_color: _builtins.str
    """文案日间色值"""
    text_color_night: _builtins.str
    """文案夜间色值"""
    bg_color: _builtins.str
    """背景日间色值"""
    bg_color_night: _builtins.str
    """背景夜间色值"""
    border_color: _builtins.str
    """边框日间色值"""
    border_color_night: _builtins.str
    """边框夜间色值"""
    bg_style: _builtins.int
    """角标样式
    1:填充模式 2:镂空模式
    """
    def __init__(
        self,
        *,
        text: _builtins.str = ...,
        text_color: _builtins.str = ...,
        text_color_night: _builtins.str = ...,
        bg_color: _builtins.str = ...,
        bg_color_night: _builtins.str = ...,
        border_color: _builtins.str = ...,
        border_color_night: _builtins.str = ...,
        bg_style: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bg_color", b"bg_color", "bg_color_night", b"bg_color_night", "bg_style", b"bg_style", "border_color", b"border_color", "border_color_night", b"border_color_night", "text", b"text", "text_color", b"text_color", "text_color_night", b"text_color_night"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReasonStyle: _TypeAlias = ReasonStyle  # noqa: Y015
