"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from bilibili.app.dynamic.v2 import dynamic_pb2 as _dynamic_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ArcState:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ArcStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ArcState.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    STATE_UNKNOWN: _ArcState.ValueType  # 0
    """"""
    OPEN: _ArcState.ValueType  # 1
    """"""
    ORANGE: _ArcState.ValueType  # 2
    """"""
    WAIT: _ArcState.ValueType  # 3
    """"""
    RECICLE: _ArcState.ValueType  # 4
    """"""
    LOCK: _ArcState.ValueType  # 5
    """"""
    FIXED: _ArcState.ValueType  # 6
    """"""
    USER_DELAY: _ArcState.ValueType  # 7
    """"""
    FAST_PUB: _ArcState.ValueType  # 8
    """"""
    XCODE_FAIL: _ArcState.ValueType  # 9
    """"""

class ArcState(_ArcState, metaclass=_ArcStateEnumTypeWrapper):
    """"""

STATE_UNKNOWN: ArcState.ValueType  # 0
""""""
OPEN: ArcState.ValueType  # 1
""""""
ORANGE: ArcState.ValueType  # 2
""""""
WAIT: ArcState.ValueType  # 3
""""""
RECICLE: ArcState.ValueType  # 4
""""""
LOCK: ArcState.ValueType  # 5
""""""
FIXED: ArcState.ValueType  # 6
""""""
USER_DELAY: ArcState.ValueType  # 7
""""""
FAST_PUB: ArcState.ValueType  # 8
""""""
XCODE_FAIL: ArcState.ValueType  # 9
""""""
Global___ArcState: _TypeAlias = ArcState  # noqa: Y015

class _CardType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CardTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_CardType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CARD_UNKNOWN: _CardType.ValueType  # 0
    """"""
    PUBGUIDE: _CardType.ValueType  # 1
    """"""
    UGC: _CardType.ValueType  # 2
    """"""
    OPUS: _CardType.ValueType  # 3
    """"""
    MORE: _CardType.ValueType  # 4
    """"""

class CardType(_CardType, metaclass=_CardTypeEnumTypeWrapper):
    """"""

CARD_UNKNOWN: CardType.ValueType  # 0
""""""
PUBGUIDE: CardType.ValueType  # 1
""""""
UGC: CardType.ValueType  # 2
""""""
OPUS: CardType.ValueType  # 3
""""""
MORE: CardType.ValueType  # 4
""""""
Global___CardType: _TypeAlias = CardType  # noqa: Y015

class _OpusState:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _OpusStateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_OpusState.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    OPUS_UNKNOWN: _OpusState.ValueType  # 0
    """"""
    OPUS_OPEN: _OpusState.ValueType  # 1
    """"""
    OPUS_NO_FORWARD: _OpusState.ValueType  # 2
    """"""

class OpusState(_OpusState, metaclass=_OpusStateEnumTypeWrapper):
    """"""

OPUS_UNKNOWN: OpusState.ValueType  # 0
""""""
OPUS_OPEN: OpusState.ValueType  # 1
""""""
OPUS_NO_FORWARD: OpusState.ValueType  # 2
""""""
Global___OpusState: _TypeAlias = OpusState  # noqa: Y015

@_typing.final
class Arc(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    DATE_FIELD_NUMBER: _builtins.int
    STAT_FIELD_NUMBER: _builtins.int
    COVER_FIELD_NUMBER: _builtins.int
    DURATION_FIELD_NUMBER: _builtins.int
    AID_FIELD_NUMBER: _builtins.int
    CID_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    date: _builtins.str
    """"""
    cover: _builtins.str
    """"""
    duration: _builtins.int
    """"""
    aid: _builtins.int
    """"""
    cid: _builtins.int
    """"""
    state: _builtins.int
    """"""
    @_builtins.property
    def stat(self) -> Global___Stat:
        """"""

    def __init__(
        self,
        *,
        date: _builtins.str = ...,
        stat: Global___Stat | None = ...,
        cover: _builtins.str = ...,
        duration: _builtins.int = ...,
        aid: _builtins.int = ...,
        cid: _builtins.int = ...,
        state: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stat", b"stat"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aid", b"aid", "cid", b"cid", "cover", b"cover", "date", b"date", "duration", b"duration", "stat", b"stat", "state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Arc: _TypeAlias = Arc  # noqa: Y015

@_typing.final
class Button(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    LIGHT_ICON_FIELD_NUMBER: _builtins.int
    DARK_ICON_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    light_icon: _builtins.str
    """"""
    dark_icon: _builtins.str
    """"""
    url: _builtins.str
    """"""
    text: _builtins.str
    """"""
    def __init__(
        self,
        *,
        light_icon: _builtins.str = ...,
        dark_icon: _builtins.str = ...,
        url: _builtins.str = ...,
        text: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dark_icon", b"dark_icon", "light_icon", b"light_icon", "text", b"text", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Button: _TypeAlias = Button  # noqa: Y015

@_typing.final
class CardMore(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BUTTON_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def button(self) -> Global___Button:
        """"""

    def __init__(
        self,
        *,
        button: Global___Button | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["button", b"button"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["button", b"button"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CardMore: _TypeAlias = CardMore  # noqa: Y015

@_typing.final
class CardOpus(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    WORD_PARAGRAPH_FIELD_NUMBER: _builtins.int
    COVER_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    STAT_TITLE_FIELD_NUMBER: _builtins.int
    STAT_FIELD_NUMBER: _builtins.int
    DATE_FIELD_NUMBER: _builtins.int
    DYN_ID_FIELD_NUMBER: _builtins.int
    HAS_SHARE_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    cover: _builtins.str
    """"""
    url: _builtins.str
    """"""
    date: _builtins.str
    """"""
    dyn_id: _builtins.int
    """"""
    has_share: _builtins.bool
    """"""
    state: _builtins.int
    """"""
    @_builtins.property
    def word_paragraph(self) -> _dynamic_pb2.Paragraph:
        """"""

    @_builtins.property
    def stat_title(self) -> Global___SubTitleWithStat:
        """"""

    @_builtins.property
    def stat(self) -> Global___Stat:
        """"""

    def __init__(
        self,
        *,
        word_paragraph: _dynamic_pb2.Paragraph | None = ...,
        cover: _builtins.str = ...,
        url: _builtins.str = ...,
        stat_title: Global___SubTitleWithStat | None = ...,
        stat: Global___Stat | None = ...,
        date: _builtins.str = ...,
        dyn_id: _builtins.int = ...,
        has_share: _builtins.bool = ...,
        state: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stat", b"stat", "stat_title", b"stat_title", "word_paragraph", b"word_paragraph"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cover", b"cover", "date", b"date", "dyn_id", b"dyn_id", "has_share", b"has_share", "stat", b"stat", "stat_title", b"stat_title", "state", b"state", "url", b"url", "word_paragraph", b"word_paragraph"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CardOpus: _TypeAlias = CardOpus  # noqa: Y015

@_typing.final
class CardPubGuide(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TITLE_FIELD_NUMBER: _builtins.int
    BUTTON_FIELD_NUMBER: _builtins.int
    MATERIAL_FIELD_NUMBER: _builtins.int
    MORE_BUTTON_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def title(self) -> Global___Title:
        """"""

    @_builtins.property
    def button(self) -> Global___Button:
        """"""

    @_builtins.property
    def material(self) -> _containers.RepeatedCompositeFieldContainer[Global___PubGuideMaterial]:
        """"""

    @_builtins.property
    def more_button(self) -> Global___Button:
        """"""

    def __init__(
        self,
        *,
        title: Global___Title | None = ...,
        button: Global___Button | None = ...,
        material: _abc.Iterable[Global___PubGuideMaterial] | None = ...,
        more_button: Global___Button | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["button", b"button", "more_button", b"more_button", "title", b"title"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["button", b"button", "material", b"material", "more_button", b"more_button", "title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CardPubGuide: _TypeAlias = CardPubGuide  # noqa: Y015

@_typing.final
class CardUGC(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TITLE_FIELD_NUMBER: _builtins.int
    TITLE_COLOR_FIELD_NUMBER: _builtins.int
    BUTTON_TITLE_FIELD_NUMBER: _builtins.int
    STAT_TITLE_FIELD_NUMBER: _builtins.int
    ARC_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    HAS_SHARE_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    """"""
    button_title: _builtins.str
    """"""
    stat_title: _builtins.str
    """"""
    url: _builtins.str
    """"""
    has_share: _builtins.bool
    """"""
    @_builtins.property
    def title_color(self) -> Global___Color:
        """"""

    @_builtins.property
    def arc(self) -> Global___Arc:
        """"""

    def __init__(
        self,
        *,
        title: _builtins.str = ...,
        title_color: Global___Color | None = ...,
        button_title: _builtins.str = ...,
        stat_title: _builtins.str = ...,
        arc: Global___Arc | None = ...,
        url: _builtins.str = ...,
        has_share: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["arc", b"arc", "button_title", b"button_title", "stat_title", b"stat_title", "subtitle", b"subtitle", "title_color", b"title_color"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["arc", b"arc", "button_title", b"button_title", "has_share", b"has_share", "stat_title", b"stat_title", "subtitle", b"subtitle", "title", b"title", "title_color", b"title_color", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_subtitle: _TypeAlias = _typing.Literal["button_title", "stat_title"]  # noqa: Y015
    _WhichOneofArgType_subtitle: _TypeAlias = _typing.Literal["subtitle", b"subtitle"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_subtitle) -> _WhichOneofReturnType_subtitle | None: ...

Global___CardUGC: _TypeAlias = CardUGC  # noqa: Y015

@_typing.final
class Color(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    LIGHT_COLOR_FIELD_NUMBER: _builtins.int
    DARK_COLOR_FIELD_NUMBER: _builtins.int
    light_color: _builtins.str
    """"""
    dark_color: _builtins.str
    """"""
    def __init__(
        self,
        *,
        light_color: _builtins.str = ...,
        dark_color: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dark_color", b"dark_color", "light_color", b"light_color"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Color: _TypeAlias = Color  # noqa: Y015

@_typing.final
class PubCard(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    PUB_GUIDE_FIELD_NUMBER: _builtins.int
    UGC_FIELD_NUMBER: _builtins.int
    OPUS_FIELD_NUMBER: _builtins.int
    MORE_FIELD_NUMBER: _builtins.int
    CARD_TYPE_FIELD_NUMBER: _builtins.int
    card_type: Global___CardType.ValueType
    """"""
    @_builtins.property
    def pub_guide(self) -> Global___CardPubGuide:
        """"""

    @_builtins.property
    def ugc(self) -> Global___CardUGC:
        """"""

    @_builtins.property
    def opus(self) -> Global___CardOpus:
        """"""

    @_builtins.property
    def more(self) -> Global___CardMore:
        """"""

    def __init__(
        self,
        *,
        pub_guide: Global___CardPubGuide | None = ...,
        ugc: Global___CardUGC | None = ...,
        opus: Global___CardOpus | None = ...,
        more: Global___CardMore | None = ...,
        card_type: Global___CardType.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["card", b"card", "more", b"more", "opus", b"opus", "pub_guide", b"pub_guide", "ugc", b"ugc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["card", b"card", "card_type", b"card_type", "more", b"more", "opus", b"opus", "pub_guide", b"pub_guide", "ugc", b"ugc"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_card: _TypeAlias = _typing.Literal["pub_guide", "ugc", "opus", "more"]  # noqa: Y015
    _WhichOneofArgType_card: _TypeAlias = _typing.Literal["card", b"card"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_card) -> _WhichOneofReturnType_card | None: ...

Global___PubCard: _TypeAlias = PubCard  # noqa: Y015

@_typing.final
class PubGuideMaterial(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    COVER_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    """"""
    cover: _builtins.str
    """"""
    url: _builtins.str
    """"""
    @_builtins.property
    def title(self) -> Global___Title:
        """"""

    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        title: Global___Title | None = ...,
        cover: _builtins.str = ...,
        url: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["title", b"title"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cover", b"cover", "id", b"id", "title", b"title", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PubGuideMaterial: _TypeAlias = PubGuideMaterial  # noqa: Y015

@_typing.final
class PubModuleReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ORIGINAL_STATE_FIELD_NUMBER: _builtins.int
    DYN_IDS_FIELD_NUMBER: _builtins.int
    CARD_NUM_FIELD_NUMBER: _builtins.int
    user_original_state: _builtins.int
    """"""
    card_num: _builtins.int
    """"""
    @_builtins.property
    def dyn_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """"""

    def __init__(
        self,
        *,
        user_original_state: _builtins.int = ...,
        dyn_ids: _abc.Iterable[_builtins.int] | None = ...,
        card_num: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["card_num", b"card_num", "dyn_ids", b"dyn_ids", "user_original_state", b"user_original_state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PubModuleReq: _TypeAlias = PubModuleReq  # noqa: Y015

@_typing.final
class PubModuleResp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    PUB_CARD_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pub_card(self) -> _containers.RepeatedCompositeFieldContainer[Global___PubCard]:
        """"""

    def __init__(
        self,
        *,
        pub_card: _abc.Iterable[Global___PubCard] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pub_card", b"pub_card"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PubModuleResp: _TypeAlias = PubModuleResp  # noqa: Y015

@_typing.final
class Stat(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    PLAY_ICON_FIELD_NUMBER: _builtins.int
    PLAY_FIELD_NUMBER: _builtins.int
    LIKE_ICON_FIELD_NUMBER: _builtins.int
    LIKE_FIELD_NUMBER: _builtins.int
    play_icon: _builtins.str
    """"""
    play: _builtins.str
    """"""
    like_icon: _builtins.str
    """"""
    like: _builtins.str
    """"""
    def __init__(
        self,
        *,
        play_icon: _builtins.str = ...,
        play: _builtins.str = ...,
        like_icon: _builtins.str = ...,
        like: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["like", b"like", "like_icon", b"like_icon", "play", b"play", "play_icon", b"play_icon"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Stat: _TypeAlias = Stat  # noqa: Y015

@_typing.final
class SubTitleWithButton(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    ICON_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    BACKGROUND_COLOR_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    TEXT_COLOR_FIELD_NUMBER: _builtins.int
    icon: _builtins.str
    """"""
    url: _builtins.str
    """"""
    text: _builtins.str
    """"""
    @_builtins.property
    def background_color(self) -> Global___Color:
        """"""

    @_builtins.property
    def text_color(self) -> Global___Color:
        """"""

    def __init__(
        self,
        *,
        icon: _builtins.str = ...,
        url: _builtins.str = ...,
        background_color: Global___Color | None = ...,
        text: _builtins.str = ...,
        text_color: Global___Color | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["background_color", b"background_color", "text_color", b"text_color"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["background_color", b"background_color", "icon", b"icon", "text", b"text", "text_color", b"text_color", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubTitleWithButton: _TypeAlias = SubTitleWithButton  # noqa: Y015

@_typing.final
class SubTitleWithStat(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    ICON_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    """"""
    @_builtins.property
    def icon(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """"""

    def __init__(
        self,
        *,
        icon: _abc.Iterable[_builtins.str] | None = ...,
        text: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["icon", b"icon", "text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubTitleWithStat: _TypeAlias = SubTitleWithStat  # noqa: Y015

@_typing.final
class Title(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    MAIN_FIELD_NUMBER: _builtins.int
    SUB_FIELD_NUMBER: _builtins.int
    main: _builtins.str
    """"""
    sub: _builtins.str
    """"""
    def __init__(
        self,
        *,
        main: _builtins.str = ...,
        sub: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["main", b"main", "sub", b"sub"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Title: _TypeAlias = Title  # noqa: Y015
