"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class BasicRenderSpec(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    OPACITY_FIELD_NUMBER: _builtins.int
    opacity: _builtins.float
    """"""
    def __init__(
        self,
        *,
        opacity: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["opacity", b"opacity"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BasicRenderSpec: _TypeAlias = BasicRenderSpec  # noqa: Y015

@_typing.final
class ColorConfig(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    IS_DARK_MODE_AWARE_FIELD_NUMBER: _builtins.int
    DAY_FIELD_NUMBER: _builtins.int
    NIGHT_FIELD_NUMBER: _builtins.int
    is_dark_mode_aware: _builtins.bool
    """"""
    @_builtins.property
    def day(self) -> Global___ColorSpec:
        """"""

    @_builtins.property
    def night(self) -> Global___ColorSpec:
        """"""

    def __init__(
        self,
        *,
        is_dark_mode_aware: _builtins.bool = ...,
        day: Global___ColorSpec | None = ...,
        night: Global___ColorSpec | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["day", b"day", "night", b"night"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["day", b"day", "is_dark_mode_aware", b"is_dark_mode_aware", "night", b"night"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ColorConfig: _TypeAlias = ColorConfig  # noqa: Y015

@_typing.final
class ColorSpec(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    ARGB_FIELD_NUMBER: _builtins.int
    argb: _builtins.str
    """"""
    def __init__(
        self,
        *,
        argb: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["argb", b"argb"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ColorSpec: _TypeAlias = ColorSpec  # noqa: Y015

@_typing.final
class LayerGeneralSpec(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    POS_SPEC_FIELD_NUMBER: _builtins.int
    SIZE_SPEC_FIELD_NUMBER: _builtins.int
    RENDER_SPEC_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pos_spec(self) -> Global___PositionSpec:
        """"""

    @_builtins.property
    def size_spec(self) -> Global___SizeSpec:
        """"""

    @_builtins.property
    def render_spec(self) -> Global___BasicRenderSpec:
        """"""

    def __init__(
        self,
        *,
        pos_spec: Global___PositionSpec | None = ...,
        size_spec: Global___SizeSpec | None = ...,
        render_spec: Global___BasicRenderSpec | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pos_spec", b"pos_spec", "render_spec", b"render_spec", "size_spec", b"size_spec"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pos_spec", b"pos_spec", "render_spec", b"render_spec", "size_spec", b"size_spec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LayerGeneralSpec: _TypeAlias = LayerGeneralSpec  # noqa: Y015

@_typing.final
class MaskProperty(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    GENERAL_SPEC_FIELD_NUMBER: _builtins.int
    MASK_SRC_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def general_spec(self) -> Global___LayerGeneralSpec:
        """"""

    @_builtins.property
    def mask_src(self) -> Global___ResourceSource:
        """"""

    def __init__(
        self,
        *,
        general_spec: Global___LayerGeneralSpec | None = ...,
        mask_src: Global___ResourceSource | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["general_spec", b"general_spec", "mask_src", b"mask_src"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["general_spec", b"general_spec", "mask_src", b"mask_src"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MaskProperty: _TypeAlias = MaskProperty  # noqa: Y015

@_typing.final
class NativeDrawRes(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    DRAW_TYPE_FIELD_NUMBER: _builtins.int
    FILL_MODE_FIELD_NUMBER: _builtins.int
    COLOR_CONFIG_FIELD_NUMBER: _builtins.int
    EDGE_WEIGHT_FIELD_NUMBER: _builtins.int
    draw_type: _builtins.int
    """"""
    fill_mode: _builtins.int
    """"""
    edge_weight: _builtins.float
    """"""
    @_builtins.property
    def color_config(self) -> Global___ColorConfig:
        """"""

    def __init__(
        self,
        *,
        draw_type: _builtins.int = ...,
        fill_mode: _builtins.int = ...,
        color_config: Global___ColorConfig | None = ...,
        edge_weight: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["color_config", b"color_config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["color_config", b"color_config", "draw_type", b"draw_type", "edge_weight", b"edge_weight", "fill_mode", b"fill_mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___NativeDrawRes: _TypeAlias = NativeDrawRes  # noqa: Y015

@_typing.final
class PositionSpec(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    COORDINATE_POS_FIELD_NUMBER: _builtins.int
    AXIS_X_FIELD_NUMBER: _builtins.int
    AXIS_Y_FIELD_NUMBER: _builtins.int
    coordinate_pos: _builtins.int
    """"""
    axis_x: _builtins.float
    """"""
    axis_y: _builtins.float
    """"""
    def __init__(
        self,
        *,
        coordinate_pos: _builtins.int = ...,
        axis_x: _builtins.float = ...,
        axis_y: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["axis_x", b"axis_x", "axis_y", b"axis_y", "coordinate_pos", b"coordinate_pos"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PositionSpec: _TypeAlias = PositionSpec  # noqa: Y015

@_typing.final
class RemoteRes(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    URL_FIELD_NUMBER: _builtins.int
    BFS_STYLE_FIELD_NUMBER: _builtins.int
    url: _builtins.str
    """"""
    bfs_style: _builtins.str
    """"""
    def __init__(
        self,
        *,
        url: _builtins.str = ...,
        bfs_style: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bfs_style", b"bfs_style", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoteRes: _TypeAlias = RemoteRes  # noqa: Y015

@_typing.final
class ResourceSource(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    class _LocalRes:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _LocalResEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ResourceSource._LocalRes.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        LOCAL_RES_INVALID: ResourceSource._LocalRes.ValueType  # 0
        LOCAL_RES_ICON_VIP: ResourceSource._LocalRes.ValueType  # 1
        LOCAL_RES_ICON_SMALL_VIP: ResourceSource._LocalRes.ValueType  # 2
        LOCAL_RES_ICON_PERSONAL_VERIFY: ResourceSource._LocalRes.ValueType  # 3
        LOCAL_RES_ICON_ENTERPRISE_VERIFY: ResourceSource._LocalRes.ValueType  # 4
        LOCAL_RES_ICON_NFT_MAINLAND: ResourceSource._LocalRes.ValueType  # 5
        LOCAL_RES_DEFAULT_AVATAR: ResourceSource._LocalRes.ValueType  # 6

    class LocalRes(_LocalRes, metaclass=_LocalResEnumTypeWrapper):
        """"""

    LOCAL_RES_INVALID: ResourceSource.LocalRes.ValueType  # 0
    LOCAL_RES_ICON_VIP: ResourceSource.LocalRes.ValueType  # 1
    LOCAL_RES_ICON_SMALL_VIP: ResourceSource.LocalRes.ValueType  # 2
    LOCAL_RES_ICON_PERSONAL_VERIFY: ResourceSource.LocalRes.ValueType  # 3
    LOCAL_RES_ICON_ENTERPRISE_VERIFY: ResourceSource.LocalRes.ValueType  # 4
    LOCAL_RES_ICON_NFT_MAINLAND: ResourceSource.LocalRes.ValueType  # 5
    LOCAL_RES_DEFAULT_AVATAR: ResourceSource.LocalRes.ValueType  # 6

    SRC_TYPE_FIELD_NUMBER: _builtins.int
    PLACEHOLDER_FIELD_NUMBER: _builtins.int
    REMOTE_FIELD_NUMBER: _builtins.int
    LOCAL_FIELD_NUMBER: _builtins.int
    DRAW_FIELD_NUMBER: _builtins.int
    src_type: _builtins.int
    """"""
    placeholder: _builtins.int
    """"""
    local: Global___ResourceSource.LocalRes.ValueType
    """"""
    @_builtins.property
    def remote(self) -> Global___RemoteRes:
        """"""

    @_builtins.property
    def draw(self) -> Global___NativeDrawRes:
        """"""

    def __init__(
        self,
        *,
        src_type: _builtins.int = ...,
        placeholder: _builtins.int = ...,
        remote: Global___RemoteRes | None = ...,
        local: Global___ResourceSource.LocalRes.ValueType = ...,
        draw: Global___NativeDrawRes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["draw", b"draw", "local", b"local", "remote", b"remote", "res", b"res"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["draw", b"draw", "local", b"local", "placeholder", b"placeholder", "remote", b"remote", "res", b"res", "src_type", b"src_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_res: _TypeAlias = _typing.Literal["remote", "local", "draw"]  # noqa: Y015
    _WhichOneofArgType_res: _TypeAlias = _typing.Literal["res", b"res"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_res) -> _WhichOneofReturnType_res | None: ...

Global___ResourceSource: _TypeAlias = ResourceSource  # noqa: Y015

@_typing.final
class SizeSpec(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    width: _builtins.float
    """"""
    height: _builtins.float
    """"""
    def __init__(
        self,
        *,
        width: _builtins.float = ...,
        height: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SizeSpec: _TypeAlias = SizeSpec  # noqa: Y015
