"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import any_pb2 as _any_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Render(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    TTL_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    code: _builtins.int
    """"""
    message: _builtins.str
    """"""
    ttl: _builtins.str
    """"""
    @_builtins.property
    def data(self) -> _any_pb2.Any:
        """"""

    def __init__(
        self,
        *,
        code: _builtins.int = ...,
        message: _builtins.str = ...,
        ttl: _builtins.str = ...,
        data: _any_pb2.Any | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "data", b"data", "message", b"message", "ttl", b"ttl"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Render: _TypeAlias = Render  # noqa: Y015
