"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from bilibili.dagw.component.avatar.common import common_pb2 as _common_pb2
from bilibili.dagw.component.avatar.v1 import plugin_pb2 as _plugin_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AvatarItem(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    CONTAINER_SIZE_FIELD_NUMBER: _builtins.int
    LAYERS_FIELD_NUMBER: _builtins.int
    FALLBACK_LAYERS_FIELD_NUMBER: _builtins.int
    MID_FIELD_NUMBER: _builtins.int
    mid: _builtins.int
    """"""
    @_builtins.property
    def container_size(self) -> _common_pb2.SizeSpec:
        """"""

    @_builtins.property
    def layers(self) -> _containers.RepeatedCompositeFieldContainer[Global___LayerGroup]:
        """"""

    @_builtins.property
    def fallback_layers(self) -> Global___LayerGroup:
        """"""

    def __init__(
        self,
        *,
        container_size: _common_pb2.SizeSpec | None = ...,
        layers: _abc.Iterable[Global___LayerGroup] | None = ...,
        fallback_layers: Global___LayerGroup | None = ...,
        mid: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["container_size", b"container_size", "fallback_layers", b"fallback_layers"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["container_size", b"container_size", "fallback_layers", b"fallback_layers", "layers", b"layers", "mid", b"mid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AvatarItem: _TypeAlias = AvatarItem  # noqa: Y015

@_typing.final
class BasicLayerResource(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    RES_TYPE_FIELD_NUMBER: _builtins.int
    RES_IMAGE_FIELD_NUMBER: _builtins.int
    RES_ANIMATION_FIELD_NUMBER: _builtins.int
    RES_NATIVE_DRAW_FIELD_NUMBER: _builtins.int
    res_type: _builtins.int
    """"""
    @_builtins.property
    def res_image(self) -> Global___ResImage:
        """"""

    @_builtins.property
    def res_animation(self) -> Global___ResAnimation:
        """"""

    @_builtins.property
    def res_native_draw(self) -> Global___ResNativeDraw:
        """/"""

    def __init__(
        self,
        *,
        res_type: _builtins.int = ...,
        res_image: Global___ResImage | None = ...,
        res_animation: Global___ResAnimation | None = ...,
        res_native_draw: Global___ResNativeDraw | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload", "res_animation", b"res_animation", "res_image", b"res_image", "res_native_draw", b"res_native_draw"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload", "res_animation", b"res_animation", "res_image", b"res_image", "res_native_draw", b"res_native_draw", "res_type", b"res_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["res_image", "res_animation", "res_native_draw"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___BasicLayerResource: _TypeAlias = BasicLayerResource  # noqa: Y015

@_typing.final
class GeneralConfig(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class WebCssStyleEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    WEB_CSS_STYLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def web_css_style(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """"""

    def __init__(
        self,
        *,
        web_css_style: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["web_css_style", b"web_css_style"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GeneralConfig: _TypeAlias = GeneralConfig  # noqa: Y015

@_typing.final
class Layer(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    LAYER_ID_FIELD_NUMBER: _builtins.int
    VISIBLE_FIELD_NUMBER: _builtins.int
    GENERAL_SPEC_FIELD_NUMBER: _builtins.int
    LAYER_CONFIG_FIELD_NUMBER: _builtins.int
    RESOURCE_FIELD_NUMBER: _builtins.int
    layer_id: _builtins.str
    """"""
    visible: _builtins.bool
    """"""
    @_builtins.property
    def general_spec(self) -> _common_pb2.LayerGeneralSpec:
        """"""

    @_builtins.property
    def layer_config(self) -> Global___LayerConfig:
        """"""

    @_builtins.property
    def resource(self) -> Global___BasicLayerResource:
        """"""

    def __init__(
        self,
        *,
        layer_id: _builtins.str = ...,
        visible: _builtins.bool = ...,
        general_spec: _common_pb2.LayerGeneralSpec | None = ...,
        layer_config: Global___LayerConfig | None = ...,
        resource: Global___BasicLayerResource | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["general_spec", b"general_spec", "layer_config", b"layer_config", "resource", b"resource"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["general_spec", b"general_spec", "layer_config", b"layer_config", "layer_id", b"layer_id", "resource", b"resource", "visible", b"visible"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Layer: _TypeAlias = Layer  # noqa: Y015

@_typing.final
class LayerConfig(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___LayerTagConfig: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___LayerTagConfig | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TAGS_FIELD_NUMBER: _builtins.int
    IS_CRITICAL_FIELD_NUMBER: _builtins.int
    ALLOW_OVER_PAINT_FIELD_NUMBER: _builtins.int
    LAYER_MASK_FIELD_NUMBER: _builtins.int
    is_critical: _builtins.bool
    """"""
    allow_over_paint: _builtins.bool
    """"""
    @_builtins.property
    def tags(self) -> _containers.MessageMap[_builtins.str, Global___LayerTagConfig]:
        """"""

    @_builtins.property
    def layer_mask(self) -> _common_pb2.MaskProperty:
        """"""

    def __init__(
        self,
        *,
        tags: _abc.Mapping[_builtins.str, Global___LayerTagConfig] | None = ...,
        is_critical: _builtins.bool = ...,
        allow_over_paint: _builtins.bool = ...,
        layer_mask: _common_pb2.MaskProperty | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["layer_mask", b"layer_mask"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allow_over_paint", b"allow_over_paint", "is_critical", b"is_critical", "layer_mask", b"layer_mask", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LayerConfig: _TypeAlias = LayerConfig  # noqa: Y015

@_typing.final
class LayerGroup(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    GROUP_ID_FIELD_NUMBER: _builtins.int
    LAYERS_FIELD_NUMBER: _builtins.int
    GROUP_MASK_FIELD_NUMBER: _builtins.int
    IS_CRITICAL_GROUP_FIELD_NUMBER: _builtins.int
    group_id: _builtins.str
    """"""
    is_critical_group: _builtins.bool
    """"""
    @_builtins.property
    def layers(self) -> _containers.RepeatedCompositeFieldContainer[Global___Layer]:
        """"""

    @_builtins.property
    def group_mask(self) -> _common_pb2.MaskProperty:
        """"""

    def __init__(
        self,
        *,
        group_id: _builtins.str = ...,
        layers: _abc.Iterable[Global___Layer] | None = ...,
        group_mask: _common_pb2.MaskProperty | None = ...,
        is_critical_group: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["group_mask", b"group_mask"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["group_id", b"group_id", "group_mask", b"group_mask", "is_critical_group", b"is_critical_group", "layers", b"layers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LayerGroup: _TypeAlias = LayerGroup  # noqa: Y015

@_typing.final
class LayerTagConfig(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_TYPE_FIELD_NUMBER: _builtins.int
    GENERAL_CONFIG_FIELD_NUMBER: _builtins.int
    GYRO_CONFIG_FIELD_NUMBER: _builtins.int
    COMMENT_DOUBLECLICK_CONFIG_FIELD_NUMBER: _builtins.int
    LIVE_ANIME_CONFIG_FIELD_NUMBER: _builtins.int
    config_type: _builtins.int
    """"""
    @_builtins.property
    def general_config(self) -> Global___GeneralConfig:
        """"""

    @_builtins.property
    def gyro_config(self) -> _plugin_pb2.GyroConfig:
        """"""

    @_builtins.property
    def comment_doubleClick_config(self) -> _plugin_pb2.CommentDoubleClickConfig:
        """"""

    @_builtins.property
    def live_anime_config(self) -> _plugin_pb2.LiveAnimeConfig:
        """"""

    def __init__(
        self,
        *,
        config_type: _builtins.int = ...,
        general_config: Global___GeneralConfig | None = ...,
        gyro_config: _plugin_pb2.GyroConfig | None = ...,
        comment_doubleClick_config: _plugin_pb2.CommentDoubleClickConfig | None = ...,
        live_anime_config: _plugin_pb2.LiveAnimeConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["comment_doubleClick_config", b"comment_doubleClick_config", "config", b"config", "general_config", b"general_config", "gyro_config", b"gyro_config", "live_anime_config", b"live_anime_config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["comment_doubleClick_config", b"comment_doubleClick_config", "config", b"config", "config_type", b"config_type", "general_config", b"general_config", "gyro_config", b"gyro_config", "live_anime_config", b"live_anime_config"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_config: _TypeAlias = _typing.Literal["general_config", "gyro_config", "comment_doubleClick_config", "live_anime_config"]  # noqa: Y015
    _WhichOneofArgType_config: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_config) -> _WhichOneofReturnType_config | None: ...

Global___LayerTagConfig: _TypeAlias = LayerTagConfig  # noqa: Y015

@_typing.final
class ResAnimation(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    WEBP_SRC_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def webp_src(self) -> _common_pb2.ResourceSource:
        """"""

    def __init__(
        self,
        *,
        webp_src: _common_pb2.ResourceSource | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["webp_src", b"webp_src"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["webp_src", b"webp_src"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResAnimation: _TypeAlias = ResAnimation  # noqa: Y015

@_typing.final
class ResImage(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    IMAGE_SRC_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def image_src(self) -> _common_pb2.ResourceSource:
        """"""

    def __init__(
        self,
        *,
        image_src: _common_pb2.ResourceSource | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["image_src", b"image_src"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["image_src", b"image_src"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResImage: _TypeAlias = ResImage  # noqa: Y015

@_typing.final
class ResNativeDraw(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    DRAW_SRC_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def draw_src(self) -> _common_pb2.ResourceSource:
        """"""

    def __init__(
        self,
        *,
        draw_src: _common_pb2.ResourceSource | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["draw_src", b"draw_src"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["draw_src", b"draw_src"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResNativeDraw: _TypeAlias = ResNativeDraw  # noqa: Y015
