import re

from ...utils.format import replace_placeholder_to_sticker
from ..data import MediaContent

COOLAPK_PATTERN = re.compile(r"\[(?P<name>[^]]+)\]")


MAP = {
    "哈哈哈": "coolapk_emotion_1_hahaha",
    "惊讶": "coolapk_emotion_2_jingya",
    "呲牙": "coolapk_emotion_3_ciya",
    "流泪": "coolapk_emotion_4_liulei",
    "可爱": "coolapk_emotion_5_keai",
    "微笑": "coolapk_emotion_6_weixiao",
    "呵呵": "coolapk_emotion_7_hehe",
    "撇嘴": "coolapk_emotion_8_piezui",
    "色": "coolapk_emotion_9_se",
    "傲慢": "coolapk_emotion_10_aoman",
    "疑问": "coolapk_emotion_11_yiwen",
    "无语": "coolapk_emotion_12_wuyu",
    "坏笑": "coolapk_emotion_13_huaixiao",
    "鄙视": "coolapk_emotion_14_bishi",
    "发怒": "coolapk_emotion_15_fanu",
    "爆怒": "coolapk_emotion_104_baonu",
    "托腮": "coolapk_emotion_16_tuosai",
    "吐舌": "coolapk_emotion_17_tushe",
    "汗": "coolapk_emotion_18_han",
    "抠鼻": "coolapk_emotion_19_koubi",
    "亲亲": "coolapk_emotion_20_qinqin",
    "喷血": "coolapk_emotion_21_penxue",
    "笑眼": "coolapk_emotion_22_xiaoyan",
    "睡": "coolapk_emotion_23_shui",
    "捂嘴笑": "coolapk_emotion_24_wuzuixiao",
    "再见": "coolapk_emotion_25_zaijian",
    "可怜": "coolapk_emotion_26_kelian",
    "笑哭": "coolapk_emotion_31_xiaoku",
    "强": "coolapk_emotion_27_qiang",
    "弱": "coolapk_emotion_28_ruo",
    "抱拳": "coolapk_emotion_29_baoquan",
    "ok": "coolapk_emotion_30_ok",
    "嘿哈": "coolapk_emotion_32_heiha",
    "捂脸": "coolapk_emotion_33_wulian",
    "机智": "coolapk_emotion_34_jizhi",
    "耶": "coolapk_emotion_35_ye",
    "我最美": "coolapk_emotion_38_wozuimei",
    "酷": "coolapk_emotion_36_ku",
    "黑线": "coolapk_emotion_43_heixian",
    "喷": "coolapk_emotion_44_pen",
    "阴险": "coolapk_emotion_45_yinxian",
    "难过": "coolapk_emotion_46_nanguo",
    "委屈": "coolapk_emotion_47_weiqu",
    "吃瓜": "coolapk_emotion_51_chigua",
    "喝酒": "coolapk_emotion_52_hejiu",
    "噗": "coolapk_emotion_53_pu",
    "微微一笑": "coolapk_emotion_48_weiweiyixiao",
    "欢呼": "coolapk_emotion_49_huanhu",
    "白眼": "coolapk_emotion_84_baiyan",
    "耐克嘴": "coolapk_emotion_81_naikezui",
    "t耐克嘴": "coolapk_emotion_105_tnaikezui",
    "害羞": "coolapk_emotion_97_haixiu",
    "无奈": "coolapk_emotion_98_wunai",
    "皱眉": "coolapk_emotion_99_zhoumei",
    "qqdoge": "coolapk_emotion_100_qqdoge",
    "发呆": "coolapk_emotion_102_fadai",
    "舒服": "coolapk_emotion_106_shufu",
    "懒得理": "coolapk_emotion_107_landeli",
    "不开心": "coolapk_emotion_108_bukaixin",
    "挑眉坏笑": "coolapk_emotion_109_tiaomeihuaixiao",
    "害怕": "coolapk_emotion_1010_haipa",
    "哼唧": "coolapk_emotion_1011_hengji",
    "挨打": "coolapk_emotion_1012_aida",
    "假笑": "coolapk_emotion_1014_jiaxiao",
    "偷看": "coolapk_emotion_1015",
    "喝茶": "coolapk_emotion_1016_hecha",
    "哦吼吼": "coolapk_emotion_1017_houhouhou",
    "掩面笑": "coolapk_emotion_1018_yanmianxiao",
    "表面哭泣": "coolapk_emotion_1019_biaomiankuqi",
    "表面开心": "coolapk_emotion_1020_biaomiankaixin",
    "滑稽": "coolapk_emotion_62_huaji",
    "流汗滑稽": "coolapk_emotion_63_liuhanhuaji",
    "受虐滑稽": "coolapk_emotion_64_shounuehuaji",
    "cos滑稽": "coolapk_emotion_65_coshuaji",
    "斗鸡眼滑稽": "coolapk_emotion_66_doujiyanhuaji",
    "墨镜滑稽": "coolapk_emotion_67_mojinghuaji",
    "小嘴滑稽": "coolapk_emotion_1013_xiaozuihuaji",
    "doge": "coolapk_emotion_37_doge",
    "doge笑哭": "coolapk_emotion_56_dogexiaoku",
    "doge呵斥": "coolapk_emotion_57_dogehechi",
    "doge原谅ta": "coolapk_emotion_58_dogeyuanliangta",
    "喵喵": "coolapk_emotion_82_miaomiao",
    "二哈": "coolapk_emotion_59_erha",
    "二哈盯": "coolapk_emotion_95_erhading",
    "爱心": "coolapk_emotion_40_aixin",
    "心碎": "coolapk_emotion_50_xinsui",
    "玫瑰": "coolapk_emotion_41_meigui",
    "凋谢": "coolapk_emotion_42_diaoxie",
    "菜刀": "coolapk_emotion_39_caidao",
    "牛啤": "coolapk_emotion_103_nb",
    "py交易": "coolapk_emotion_101_pyjiaoyi",
    "绿药丸": "coolapk_emotion_55_lvyaowan",
    "红药丸": "coolapk_emotion_54_hongyaowan",
    "酷安": "coolapk_emotion_60_kuan",
    "酷安钓鱼": "coolapk_emotion_1021_kuandiaoyu",
    "绿帽": "coolapk_emotion_61_lvmao",
    "酷安绿帽": "coolapk_emotion_96_kuanlvmao",
    "火把": "coolapk_emotion_83_huoba",
    "酷币": "c_coolb",
    "酷币1分": "c_onef",
    "酷币2分": "c_twof",
    "酷币5分": "c_fivef",
    "酷币1毛": "c_onem",
    "酷币2毛": "c_twom",
    "酷币5毛": "c_fivem",
    "酷币1块": "c_oney",
    "酷币2块": "c_twoy",
    "酷币5块": "c_fivey",
    "酷币10块": "c_teny",
    "酷币20块": "c_ty",
    "酷币50块": "c_fy",
    "酷币100块": "c_oy",
    "酷币1$": "c_oned",
    "酷币2$": "c_twod",
    "酷币5$": "c_fived",
    "酷币1€": "c_oneo",
    "酷币2€": "c_twoo",
    "酷币5€": "c_fiveo",
    "灰色酷币": "coolapk_emotion_68",
    "绿色酷币": "coolapk_emotion_69",
    "白纹酷币": "coolapk_emotion_70",
    "新酷币": "coolapk_emotion_71",
    "新币1分": "coolapk_emotion_72",
    "新酷币2分": "coolapk_emotion_85",
    "新酷币5分": "coolapk_emotion_86",
    "新酷币1毛": "coolapk_emotion_87",
    "新酷币2毛": "coolapk_emotion_88",
    "新酷币5毛": "coolapk_emotion_89",
    "新酷币1块": "coolapk_emotion_90",
    "新酷币2块": "coolapk_emotion_91",
    "新酷币5块": "coolapk_emotion_92",
    "新酷币10块": "coolapk_emotion_93",
    "新酷币20块": "coolapk_emotion_94",
    "新酷币50块": "coolapk_emotion_73",
    "新酷币100块": "coolapk_emotion_74",
    "新酷币1$": "coolapk_emotion_75",
    "新酷币2$": "coolapk_emotion_76",
    "新酷币5$": "coolapk_emotion_77",
    "新酷币1€": "coolapk_emotion_78",
    "新酷币2€": "coolapk_emotion_79",
    "新酷币5€": "coolapk_emotion_80",
}


def name2id(name: str) -> str:
    return MAP.get(name, "")


def format_sticker(text: str) -> list[MediaContent | str]:
    return replace_placeholder_to_sticker(
        text, COOLAPK_PATTERN, "coolapk", id_resolver=name2id
    )
