"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import any_pb2 as _any_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MessagePullsReply(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    PN_FIELD_NUMBER: _builtins.int
    PS_FIELD_NUMBER: _builtins.int
    COUNT_FIELD_NUMBER: _builtins.int
    HAS_NEXT_FIELD_NUMBER: _builtins.int
    pn: _builtins.int
    """"""
    ps: _builtins.int
    """"""
    count: _builtins.int
    """"""
    has_next: _builtins.bool
    """"""
    @_builtins.property
    def data(self) -> _containers.RepeatedCompositeFieldContainer[_any_pb2.Any]:
        """"""

    def __init__(
        self,
        *,
        data: _abc.Iterable[_any_pb2.Any] | None = ...,
        pn: _builtins.int = ...,
        ps: _builtins.int = ...,
        count: _builtins.int = ...,
        has_next: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count", b"count", "data", b"data", "has_next", b"has_next", "pn", b"pn", "ps", b"ps"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MessagePullsReply: _TypeAlias = MessagePullsReply  # noqa: Y015

@_typing.final
class MessagePullsReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    START_SEQ_ID_FIELD_NUMBER: _builtins.int
    END_SEQ_ID_FIELD_NUMBER: _builtins.int
    PN_FIELD_NUMBER: _builtins.int
    PS_FIELD_NUMBER: _builtins.int
    start_seq_id: _builtins.int
    """"""
    end_seq_id: _builtins.int
    """"""
    pn: _builtins.int
    """"""
    ps: _builtins.int
    """"""
    def __init__(
        self,
        *,
        start_seq_id: _builtins.int = ...,
        end_seq_id: _builtins.int = ...,
        pn: _builtins.int = ...,
        ps: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["end_seq_id", b"end_seq_id", "pn", b"pn", "ps", b"ps", "start_seq_id", b"start_seq_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MessagePullsReq: _TypeAlias = MessagePullsReq  # noqa: Y015
