"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _Business:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _BusinessEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Business.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UNKNOWN: _Business.ValueType  # 0
    """未知类型"""
    STORY: _Business.ValueType  # 1
    """story业务"""

class Business(_Business, metaclass=_BusinessEnumTypeWrapper):
    """业务类型"""

UNKNOWN: Business.ValueType  # 0
"""未知类型"""
STORY: Business.ValueType  # 1
"""story业务"""
Global___Business: _TypeAlias = Business  # noqa: Y015

class _CodeType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CodeTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_CodeType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NOCODE: _CodeType.ValueType  # 0
    """默认"""
    CODE264: _CodeType.ValueType  # 1
    """H.264"""
    CODE265: _CodeType.ValueType  # 2
    """H.265"""
    CODEAV1: _CodeType.ValueType  # 3
    """av1"""

class CodeType(_CodeType, metaclass=_CodeTypeEnumTypeWrapper):
    """编码类型"""

NOCODE: CodeType.ValueType  # 0
"""默认"""
CODE264: CodeType.ValueType  # 1
"""H.264"""
CODE265: CodeType.ValueType  # 2
"""H.265"""
CODEAV1: CodeType.ValueType  # 3
"""av1"""
Global___CodeType: _TypeAlias = CodeType  # noqa: Y015

class _ConfType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ConfTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ConfType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NoType: _ConfType.ValueType  # 0
    """"""
    FLIPCONF: _ConfType.ValueType  # 1
    """镜像反转"""
    CASTCONF: _ConfType.ValueType  # 2
    """视频投屏"""
    FEEDBACK: _ConfType.ValueType  # 3
    """反馈"""
    SUBTITLE: _ConfType.ValueType  # 4
    """字幕"""
    PLAYBACKRATE: _ConfType.ValueType  # 5
    """播放速度"""
    TIMEUP: _ConfType.ValueType  # 6
    """定时停止播放"""
    PLAYBACKMODE: _ConfType.ValueType  # 7
    """播放方式"""
    SCALEMODE: _ConfType.ValueType  # 8
    """画面尺寸"""
    BACKGROUNDPLAY: _ConfType.ValueType  # 9
    """后台播放"""
    LIKE: _ConfType.ValueType  # 10
    """顶"""
    DISLIKE: _ConfType.ValueType  # 11
    """踩"""
    COIN: _ConfType.ValueType  # 12
    """投币"""
    ELEC: _ConfType.ValueType  # 13
    """充电"""
    SHARE: _ConfType.ValueType  # 14
    """分享"""
    SCREENSHOT: _ConfType.ValueType  # 15
    """截图"""
    LOCKSCREEN: _ConfType.ValueType  # 16
    """锁屏"""
    RECOMMEND: _ConfType.ValueType  # 17
    """推荐"""
    PLAYBACKSPEED: _ConfType.ValueType  # 18
    """倍速"""
    DEFINITION: _ConfType.ValueType  # 19
    """清晰度"""
    SELECTIONS: _ConfType.ValueType  # 20
    """选集"""
    NEXT: _ConfType.ValueType  # 21
    """下一集"""
    EDITDM: _ConfType.ValueType  # 22
    """编辑弹幕"""
    SMALLWINDOW: _ConfType.ValueType  # 23
    """小窗"""
    SHAKE: _ConfType.ValueType  # 24
    """播放震动"""
    OUTERDM: _ConfType.ValueType  # 25
    """外层面板弹幕设置"""
    INNERDM: _ConfType.ValueType  # 26
    """三点内弹幕设置"""
    PANORAMA: _ConfType.ValueType  # 27
    """全景"""
    DOLBY: _ConfType.ValueType  # 28
    """杜比"""
    COLORFILTER: _ConfType.ValueType  # 29
    """颜色滤镜"""
    LOSSLESS: _ConfType.ValueType  # 30
    """HIRES"""

class ConfType(_ConfType, metaclass=_ConfTypeEnumTypeWrapper):
    """设置类型"""

NoType: ConfType.ValueType  # 0
""""""
FLIPCONF: ConfType.ValueType  # 1
"""镜像反转"""
CASTCONF: ConfType.ValueType  # 2
"""视频投屏"""
FEEDBACK: ConfType.ValueType  # 3
"""反馈"""
SUBTITLE: ConfType.ValueType  # 4
"""字幕"""
PLAYBACKRATE: ConfType.ValueType  # 5
"""播放速度"""
TIMEUP: ConfType.ValueType  # 6
"""定时停止播放"""
PLAYBACKMODE: ConfType.ValueType  # 7
"""播放方式"""
SCALEMODE: ConfType.ValueType  # 8
"""画面尺寸"""
BACKGROUNDPLAY: ConfType.ValueType  # 9
"""后台播放"""
LIKE: ConfType.ValueType  # 10
"""顶"""
DISLIKE: ConfType.ValueType  # 11
"""踩"""
COIN: ConfType.ValueType  # 12
"""投币"""
ELEC: ConfType.ValueType  # 13
"""充电"""
SHARE: ConfType.ValueType  # 14
"""分享"""
SCREENSHOT: ConfType.ValueType  # 15
"""截图"""
LOCKSCREEN: ConfType.ValueType  # 16
"""锁屏"""
RECOMMEND: ConfType.ValueType  # 17
"""推荐"""
PLAYBACKSPEED: ConfType.ValueType  # 18
"""倍速"""
DEFINITION: ConfType.ValueType  # 19
"""清晰度"""
SELECTIONS: ConfType.ValueType  # 20
"""选集"""
NEXT: ConfType.ValueType  # 21
"""下一集"""
EDITDM: ConfType.ValueType  # 22
"""编辑弹幕"""
SMALLWINDOW: ConfType.ValueType  # 23
"""小窗"""
SHAKE: ConfType.ValueType  # 24
"""播放震动"""
OUTERDM: ConfType.ValueType  # 25
"""外层面板弹幕设置"""
INNERDM: ConfType.ValueType  # 26
"""三点内弹幕设置"""
PANORAMA: ConfType.ValueType  # 27
"""全景"""
DOLBY: ConfType.ValueType  # 28
"""杜比"""
COLORFILTER: ConfType.ValueType  # 29
"""颜色滤镜"""
LOSSLESS: ConfType.ValueType  # 30
"""HIRES"""
Global___ConfType: _TypeAlias = ConfType  # noqa: Y015

class _Group:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _GroupEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Group.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UnknownGroup: _Group.ValueType  # 0
    """"""
    A: _Group.ValueType  # 1
    """"""
    B: _Group.ValueType  # 2
    """"""
    C: _Group.ValueType  # 3
    """"""

class Group(_Group, metaclass=_GroupEnumTypeWrapper):
    """"""

UnknownGroup: Group.ValueType  # 0
""""""
A: Group.ValueType  # 1
""""""
B: Group.ValueType  # 2
""""""
C: Group.ValueType  # 3
""""""
Global___Group: _TypeAlias = Group  # noqa: Y015

class _PlayErr:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PlayErrEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PlayErr.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NoErr: _PlayErr.ValueType  # 0
    """"""
    WithMultiDeviceLoginErr: _PlayErr.ValueType  # 1
    """管控类型的错误码"""

class PlayErr(_PlayErr, metaclass=_PlayErrEnumTypeWrapper):
    """错误码"""

NoErr: PlayErr.ValueType  # 0
""""""
WithMultiDeviceLoginErr: PlayErr.ValueType  # 1
"""管控类型的错误码"""
Global___PlayErr: _TypeAlias = PlayErr  # noqa: Y015

class _PlayLimitCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PlayLimitCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PlayLimitCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PLCUnkown: _PlayLimitCode.ValueType  # 0
    """"""
    PLCUgcNotPayed: _PlayLimitCode.ValueType  # 1
    """"""
    PLCChargingPlusNotPass: _PlayLimitCode.ValueType  # 2
    """"""
    PLCChargingPlusUpgrade: _PlayLimitCode.ValueType  # 3
    """"""

class PlayLimitCode(_PlayLimitCode, metaclass=_PlayLimitCodeEnumTypeWrapper):
    """"""

PLCUnkown: PlayLimitCode.ValueType  # 0
""""""
PLCUgcNotPayed: PlayLimitCode.ValueType  # 1
""""""
PLCChargingPlusNotPass: PlayLimitCode.ValueType  # 2
""""""
PLCChargingPlusUpgrade: PlayLimitCode.ValueType  # 3
""""""
Global___PlayLimitCode: _TypeAlias = PlayLimitCode  # noqa: Y015

class _VideoType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _VideoTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_VideoType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    Unknown: _VideoType.ValueType  # 0
    """"""
    FLV: _VideoType.ValueType  # 1
    """flv格式"""
    DASH: _VideoType.ValueType  # 2
    """dash格式"""
    MP4: _VideoType.ValueType  # 3
    """mp4格式"""

class VideoType(_VideoType, metaclass=_VideoTypeEnumTypeWrapper):
    """视频类型"""

Unknown: VideoType.ValueType  # 0
""""""
FLV: VideoType.ValueType  # 1
"""flv格式"""
DASH: VideoType.ValueType  # 2
"""dash格式"""
MP4: VideoType.ValueType  # 3
"""mp4格式"""
Global___VideoType: _TypeAlias = VideoType  # noqa: Y015

@_typing.final
class AB(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    GLANCE_FIELD_NUMBER: _builtins.int
    GROUP_FIELD_NUMBER: _builtins.int
    group: _builtins.int
    """"""
    @_builtins.property
    def glance(self) -> Global___Glance:
        """"""

    def __init__(
        self,
        *,
        glance: Global___Glance | None = ...,
        group: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["glance", b"glance"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["glance", b"glance", "group", b"group"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AB: _TypeAlias = AB  # noqa: Y015

@_typing.final
class ArcConf(_message.Message):
    """配置项"""

    DESCRIPTOR: _descriptor.Descriptor

    IS_SUPPORT_FIELD_NUMBER: _builtins.int
    DISABLED_FIELD_NUMBER: _builtins.int
    EXTRA_CONTENT_FIELD_NUMBER: _builtins.int
    UNSUPPORT_SCENE_FIELD_NUMBER: _builtins.int
    is_support: _builtins.bool
    """是否支持"""
    disabled: _builtins.bool
    """"""
    @_builtins.property
    def extra_content(self) -> Global___ExtraContent:
        """"""

    @_builtins.property
    def unsupport_scene(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """"""

    def __init__(
        self,
        *,
        is_support: _builtins.bool = ...,
        disabled: _builtins.bool = ...,
        extra_content: Global___ExtraContent | None = ...,
        unsupport_scene: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["extra_content", b"extra_content"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["disabled", b"disabled", "extra_content", b"extra_content", "is_support", b"is_support", "unsupport_scene", b"unsupport_scene"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ArcConf: _TypeAlias = ArcConf  # noqa: Y015

@_typing.final
class Chronos(_message.Message):
    """Chronos灰度管理"""

    DESCRIPTOR: _descriptor.Descriptor

    MD5_FIELD_NUMBER: _builtins.int
    FILE_FIELD_NUMBER: _builtins.int
    md5: _builtins.str
    """资源md5"""
    file: _builtins.str
    """资源文件"""
    def __init__(
        self,
        *,
        md5: _builtins.str = ...,
        file: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["file", b"file", "md5", b"md5"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Chronos: _TypeAlias = Chronos  # noqa: Y015

@_typing.final
class ButtonStyle(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    TEXT_COLOR_FIELD_NUMBER: _builtins.int
    BG_COLOR_FIELD_NUMBER: _builtins.int
    JUMP_LINK_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    """"""
    text_color: _builtins.str
    """"""
    bg_color: _builtins.str
    """"""
    jump_link: _builtins.str
    """"""
    def __init__(
        self,
        *,
        text: _builtins.str = ...,
        text_color: _builtins.str = ...,
        bg_color: _builtins.str = ...,
        jump_link: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bg_color", b"bg_color", "jump_link", b"jump_link", "text", b"text", "text_color", b"text_color"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ButtonStyle: _TypeAlias = ButtonStyle  # noqa: Y015

@_typing.final
class CloudConf(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    SHOW_FIELD_NUMBER: _builtins.int
    CONF_TYPE_FIELD_NUMBER: _builtins.int
    FIELD_VALUE_FIELD_NUMBER: _builtins.int
    CONF_VALUE_FIELD_NUMBER: _builtins.int
    show: _builtins.bool
    """是否展示功能"""
    conf_type: Global___ConfType.ValueType
    """设置类型"""
    @_builtins.property
    def field_value(self) -> Global___FieldValue:
        """"""

    @_builtins.property
    def conf_value(self) -> Global___ConfValue:
        """"""

    def __init__(
        self,
        *,
        show: _builtins.bool = ...,
        conf_type: Global___ConfType.ValueType = ...,
        field_value: Global___FieldValue | None = ...,
        conf_value: Global___ConfValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conf_value", b"conf_value", "field_value", b"field_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conf_type", b"conf_type", "conf_value", b"conf_value", "field_value", b"field_value", "show", b"show"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CloudConf: _TypeAlias = CloudConf  # noqa: Y015

@_typing.final
class ConfValue(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    SWITCH_VAL_FIELD_NUMBER: _builtins.int
    SELECTED_VAL_FIELD_NUMBER: _builtins.int
    switch_val: _builtins.bool
    """"""
    selected_val: _builtins.int
    """"""
    def __init__(
        self,
        *,
        switch_val: _builtins.bool = ...,
        selected_val: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["selected_val", b"selected_val", "switch_val", b"switch_val", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["selected_val", b"selected_val", "switch_val", b"switch_val", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["switch_val", "selected_val"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___ConfValue: _TypeAlias = ConfValue  # noqa: Y015

@_typing.final
class DashItem(_message.Message):
    """dash条目"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    BASEURL_FIELD_NUMBER: _builtins.int
    BACKUP_URL_FIELD_NUMBER: _builtins.int
    BANDWIDTH_FIELD_NUMBER: _builtins.int
    CODECID_FIELD_NUMBER: _builtins.int
    MD5_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    FRAME_RATE_FIELD_NUMBER: _builtins.int
    WIDEVINE_PSSH_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    """清晰度"""
    baseUrl: _builtins.str
    """主线流"""
    bandwidth: _builtins.int
    """带宽"""
    codecid: _builtins.int
    """编码id"""
    md5: _builtins.str
    """md5"""
    size: _builtins.int
    """大小"""
    frame_rate: _builtins.str
    """帧率"""
    widevine_pssh: _builtins.str
    """"""
    @_builtins.property
    def backup_url(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """备用流"""

    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        baseUrl: _builtins.str = ...,
        backup_url: _abc.Iterable[_builtins.str] | None = ...,
        bandwidth: _builtins.int = ...,
        codecid: _builtins.int = ...,
        md5: _builtins.str = ...,
        size: _builtins.int = ...,
        frame_rate: _builtins.str = ...,
        widevine_pssh: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["backup_url", b"backup_url", "bandwidth", b"bandwidth", "baseUrl", b"baseUrl", "codecid", b"codecid", "frame_rate", b"frame_rate", "id", b"id", "md5", b"md5", "size", b"size", "widevine_pssh", b"widevine_pssh"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DashItem: _TypeAlias = DashItem  # noqa: Y015

@_typing.final
class DashVideo(_message.Message):
    """dash视频流"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_URL_FIELD_NUMBER: _builtins.int
    BACKUP_URL_FIELD_NUMBER: _builtins.int
    BANDWIDTH_FIELD_NUMBER: _builtins.int
    CODECID_FIELD_NUMBER: _builtins.int
    MD5_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    AUDIOID_FIELD_NUMBER: _builtins.int
    NO_REXCODE_FIELD_NUMBER: _builtins.int
    FRAME_RATE_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    WIDEVINE_PSSH_FIELD_NUMBER: _builtins.int
    base_url: _builtins.str
    """主线流"""
    bandwidth: _builtins.int
    """带宽"""
    codecid: _builtins.int
    """编码id"""
    md5: _builtins.str
    """md5"""
    size: _builtins.int
    """大小"""
    audioId: _builtins.int
    """伴音质量id"""
    no_rexcode: _builtins.bool
    """是否非全二压"""
    frame_rate: _builtins.str
    """码率"""
    width: _builtins.int
    """宽度"""
    height: _builtins.int
    """高度"""
    widevine_pssh: _builtins.str
    """"""
    @_builtins.property
    def backup_url(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """备用流"""

    def __init__(
        self,
        *,
        base_url: _builtins.str = ...,
        backup_url: _abc.Iterable[_builtins.str] | None = ...,
        bandwidth: _builtins.int = ...,
        codecid: _builtins.int = ...,
        md5: _builtins.str = ...,
        size: _builtins.int = ...,
        audioId: _builtins.int = ...,
        no_rexcode: _builtins.bool = ...,
        frame_rate: _builtins.str = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
        widevine_pssh: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audioId", b"audioId", "backup_url", b"backup_url", "bandwidth", b"bandwidth", "base_url", b"base_url", "codecid", b"codecid", "frame_rate", b"frame_rate", "height", b"height", "md5", b"md5", "no_rexcode", b"no_rexcode", "size", b"size", "widevine_pssh", b"widevine_pssh", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DashVideo: _TypeAlias = DashVideo  # noqa: Y015

@_typing.final
class DolbyItem(_message.Message):
    """杜比伴音信息"""

    DESCRIPTOR: _descriptor.Descriptor

    class _Type:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[DolbyItem._Type.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        NONE: DolbyItem._Type.ValueType  # 0
        """NONE"""
        COMMON: DolbyItem._Type.ValueType  # 1
        """普通杜比音效"""
        ATMOS: DolbyItem._Type.ValueType  # 2
        """全景杜比音效"""

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    NONE: DolbyItem.Type.ValueType  # 0
    """NONE"""
    COMMON: DolbyItem.Type.ValueType  # 1
    """普通杜比音效"""
    ATMOS: DolbyItem.Type.ValueType  # 2
    """全景杜比音效"""

    TYPE_FIELD_NUMBER: _builtins.int
    AUDIO_FIELD_NUMBER: _builtins.int
    type: Global___DolbyItem.Type.ValueType
    """杜比类型"""
    @_builtins.property
    def audio(self) -> Global___DashItem:
        """音频流"""

    def __init__(
        self,
        *,
        type: Global___DolbyItem.Type.ValueType = ...,
        audio: Global___DashItem | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audio", b"audio"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio", b"audio", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DolbyItem: _TypeAlias = DolbyItem  # noqa: Y015

@_typing.final
class Event(_message.Message):
    """事件"""

    DESCRIPTOR: _descriptor.Descriptor

    SHAKE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def shake(self) -> Global___Shake:
        """震动"""

    def __init__(
        self,
        *,
        shake: Global___Shake | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["shake", b"shake"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["shake", b"shake"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Event: _TypeAlias = Event  # noqa: Y015

@_typing.final
class ExtraContent(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    DISABLED_REASON_FIELD_NUMBER: _builtins.int
    DISABLED_CODE_FIELD_NUMBER: _builtins.int
    disabled_reason: _builtins.str
    """"""
    disabled_code: _builtins.int
    """"""
    def __init__(
        self,
        *,
        disabled_reason: _builtins.str = ...,
        disabled_code: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["disabled_code", b"disabled_code", "disabled_reason", b"disabled_reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExtraContent: _TypeAlias = ExtraContent  # noqa: Y015

@_typing.final
class FieldValue(_message.Message):
    """配置字段值"""

    DESCRIPTOR: _descriptor.Descriptor

    SWITCH_FIELD_NUMBER: _builtins.int
    switch: _builtins.bool
    """开关"""
    def __init__(
        self,
        *,
        switch: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["switch", b"switch", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["switch", b"switch", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["switch"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___FieldValue: _TypeAlias = FieldValue  # noqa: Y015

@_typing.final
class FormatDescription(_message.Message):
    """清晰度描述"""

    DESCRIPTOR: _descriptor.Descriptor

    QUALITY_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    NEW_DESCRIPTION_FIELD_NUMBER: _builtins.int
    DISPLAY_DESC_FIELD_NUMBER: _builtins.int
    SUPERSCRIPT_FIELD_NUMBER: _builtins.int
    quality: _builtins.int
    """清晰度"""
    format: _builtins.str
    """清晰度格式"""
    description: _builtins.str
    """清晰度描述"""
    new_description: _builtins.str
    """新描述"""
    display_desc: _builtins.str
    """选中态的清晰度描述"""
    superscript: _builtins.str
    """选中态的清晰度描述的角标"""
    def __init__(
        self,
        *,
        quality: _builtins.int = ...,
        format: _builtins.str = ...,
        description: _builtins.str = ...,
        new_description: _builtins.str = ...,
        display_desc: _builtins.str = ...,
        superscript: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "display_desc", b"display_desc", "format", b"format", "new_description", b"new_description", "quality", b"quality", "superscript", b"superscript"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FormatDescription: _TypeAlias = FormatDescription  # noqa: Y015

@_typing.final
class Glance(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    CAN_WATCH_FIELD_NUMBER: _builtins.int
    TIMES_FIELD_NUMBER: _builtins.int
    DURATION_FIELD_NUMBER: _builtins.int
    can_watch: _builtins.bool
    """"""
    times: _builtins.int
    """"""
    duration: _builtins.int
    """"""
    def __init__(
        self,
        *,
        can_watch: _builtins.bool = ...,
        times: _builtins.int = ...,
        duration: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["can_watch", b"can_watch", "duration", b"duration", "times", b"times"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Glance: _TypeAlias = Glance  # noqa: Y015

@_typing.final
class LossLessItem(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    IS_LOSSLESS_AUDIO_FIELD_NUMBER: _builtins.int
    AUDIO_FIELD_NUMBER: _builtins.int
    NEED_VIP_FIELD_NUMBER: _builtins.int
    is_lossless_audio: _builtins.bool
    """"""
    need_vip: _builtins.bool
    """"""
    @_builtins.property
    def audio(self) -> Global___DashItem:
        """"""

    def __init__(
        self,
        *,
        is_lossless_audio: _builtins.bool = ...,
        audio: Global___DashItem | None = ...,
        need_vip: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audio", b"audio"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio", b"audio", "is_lossless_audio", b"is_lossless_audio", "need_vip", b"need_vip"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LossLessItem: _TypeAlias = LossLessItem  # noqa: Y015

@_typing.final
class PlayAbilityConf(_message.Message):
    """禁用功能配置"""

    DESCRIPTOR: _descriptor.Descriptor

    BACKGROUND_PLAY_CONF_FIELD_NUMBER: _builtins.int
    FLIP_CONF_FIELD_NUMBER: _builtins.int
    CAST_CONF_FIELD_NUMBER: _builtins.int
    FEEDBACK_CONF_FIELD_NUMBER: _builtins.int
    SUBTITLE_CONF_FIELD_NUMBER: _builtins.int
    PLAYBACK_RATE_CONF_FIELD_NUMBER: _builtins.int
    TIME_UP_CONF_FIELD_NUMBER: _builtins.int
    PLAYBACK_MODE_CONF_FIELD_NUMBER: _builtins.int
    SCALE_MODE_CONF_FIELD_NUMBER: _builtins.int
    LIKE_CONF_FIELD_NUMBER: _builtins.int
    DISLIKE_CONF_FIELD_NUMBER: _builtins.int
    COIN_CONF_FIELD_NUMBER: _builtins.int
    ELEC_CONF_FIELD_NUMBER: _builtins.int
    SHARE_CONF_FIELD_NUMBER: _builtins.int
    SCREEN_SHOT_CONF_FIELD_NUMBER: _builtins.int
    LOCK_SCREEN_CONF_FIELD_NUMBER: _builtins.int
    RECOMMEND_CONF_FIELD_NUMBER: _builtins.int
    PLAYBACK_SPEED_CONF_FIELD_NUMBER: _builtins.int
    DEFINITION_CONF_FIELD_NUMBER: _builtins.int
    SELECTIONS_CONF_FIELD_NUMBER: _builtins.int
    NEXT_CONF_FIELD_NUMBER: _builtins.int
    EDIT_DM_CONF_FIELD_NUMBER: _builtins.int
    SMALL_WINDOW_CONF_FIELD_NUMBER: _builtins.int
    SHAKE_CONF_FIELD_NUMBER: _builtins.int
    OUTER_DM_CONF_FIELD_NUMBER: _builtins.int
    INNERDMDISABLE_FIELD_NUMBER: _builtins.int
    INNER_DM_CONF_FIELD_NUMBER: _builtins.int
    DOLBY_CONF_FIELD_NUMBER: _builtins.int
    COLOR_FILTER_CONF_FIELD_NUMBER: _builtins.int
    LOSS_LESS_CONF_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def background_play_conf(self) -> Global___CloudConf:
        """后台播放"""

    @_builtins.property
    def flip_conf(self) -> Global___CloudConf:
        """镜像反转"""

    @_builtins.property
    def cast_conf(self) -> Global___CloudConf:
        """投屏"""

    @_builtins.property
    def feedback_conf(self) -> Global___CloudConf:
        """反馈"""

    @_builtins.property
    def subtitle_conf(self) -> Global___CloudConf:
        """字幕"""

    @_builtins.property
    def playback_rate_conf(self) -> Global___CloudConf:
        """播放速度"""

    @_builtins.property
    def time_up_conf(self) -> Global___CloudConf:
        """定时停止"""

    @_builtins.property
    def playback_mode_conf(self) -> Global___CloudConf:
        """播放方式"""

    @_builtins.property
    def scale_mode_conf(self) -> Global___CloudConf:
        """画面尺寸"""

    @_builtins.property
    def like_conf(self) -> Global___CloudConf:
        """赞"""

    @_builtins.property
    def dislike_conf(self) -> Global___CloudConf:
        """踩"""

    @_builtins.property
    def coin_conf(self) -> Global___CloudConf:
        """投币"""

    @_builtins.property
    def elec_conf(self) -> Global___CloudConf:
        """充电"""

    @_builtins.property
    def share_conf(self) -> Global___CloudConf:
        """分享"""

    @_builtins.property
    def screen_shot_conf(self) -> Global___CloudConf:
        """截图"""

    @_builtins.property
    def lock_screen_conf(self) -> Global___CloudConf:
        """锁定"""

    @_builtins.property
    def recommend_conf(self) -> Global___CloudConf:
        """相关推荐"""

    @_builtins.property
    def playback_speed_conf(self) -> Global___CloudConf:
        """播放速度"""

    @_builtins.property
    def definition_conf(self) -> Global___CloudConf:
        """清晰度"""

    @_builtins.property
    def selections_conf(self) -> Global___CloudConf:
        """选集"""

    @_builtins.property
    def next_conf(self) -> Global___CloudConf:
        """下一集"""

    @_builtins.property
    def edit_dm_conf(self) -> Global___CloudConf:
        """编辑弹幕"""

    @_builtins.property
    def small_window_conf(self) -> Global___CloudConf:
        """小窗"""

    @_builtins.property
    def shake_conf(self) -> Global___CloudConf:
        """震动"""

    @_builtins.property
    def outer_dm_conf(self) -> Global___CloudConf:
        """外层面板弹幕设置"""

    @_builtins.property
    def innerDmDisable(self) -> Global___CloudConf:
        """三点内弹幕设置"""

    @_builtins.property
    def inner_dm_conf(self) -> Global___CloudConf:
        """一起看入口"""

    @_builtins.property
    def dolby_conf(self) -> Global___CloudConf:
        """杜比音效"""

    @_builtins.property
    def color_filter_conf(self) -> Global___CloudConf:
        """颜色滤镜"""

    @_builtins.property
    def loss_less_conf(self) -> Global___CloudConf:
        """HIRES"""

    def __init__(
        self,
        *,
        background_play_conf: Global___CloudConf | None = ...,
        flip_conf: Global___CloudConf | None = ...,
        cast_conf: Global___CloudConf | None = ...,
        feedback_conf: Global___CloudConf | None = ...,
        subtitle_conf: Global___CloudConf | None = ...,
        playback_rate_conf: Global___CloudConf | None = ...,
        time_up_conf: Global___CloudConf | None = ...,
        playback_mode_conf: Global___CloudConf | None = ...,
        scale_mode_conf: Global___CloudConf | None = ...,
        like_conf: Global___CloudConf | None = ...,
        dislike_conf: Global___CloudConf | None = ...,
        coin_conf: Global___CloudConf | None = ...,
        elec_conf: Global___CloudConf | None = ...,
        share_conf: Global___CloudConf | None = ...,
        screen_shot_conf: Global___CloudConf | None = ...,
        lock_screen_conf: Global___CloudConf | None = ...,
        recommend_conf: Global___CloudConf | None = ...,
        playback_speed_conf: Global___CloudConf | None = ...,
        definition_conf: Global___CloudConf | None = ...,
        selections_conf: Global___CloudConf | None = ...,
        next_conf: Global___CloudConf | None = ...,
        edit_dm_conf: Global___CloudConf | None = ...,
        small_window_conf: Global___CloudConf | None = ...,
        shake_conf: Global___CloudConf | None = ...,
        outer_dm_conf: Global___CloudConf | None = ...,
        innerDmDisable: Global___CloudConf | None = ...,
        inner_dm_conf: Global___CloudConf | None = ...,
        dolby_conf: Global___CloudConf | None = ...,
        color_filter_conf: Global___CloudConf | None = ...,
        loss_less_conf: Global___CloudConf | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["background_play_conf", b"background_play_conf", "cast_conf", b"cast_conf", "coin_conf", b"coin_conf", "color_filter_conf", b"color_filter_conf", "definition_conf", b"definition_conf", "dislike_conf", b"dislike_conf", "dolby_conf", b"dolby_conf", "edit_dm_conf", b"edit_dm_conf", "elec_conf", b"elec_conf", "feedback_conf", b"feedback_conf", "flip_conf", b"flip_conf", "innerDmDisable", b"innerDmDisable", "inner_dm_conf", b"inner_dm_conf", "like_conf", b"like_conf", "lock_screen_conf", b"lock_screen_conf", "loss_less_conf", b"loss_less_conf", "next_conf", b"next_conf", "outer_dm_conf", b"outer_dm_conf", "playback_mode_conf", b"playback_mode_conf", "playback_rate_conf", b"playback_rate_conf", "playback_speed_conf", b"playback_speed_conf", "recommend_conf", b"recommend_conf", "scale_mode_conf", b"scale_mode_conf", "screen_shot_conf", b"screen_shot_conf", "selections_conf", b"selections_conf", "shake_conf", b"shake_conf", "share_conf", b"share_conf", "small_window_conf", b"small_window_conf", "subtitle_conf", b"subtitle_conf", "time_up_conf", b"time_up_conf"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["background_play_conf", b"background_play_conf", "cast_conf", b"cast_conf", "coin_conf", b"coin_conf", "color_filter_conf", b"color_filter_conf", "definition_conf", b"definition_conf", "dislike_conf", b"dislike_conf", "dolby_conf", b"dolby_conf", "edit_dm_conf", b"edit_dm_conf", "elec_conf", b"elec_conf", "feedback_conf", b"feedback_conf", "flip_conf", b"flip_conf", "innerDmDisable", b"innerDmDisable", "inner_dm_conf", b"inner_dm_conf", "like_conf", b"like_conf", "lock_screen_conf", b"lock_screen_conf", "loss_less_conf", b"loss_less_conf", "next_conf", b"next_conf", "outer_dm_conf", b"outer_dm_conf", "playback_mode_conf", b"playback_mode_conf", "playback_rate_conf", b"playback_rate_conf", "playback_speed_conf", b"playback_speed_conf", "recommend_conf", b"recommend_conf", "scale_mode_conf", b"scale_mode_conf", "screen_shot_conf", b"screen_shot_conf", "selections_conf", b"selections_conf", "shake_conf", b"shake_conf", "share_conf", b"share_conf", "small_window_conf", b"small_window_conf", "subtitle_conf", b"subtitle_conf", "time_up_conf", b"time_up_conf"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlayAbilityConf: _TypeAlias = PlayAbilityConf  # noqa: Y015

@_typing.final
class PlayArcConf(_message.Message):
    """播放控件稿件配置"""

    DESCRIPTOR: _descriptor.Descriptor

    BACKGROUND_PLAY_CONF_FIELD_NUMBER: _builtins.int
    FLIP_CONF_FIELD_NUMBER: _builtins.int
    CAST_CONF_FIELD_NUMBER: _builtins.int
    FEEDBACK_CONF_FIELD_NUMBER: _builtins.int
    SUBTITLE_CONF_FIELD_NUMBER: _builtins.int
    PLAYBACK_RATE_CONF_FIELD_NUMBER: _builtins.int
    TIME_UP_CONF_FIELD_NUMBER: _builtins.int
    PLAYBACK_MODE_CONF_FIELD_NUMBER: _builtins.int
    SCALE_MODE_CONF_FIELD_NUMBER: _builtins.int
    LIKE_CONF_FIELD_NUMBER: _builtins.int
    DISLIKE_CONF_FIELD_NUMBER: _builtins.int
    COIN_CONF_FIELD_NUMBER: _builtins.int
    ELEC_CONF_FIELD_NUMBER: _builtins.int
    SHARE_CONF_FIELD_NUMBER: _builtins.int
    SCREEN_SHOT_CONF_FIELD_NUMBER: _builtins.int
    LOCK_SCREEN_CONF_FIELD_NUMBER: _builtins.int
    RECOMMEND_CONF_FIELD_NUMBER: _builtins.int
    PLAYBACK_SPEED_CONF_FIELD_NUMBER: _builtins.int
    DEFINITION_CONF_FIELD_NUMBER: _builtins.int
    SELECTIONS_CONF_FIELD_NUMBER: _builtins.int
    NEXT_CONF_FIELD_NUMBER: _builtins.int
    EDIT_DM_CONF_FIELD_NUMBER: _builtins.int
    SMALL_WINDOW_CONF_FIELD_NUMBER: _builtins.int
    SHAKE_CONF_FIELD_NUMBER: _builtins.int
    OUTER_DM_CONF_FIELD_NUMBER: _builtins.int
    INNER_DM_CONF_FIELD_NUMBER: _builtins.int
    PANORAMA_CONF_FIELD_NUMBER: _builtins.int
    DOLBY_CONF_FIELD_NUMBER: _builtins.int
    SCREEN_RECORDING_CONF_FIELD_NUMBER: _builtins.int
    COLOR_FILTER_CONF_FIELD_NUMBER: _builtins.int
    LOSS_LESS_CONF_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def background_play_conf(self) -> Global___ArcConf:
        """后台播放"""

    @_builtins.property
    def flip_conf(self) -> Global___ArcConf:
        """镜像反转"""

    @_builtins.property
    def cast_conf(self) -> Global___ArcConf:
        """投屏"""

    @_builtins.property
    def feedback_conf(self) -> Global___ArcConf:
        """反馈"""

    @_builtins.property
    def subtitle_conf(self) -> Global___ArcConf:
        """字幕"""

    @_builtins.property
    def playback_rate_conf(self) -> Global___ArcConf:
        """播放速度"""

    @_builtins.property
    def time_up_conf(self) -> Global___ArcConf:
        """定时停止"""

    @_builtins.property
    def playback_mode_conf(self) -> Global___ArcConf:
        """播放方式"""

    @_builtins.property
    def scale_mode_conf(self) -> Global___ArcConf:
        """画面尺寸"""

    @_builtins.property
    def like_conf(self) -> Global___ArcConf:
        """赞"""

    @_builtins.property
    def dislike_conf(self) -> Global___ArcConf:
        """踩"""

    @_builtins.property
    def coin_conf(self) -> Global___ArcConf:
        """投币"""

    @_builtins.property
    def elec_conf(self) -> Global___ArcConf:
        """充电"""

    @_builtins.property
    def share_conf(self) -> Global___ArcConf:
        """分享"""

    @_builtins.property
    def screen_shot_conf(self) -> Global___ArcConf:
        """截图"""

    @_builtins.property
    def lock_screen_conf(self) -> Global___ArcConf:
        """锁定"""

    @_builtins.property
    def recommend_conf(self) -> Global___ArcConf:
        """相关推荐"""

    @_builtins.property
    def playback_speed_conf(self) -> Global___ArcConf:
        """播放速度"""

    @_builtins.property
    def definition_conf(self) -> Global___ArcConf:
        """清晰度"""

    @_builtins.property
    def selections_conf(self) -> Global___ArcConf:
        """选集"""

    @_builtins.property
    def next_conf(self) -> Global___ArcConf:
        """下一集"""

    @_builtins.property
    def edit_dm_conf(self) -> Global___ArcConf:
        """编辑弹幕"""

    @_builtins.property
    def small_window_conf(self) -> Global___ArcConf:
        """小窗"""

    @_builtins.property
    def shake_conf(self) -> Global___ArcConf:
        """震动"""

    @_builtins.property
    def outer_dm_conf(self) -> Global___ArcConf:
        """外层面板弹幕设置"""

    @_builtins.property
    def inner_dm_conf(self) -> Global___ArcConf:
        """三点内弹幕设置"""

    @_builtins.property
    def panorama_conf(self) -> Global___ArcConf:
        """一起看入口"""

    @_builtins.property
    def dolby_conf(self) -> Global___ArcConf:
        """杜比音效"""

    @_builtins.property
    def screen_recording_conf(self) -> Global___ArcConf:
        """屏幕录制"""

    @_builtins.property
    def color_filter_conf(self) -> Global___ArcConf:
        """颜色滤镜"""

    @_builtins.property
    def loss_less_conf(self) -> Global___ArcConf:
        """HIRES"""

    def __init__(
        self,
        *,
        background_play_conf: Global___ArcConf | None = ...,
        flip_conf: Global___ArcConf | None = ...,
        cast_conf: Global___ArcConf | None = ...,
        feedback_conf: Global___ArcConf | None = ...,
        subtitle_conf: Global___ArcConf | None = ...,
        playback_rate_conf: Global___ArcConf | None = ...,
        time_up_conf: Global___ArcConf | None = ...,
        playback_mode_conf: Global___ArcConf | None = ...,
        scale_mode_conf: Global___ArcConf | None = ...,
        like_conf: Global___ArcConf | None = ...,
        dislike_conf: Global___ArcConf | None = ...,
        coin_conf: Global___ArcConf | None = ...,
        elec_conf: Global___ArcConf | None = ...,
        share_conf: Global___ArcConf | None = ...,
        screen_shot_conf: Global___ArcConf | None = ...,
        lock_screen_conf: Global___ArcConf | None = ...,
        recommend_conf: Global___ArcConf | None = ...,
        playback_speed_conf: Global___ArcConf | None = ...,
        definition_conf: Global___ArcConf | None = ...,
        selections_conf: Global___ArcConf | None = ...,
        next_conf: Global___ArcConf | None = ...,
        edit_dm_conf: Global___ArcConf | None = ...,
        small_window_conf: Global___ArcConf | None = ...,
        shake_conf: Global___ArcConf | None = ...,
        outer_dm_conf: Global___ArcConf | None = ...,
        inner_dm_conf: Global___ArcConf | None = ...,
        panorama_conf: Global___ArcConf | None = ...,
        dolby_conf: Global___ArcConf | None = ...,
        screen_recording_conf: Global___ArcConf | None = ...,
        color_filter_conf: Global___ArcConf | None = ...,
        loss_less_conf: Global___ArcConf | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["background_play_conf", b"background_play_conf", "cast_conf", b"cast_conf", "coin_conf", b"coin_conf", "color_filter_conf", b"color_filter_conf", "definition_conf", b"definition_conf", "dislike_conf", b"dislike_conf", "dolby_conf", b"dolby_conf", "edit_dm_conf", b"edit_dm_conf", "elec_conf", b"elec_conf", "feedback_conf", b"feedback_conf", "flip_conf", b"flip_conf", "inner_dm_conf", b"inner_dm_conf", "like_conf", b"like_conf", "lock_screen_conf", b"lock_screen_conf", "loss_less_conf", b"loss_less_conf", "next_conf", b"next_conf", "outer_dm_conf", b"outer_dm_conf", "panorama_conf", b"panorama_conf", "playback_mode_conf", b"playback_mode_conf", "playback_rate_conf", b"playback_rate_conf", "playback_speed_conf", b"playback_speed_conf", "recommend_conf", b"recommend_conf", "scale_mode_conf", b"scale_mode_conf", "screen_recording_conf", b"screen_recording_conf", "screen_shot_conf", b"screen_shot_conf", "selections_conf", b"selections_conf", "shake_conf", b"shake_conf", "share_conf", b"share_conf", "small_window_conf", b"small_window_conf", "subtitle_conf", b"subtitle_conf", "time_up_conf", b"time_up_conf"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["background_play_conf", b"background_play_conf", "cast_conf", b"cast_conf", "coin_conf", b"coin_conf", "color_filter_conf", b"color_filter_conf", "definition_conf", b"definition_conf", "dislike_conf", b"dislike_conf", "dolby_conf", b"dolby_conf", "edit_dm_conf", b"edit_dm_conf", "elec_conf", b"elec_conf", "feedback_conf", b"feedback_conf", "flip_conf", b"flip_conf", "inner_dm_conf", b"inner_dm_conf", "like_conf", b"like_conf", "lock_screen_conf", b"lock_screen_conf", "loss_less_conf", b"loss_less_conf", "next_conf", b"next_conf", "outer_dm_conf", b"outer_dm_conf", "panorama_conf", b"panorama_conf", "playback_mode_conf", b"playback_mode_conf", "playback_rate_conf", b"playback_rate_conf", "playback_speed_conf", b"playback_speed_conf", "recommend_conf", b"recommend_conf", "scale_mode_conf", b"scale_mode_conf", "screen_recording_conf", b"screen_recording_conf", "screen_shot_conf", b"screen_shot_conf", "selections_conf", b"selections_conf", "shake_conf", b"shake_conf", "share_conf", b"share_conf", "small_window_conf", b"small_window_conf", "subtitle_conf", b"subtitle_conf", "time_up_conf", b"time_up_conf"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlayArcConf: _TypeAlias = PlayArcConf  # noqa: Y015

@_typing.final
class PlayConfEditReply(_message.Message):
    """编辑播放界面配置-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlayConfEditReply: _TypeAlias = PlayConfEditReply  # noqa: Y015

@_typing.final
class PlayConfEditReq(_message.Message):
    """编辑播放界面配置-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    PLAY_CONF_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def play_conf(self) -> _containers.RepeatedCompositeFieldContainer[Global___PlayConfState]:
        """播放界面配置"""

    def __init__(
        self,
        *,
        play_conf: _abc.Iterable[Global___PlayConfState] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["play_conf", b"play_conf"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlayConfEditReq: _TypeAlias = PlayConfEditReq  # noqa: Y015

@_typing.final
class PlayConfReply(_message.Message):
    """获取播放界面配置-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    PLAY_CONF_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def play_conf(self) -> Global___PlayAbilityConf:
        """播放控件用户自定义配置"""

    def __init__(
        self,
        *,
        play_conf: Global___PlayAbilityConf | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["play_conf", b"play_conf"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["play_conf", b"play_conf"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlayConfReply: _TypeAlias = PlayConfReply  # noqa: Y015

@_typing.final
class PlayConfReq(_message.Message):
    """获取播放界面配置-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlayConfReq: _TypeAlias = PlayConfReq  # noqa: Y015

@_typing.final
class PlayConfState(_message.Message):
    """播放界面配置"""

    DESCRIPTOR: _descriptor.Descriptor

    CONF_TYPE_FIELD_NUMBER: _builtins.int
    SHOW_FIELD_NUMBER: _builtins.int
    FIELD_VALUE_FIELD_NUMBER: _builtins.int
    CONF_VALUE_FIELD_NUMBER: _builtins.int
    conf_type: Global___ConfType.ValueType
    """设置类型"""
    show: _builtins.bool
    """是否隐藏"""
    @_builtins.property
    def field_value(self) -> Global___FieldValue:
        """配置字段值"""

    @_builtins.property
    def conf_value(self) -> Global___ConfValue:
        """"""

    def __init__(
        self,
        *,
        conf_type: Global___ConfType.ValueType = ...,
        show: _builtins.bool = ...,
        field_value: Global___FieldValue | None = ...,
        conf_value: Global___ConfValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conf_value", b"conf_value", "field_value", b"field_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conf_type", b"conf_type", "conf_value", b"conf_value", "field_value", b"field_value", "show", b"show"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlayConfState: _TypeAlias = PlayConfState  # noqa: Y015

@_typing.final
class PlayLimit(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    SUB_MESSAGE_FIELD_NUMBER: _builtins.int
    BUTTON_FIELD_NUMBER: _builtins.int
    code: Global___PlayLimitCode.ValueType
    """"""
    message: _builtins.str
    """"""
    sub_message: _builtins.str
    """"""
    @_builtins.property
    def button(self) -> Global___ButtonStyle:
        """"""

    def __init__(
        self,
        *,
        code: Global___PlayLimitCode.ValueType = ...,
        message: _builtins.str = ...,
        sub_message: _builtins.str = ...,
        button: Global___ButtonStyle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["button", b"button"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["button", b"button", "code", b"code", "message", b"message", "sub_message", b"sub_message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlayLimit: _TypeAlias = PlayLimit  # noqa: Y015

@_typing.final
class PlayURLReply(_message.Message):
    """视频地址-回复"""

    DESCRIPTOR: _descriptor.Descriptor

    QUALITY_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    TIMELENGTH_FIELD_NUMBER: _builtins.int
    VIDEO_CODECID_FIELD_NUMBER: _builtins.int
    FNVER_FIELD_NUMBER: _builtins.int
    FNVAL_FIELD_NUMBER: _builtins.int
    VIDEO_PROJECT_FIELD_NUMBER: _builtins.int
    DURL_FIELD_NUMBER: _builtins.int
    DASH_FIELD_NUMBER: _builtins.int
    NO_REXCODE_FIELD_NUMBER: _builtins.int
    UPGRADE_LIMIT_FIELD_NUMBER: _builtins.int
    SUPPORT_FORMATS_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    quality: _builtins.int
    """清晰的"""
    format: _builtins.str
    """格式"""
    timelength: _builtins.int
    """总时长(单位为ms)"""
    video_codecid: _builtins.int
    """编码id"""
    fnver: _builtins.int
    """视频流版本"""
    fnval: _builtins.int
    """视频流格式"""
    video_project: _builtins.bool
    """是否支持投影"""
    no_rexcode: _builtins.int
    """是否非全二压"""
    type: Global___VideoType.ValueType
    """视频格式"""
    @_builtins.property
    def durl(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResponseUrl]:
        """分段视频流列表"""

    @_builtins.property
    def dash(self) -> Global___ResponseDash:
        """dash数据"""

    @_builtins.property
    def upgrade_limit(self) -> Global___UpgradeLimit:
        """互动视频升级提示"""

    @_builtins.property
    def support_formats(self) -> _containers.RepeatedCompositeFieldContainer[Global___FormatDescription]:
        """清晰度描述列表"""

    def __init__(
        self,
        *,
        quality: _builtins.int = ...,
        format: _builtins.str = ...,
        timelength: _builtins.int = ...,
        video_codecid: _builtins.int = ...,
        fnver: _builtins.int = ...,
        fnval: _builtins.int = ...,
        video_project: _builtins.bool = ...,
        durl: _abc.Iterable[Global___ResponseUrl] | None = ...,
        dash: Global___ResponseDash | None = ...,
        no_rexcode: _builtins.int = ...,
        upgrade_limit: Global___UpgradeLimit | None = ...,
        support_formats: _abc.Iterable[Global___FormatDescription] | None = ...,
        type: Global___VideoType.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["dash", b"dash", "upgrade_limit", b"upgrade_limit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dash", b"dash", "durl", b"durl", "fnval", b"fnval", "fnver", b"fnver", "format", b"format", "no_rexcode", b"no_rexcode", "quality", b"quality", "support_formats", b"support_formats", "timelength", b"timelength", "type", b"type", "upgrade_limit", b"upgrade_limit", "video_codecid", b"video_codecid", "video_project", b"video_project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlayURLReply: _TypeAlias = PlayURLReply  # noqa: Y015

@_typing.final
class PlayURLReq(_message.Message):
    """视频地址-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    AID_FIELD_NUMBER: _builtins.int
    CID_FIELD_NUMBER: _builtins.int
    QN_FIELD_NUMBER: _builtins.int
    FNVER_FIELD_NUMBER: _builtins.int
    FNVAL_FIELD_NUMBER: _builtins.int
    DOWNLOAD_FIELD_NUMBER: _builtins.int
    FORCE_HOST_FIELD_NUMBER: _builtins.int
    FOURK_FIELD_NUMBER: _builtins.int
    SPMID_FIELD_NUMBER: _builtins.int
    FROM_SPMID_FIELD_NUMBER: _builtins.int
    aid: _builtins.int
    """稿件avid"""
    cid: _builtins.int
    """视频cid"""
    qn: _builtins.int
    """清晰度"""
    fnver: _builtins.int
    """视频流版本"""
    fnval: _builtins.int
    """视频流格式"""
    download: _builtins.int
    """下载模式
    0:播放 1:flv下载 2:dash下载
    """
    force_host: _builtins.int
    """流url强制是用域名
    0:允许使用ip 1:使用http 2:使用https
    """
    fourk: _builtins.bool
    """是否4K"""
    spmid: _builtins.str
    """当前页spm"""
    from_spmid: _builtins.str
    """上一页spm"""
    def __init__(
        self,
        *,
        aid: _builtins.int = ...,
        cid: _builtins.int = ...,
        qn: _builtins.int = ...,
        fnver: _builtins.int = ...,
        fnval: _builtins.int = ...,
        download: _builtins.int = ...,
        force_host: _builtins.int = ...,
        fourk: _builtins.bool = ...,
        spmid: _builtins.str = ...,
        from_spmid: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aid", b"aid", "cid", b"cid", "download", b"download", "fnval", b"fnval", "fnver", b"fnver", "force_host", b"force_host", "fourk", b"fourk", "from_spmid", b"from_spmid", "qn", b"qn", "spmid", b"spmid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlayURLReq: _TypeAlias = PlayURLReq  # noqa: Y015

@_typing.final
class PlayViewReply(_message.Message):
    """播放页信息-回复"""

    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_INFO_FIELD_NUMBER: _builtins.int
    PLAY_CONF_FIELD_NUMBER: _builtins.int
    UPGRADE_LIMIT_FIELD_NUMBER: _builtins.int
    CHRONOS_FIELD_NUMBER: _builtins.int
    PLAY_ARC_FIELD_NUMBER: _builtins.int
    EVENT_FIELD_NUMBER: _builtins.int
    AB_FIELD_NUMBER: _builtins.int
    PLAY_LIMIT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def video_info(self) -> Global___VideoInfo:
        """视频流信息"""

    @_builtins.property
    def play_conf(self) -> Global___PlayAbilityConf:
        """播放控件用户自定义配置"""

    @_builtins.property
    def upgrade_limit(self) -> Global___UpgradeLimit:
        """互动视频升级提示"""

    @_builtins.property
    def chronos(self) -> Global___Chronos:
        """Chronos灰度管理"""

    @_builtins.property
    def play_arc(self) -> Global___PlayArcConf:
        """播放控件稿件配置"""

    @_builtins.property
    def event(self) -> Global___Event:
        """事件"""

    @_builtins.property
    def ab(self) -> Global___AB:
        """"""

    @_builtins.property
    def play_limit(self) -> Global___PlayLimit:
        """"""

    def __init__(
        self,
        *,
        video_info: Global___VideoInfo | None = ...,
        play_conf: Global___PlayAbilityConf | None = ...,
        upgrade_limit: Global___UpgradeLimit | None = ...,
        chronos: Global___Chronos | None = ...,
        play_arc: Global___PlayArcConf | None = ...,
        event: Global___Event | None = ...,
        ab: Global___AB | None = ...,
        play_limit: Global___PlayLimit | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ab", b"ab", "chronos", b"chronos", "event", b"event", "play_arc", b"play_arc", "play_conf", b"play_conf", "play_limit", b"play_limit", "upgrade_limit", b"upgrade_limit", "video_info", b"video_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ab", b"ab", "chronos", b"chronos", "event", b"event", "play_arc", b"play_arc", "play_conf", b"play_conf", "play_limit", b"play_limit", "upgrade_limit", b"upgrade_limit", "video_info", b"video_info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlayViewReply: _TypeAlias = PlayViewReply  # noqa: Y015

@_typing.final
class PlayViewReq(_message.Message):
    """播放页信息-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    AID_FIELD_NUMBER: _builtins.int
    CID_FIELD_NUMBER: _builtins.int
    QN_FIELD_NUMBER: _builtins.int
    FNVER_FIELD_NUMBER: _builtins.int
    FNVAL_FIELD_NUMBER: _builtins.int
    DOWNLOAD_FIELD_NUMBER: _builtins.int
    FORCE_HOST_FIELD_NUMBER: _builtins.int
    FOURK_FIELD_NUMBER: _builtins.int
    SPMID_FIELD_NUMBER: _builtins.int
    FROM_SPMID_FIELD_NUMBER: _builtins.int
    TEENAGERS_MODE_FIELD_NUMBER: _builtins.int
    PREFER_CODEC_TYPE_FIELD_NUMBER: _builtins.int
    BUSINESS_FIELD_NUMBER: _builtins.int
    VOICE_BALANCE_FIELD_NUMBER: _builtins.int
    aid: _builtins.int
    """稿件avid"""
    cid: _builtins.int
    """视频cid"""
    qn: _builtins.int
    """清晰度"""
    fnver: _builtins.int
    """视频流版本"""
    fnval: _builtins.int
    """视频流格式"""
    download: _builtins.int
    """下载模式
    0:播放 1:flv下载 2:dash下载
    """
    force_host: _builtins.int
    """流url强制是用域名
    0:允许使用ip 1:使用http 2:使用https
    """
    fourk: _builtins.bool
    """是否4K"""
    spmid: _builtins.str
    """当前页spm"""
    from_spmid: _builtins.str
    """上一页spm"""
    teenagers_mode: _builtins.int
    """青少年模式"""
    prefer_codec_type: Global___CodeType.ValueType
    """编码"""
    business: Global___Business.ValueType
    """业务类型"""
    voice_balance: _builtins.int
    """"""
    def __init__(
        self,
        *,
        aid: _builtins.int = ...,
        cid: _builtins.int = ...,
        qn: _builtins.int = ...,
        fnver: _builtins.int = ...,
        fnval: _builtins.int = ...,
        download: _builtins.int = ...,
        force_host: _builtins.int = ...,
        fourk: _builtins.bool = ...,
        spmid: _builtins.str = ...,
        from_spmid: _builtins.str = ...,
        teenagers_mode: _builtins.int = ...,
        prefer_codec_type: Global___CodeType.ValueType = ...,
        business: Global___Business.ValueType = ...,
        voice_balance: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aid", b"aid", "business", b"business", "cid", b"cid", "download", b"download", "fnval", b"fnval", "fnver", b"fnver", "force_host", b"force_host", "fourk", b"fourk", "from_spmid", b"from_spmid", "prefer_codec_type", b"prefer_codec_type", "qn", b"qn", "spmid", b"spmid", "teenagers_mode", b"teenagers_mode", "voice_balance", b"voice_balance"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlayViewReq: _TypeAlias = PlayViewReq  # noqa: Y015

@_typing.final
class ProjectReply(_message.Message):
    """投屏地址-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    PROJECT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def project(self) -> Global___PlayURLReply: ...
    def __init__(
        self,
        *,
        project: Global___PlayURLReply | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["project", b"project"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["project", b"project"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProjectReply: _TypeAlias = ProjectReply  # noqa: Y015

@_typing.final
class ProjectReq(_message.Message):
    """投屏地址-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    AID_FIELD_NUMBER: _builtins.int
    CID_FIELD_NUMBER: _builtins.int
    QN_FIELD_NUMBER: _builtins.int
    FNVER_FIELD_NUMBER: _builtins.int
    FNVAL_FIELD_NUMBER: _builtins.int
    DOWNLOAD_FIELD_NUMBER: _builtins.int
    FORCE_HOST_FIELD_NUMBER: _builtins.int
    FOURK_FIELD_NUMBER: _builtins.int
    SPMID_FIELD_NUMBER: _builtins.int
    FROM_SPMID_FIELD_NUMBER: _builtins.int
    PROTOCOL_FIELD_NUMBER: _builtins.int
    DEVICE_TYPE_FIELD_NUMBER: _builtins.int
    aid: _builtins.int
    """稿件avid"""
    cid: _builtins.int
    """视频cid"""
    qn: _builtins.int
    """清晰度"""
    fnver: _builtins.int
    """视频流版本"""
    fnval: _builtins.int
    """视频流格式"""
    download: _builtins.int
    """下载模式
    0:播放 1:flv下载 2:dash下载
    """
    force_host: _builtins.int
    """流url强制是用域名
    0:允许使用ip 1:使用http 2:使用https
    """
    fourk: _builtins.bool
    """是否4K"""
    spmid: _builtins.str
    """当前页spm"""
    from_spmid: _builtins.str
    """上一页spm"""
    protocol: _builtins.int
    """使用协议
    0:默认乐播 1:自建协议 2:云投屏 3:airplay
    """
    device_type: _builtins.int
    """投屏设备
    0:默认其他 1:OTT设备
    """
    def __init__(
        self,
        *,
        aid: _builtins.int = ...,
        cid: _builtins.int = ...,
        qn: _builtins.int = ...,
        fnver: _builtins.int = ...,
        fnval: _builtins.int = ...,
        download: _builtins.int = ...,
        force_host: _builtins.int = ...,
        fourk: _builtins.bool = ...,
        spmid: _builtins.str = ...,
        from_spmid: _builtins.str = ...,
        protocol: _builtins.int = ...,
        device_type: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aid", b"aid", "cid", b"cid", "device_type", b"device_type", "download", b"download", "fnval", b"fnval", "fnver", b"fnver", "force_host", b"force_host", "fourk", b"fourk", "from_spmid", b"from_spmid", "protocol", b"protocol", "qn", b"qn", "spmid", b"spmid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProjectReq: _TypeAlias = ProjectReq  # noqa: Y015

@_typing.final
class ResponseDash(_message.Message):
    """dash数据"""

    DESCRIPTOR: _descriptor.Descriptor

    VIDEO_FIELD_NUMBER: _builtins.int
    AUDIO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def video(self) -> _containers.RepeatedCompositeFieldContainer[Global___DashItem]:
        """dash视频流"""

    @_builtins.property
    def audio(self) -> _containers.RepeatedCompositeFieldContainer[Global___DashItem]:
        """dash伴音流"""

    def __init__(
        self,
        *,
        video: _abc.Iterable[Global___DashItem] | None = ...,
        audio: _abc.Iterable[Global___DashItem] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio", b"audio", "video", b"video"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseDash: _TypeAlias = ResponseDash  # noqa: Y015

@_typing.final
class ResponseUrl(_message.Message):
    """分段流条目"""

    DESCRIPTOR: _descriptor.Descriptor

    ORDER_FIELD_NUMBER: _builtins.int
    LENGTH_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    BACKUP_URL_FIELD_NUMBER: _builtins.int
    MD5_FIELD_NUMBER: _builtins.int
    order: _builtins.int
    """分段序号"""
    length: _builtins.int
    """分段时长"""
    size: _builtins.int
    """分段大小"""
    url: _builtins.str
    """主线流"""
    md5: _builtins.str
    """md5"""
    @_builtins.property
    def backup_url(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """备用流"""

    def __init__(
        self,
        *,
        order: _builtins.int = ...,
        length: _builtins.int = ...,
        size: _builtins.int = ...,
        url: _builtins.str = ...,
        backup_url: _abc.Iterable[_builtins.str] | None = ...,
        md5: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["backup_url", b"backup_url", "length", b"length", "md5", b"md5", "order", b"order", "size", b"size", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseUrl: _TypeAlias = ResponseUrl  # noqa: Y015

@_typing.final
class SegmentVideo(_message.Message):
    """分段视频流"""

    DESCRIPTOR: _descriptor.Descriptor

    SEGMENT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def segment(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResponseUrl]:
        """分段视频流列表"""

    def __init__(
        self,
        *,
        segment: _abc.Iterable[Global___ResponseUrl] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["segment", b"segment"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SegmentVideo: _TypeAlias = SegmentVideo  # noqa: Y015

@_typing.final
class Shake(_message.Message):
    """震动"""

    DESCRIPTOR: _descriptor.Descriptor

    FILE_FIELD_NUMBER: _builtins.int
    file: _builtins.str
    """文件地址"""
    def __init__(
        self,
        *,
        file: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["file", b"file"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Shake: _TypeAlias = Shake  # noqa: Y015

@_typing.final
class Stream(_message.Message):
    """视频流信息"""

    DESCRIPTOR: _descriptor.Descriptor

    STREAM_INFO_FIELD_NUMBER: _builtins.int
    DASH_VIDEO_FIELD_NUMBER: _builtins.int
    SEGMENT_VIDEO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stream_info(self) -> Global___StreamInfo:
        """元数据"""

    @_builtins.property
    def dash_video(self) -> Global___DashVideo:
        """dash流"""

    @_builtins.property
    def segment_video(self) -> Global___SegmentVideo:
        """分段流"""

    def __init__(
        self,
        *,
        stream_info: Global___StreamInfo | None = ...,
        dash_video: Global___DashVideo | None = ...,
        segment_video: Global___SegmentVideo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "dash_video", b"dash_video", "segment_video", b"segment_video", "stream_info", b"stream_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "dash_video", b"dash_video", "segment_video", b"segment_video", "stream_info", b"stream_info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_content: _TypeAlias = _typing.Literal["dash_video", "segment_video"]  # noqa: Y015
    _WhichOneofArgType_content: _TypeAlias = _typing.Literal["content", b"content"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_content) -> _WhichOneofReturnType_content | None: ...

Global___Stream: _TypeAlias = Stream  # noqa: Y015

@_typing.final
class StreamInfo(_message.Message):
    """流媒体元数据"""

    DESCRIPTOR: _descriptor.Descriptor

    QUALITY_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    ERR_CODE_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    NEED_VIP_FIELD_NUMBER: _builtins.int
    NEED_LOGIN_FIELD_NUMBER: _builtins.int
    INTACT_FIELD_NUMBER: _builtins.int
    NO_REXCODE_FIELD_NUMBER: _builtins.int
    ATTRIBUTE_FIELD_NUMBER: _builtins.int
    NEW_DESCRIPTION_FIELD_NUMBER: _builtins.int
    DISPLAY_DESC_FIELD_NUMBER: _builtins.int
    SUPERSCRIPT_FIELD_NUMBER: _builtins.int
    quality: _builtins.int
    """清晰度"""
    format: _builtins.str
    """格式"""
    description: _builtins.str
    """格式描述"""
    err_code: Global___PlayErr.ValueType
    """错误码"""
    need_vip: _builtins.bool
    """是否需要vip"""
    need_login: _builtins.bool
    """是否需要登录"""
    intact: _builtins.bool
    """是否完整"""
    no_rexcode: _builtins.bool
    """是否非全二压"""
    attribute: _builtins.int
    """清晰度属性位"""
    new_description: _builtins.str
    """新版格式描述"""
    display_desc: _builtins.str
    """格式文字"""
    superscript: _builtins.str
    """新版格式描述备注"""
    @_builtins.property
    def limit(self) -> Global___StreamLimit:
        """不满足条件信息"""

    def __init__(
        self,
        *,
        quality: _builtins.int = ...,
        format: _builtins.str = ...,
        description: _builtins.str = ...,
        err_code: Global___PlayErr.ValueType = ...,
        limit: Global___StreamLimit | None = ...,
        need_vip: _builtins.bool = ...,
        need_login: _builtins.bool = ...,
        intact: _builtins.bool = ...,
        no_rexcode: _builtins.bool = ...,
        attribute: _builtins.int = ...,
        new_description: _builtins.str = ...,
        display_desc: _builtins.str = ...,
        superscript: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["limit", b"limit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attribute", b"attribute", "description", b"description", "display_desc", b"display_desc", "err_code", b"err_code", "format", b"format", "intact", b"intact", "limit", b"limit", "need_login", b"need_login", "need_vip", b"need_vip", "new_description", b"new_description", "no_rexcode", b"no_rexcode", "quality", b"quality", "superscript", b"superscript"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StreamInfo: _TypeAlias = StreamInfo  # noqa: Y015

@_typing.final
class StreamLimit(_message.Message):
    """清晰度不满足条件信息"""

    DESCRIPTOR: _descriptor.Descriptor

    TITLE_FIELD_NUMBER: _builtins.int
    URI_FIELD_NUMBER: _builtins.int
    MSG_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    """标题"""
    uri: _builtins.str
    """跳转地址"""
    msg: _builtins.str
    """提示信息"""
    def __init__(
        self,
        *,
        title: _builtins.str = ...,
        uri: _builtins.str = ...,
        msg: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["msg", b"msg", "title", b"title", "uri", b"uri"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StreamLimit: _TypeAlias = StreamLimit  # noqa: Y015

@_typing.final
class UpgradeButton(_message.Message):
    """互动视频升级按钮信息"""

    DESCRIPTOR: _descriptor.Descriptor

    TITLE_FIELD_NUMBER: _builtins.int
    LINK_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    """标题"""
    link: _builtins.str
    """链接"""
    def __init__(
        self,
        *,
        title: _builtins.str = ...,
        link: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["link", b"link", "title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpgradeButton: _TypeAlias = UpgradeButton  # noqa: Y015

@_typing.final
class UpgradeLimit(_message.Message):
    """互动视频升级提示"""

    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    IMAGE_FIELD_NUMBER: _builtins.int
    BUTTON_FIELD_NUMBER: _builtins.int
    code: _builtins.int
    """错误码"""
    message: _builtins.str
    """错误信息"""
    image: _builtins.str
    """图片url"""
    @_builtins.property
    def button(self) -> Global___UpgradeButton:
        """按钮信息"""

    def __init__(
        self,
        *,
        code: _builtins.int = ...,
        message: _builtins.str = ...,
        image: _builtins.str = ...,
        button: Global___UpgradeButton | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["button", b"button"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["button", b"button", "code", b"code", "image", b"image", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UpgradeLimit: _TypeAlias = UpgradeLimit  # noqa: Y015

@_typing.final
class VideoInfo(_message.Message):
    """视频url信息"""

    DESCRIPTOR: _descriptor.Descriptor

    QUALITY_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    TIMELENGTH_FIELD_NUMBER: _builtins.int
    VIDEO_CODECID_FIELD_NUMBER: _builtins.int
    STREAM_LIST_FIELD_NUMBER: _builtins.int
    DASH_AUDIO_FIELD_NUMBER: _builtins.int
    DOLBY_FIELD_NUMBER: _builtins.int
    VOLUME_FIELD_NUMBER: _builtins.int
    LOSS_LESS_ITEM_FIELD_NUMBER: _builtins.int
    quality: _builtins.int
    """视频清晰度"""
    format: _builtins.str
    """视频格式"""
    timelength: _builtins.int
    """视频时长"""
    video_codecid: _builtins.int
    """视频编码id"""
    @_builtins.property
    def stream_list(self) -> _containers.RepeatedCompositeFieldContainer[Global___Stream]:
        """视频流"""

    @_builtins.property
    def dash_audio(self) -> _containers.RepeatedCompositeFieldContainer[Global___DashItem]:
        """伴音流"""

    @_builtins.property
    def dolby(self) -> Global___DolbyItem:
        """杜比伴音流"""

    @_builtins.property
    def volume(self) -> Global___VolumeInfo:
        """"""

    @_builtins.property
    def loss_less_item(self) -> Global___LossLessItem:
        """"""

    def __init__(
        self,
        *,
        quality: _builtins.int = ...,
        format: _builtins.str = ...,
        timelength: _builtins.int = ...,
        video_codecid: _builtins.int = ...,
        stream_list: _abc.Iterable[Global___Stream] | None = ...,
        dash_audio: _abc.Iterable[Global___DashItem] | None = ...,
        dolby: Global___DolbyItem | None = ...,
        volume: Global___VolumeInfo | None = ...,
        loss_less_item: Global___LossLessItem | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["dolby", b"dolby", "loss_less_item", b"loss_less_item", "volume", b"volume"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dash_audio", b"dash_audio", "dolby", b"dolby", "format", b"format", "loss_less_item", b"loss_less_item", "quality", b"quality", "stream_list", b"stream_list", "timelength", b"timelength", "video_codecid", b"video_codecid", "volume", b"volume"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VideoInfo: _TypeAlias = VideoInfo  # noqa: Y015

@_typing.final
class VolumeInfo(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    MEASURED_I_FIELD_NUMBER: _builtins.int
    MEASURED_LRA_FIELD_NUMBER: _builtins.int
    MEASURED_TP_FIELD_NUMBER: _builtins.int
    MEASURED_THRESHOLD_FIELD_NUMBER: _builtins.int
    TARGET_OFFSET_FIELD_NUMBER: _builtins.int
    TARGET_I_FIELD_NUMBER: _builtins.int
    TARGET_TP_FIELD_NUMBER: _builtins.int
    measured_i: _builtins.float
    """"""
    measured_lra: _builtins.float
    """"""
    measured_tp: _builtins.float
    """"""
    measured_threshold: _builtins.float
    """"""
    target_offset: _builtins.float
    """"""
    target_i: _builtins.float
    """"""
    target_tp: _builtins.float
    """"""
    def __init__(
        self,
        *,
        measured_i: _builtins.float = ...,
        measured_lra: _builtins.float = ...,
        measured_tp: _builtins.float = ...,
        measured_threshold: _builtins.float = ...,
        target_offset: _builtins.float = ...,
        target_i: _builtins.float = ...,
        target_tp: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["measured_i", b"measured_i", "measured_lra", b"measured_lra", "measured_threshold", b"measured_threshold", "measured_tp", b"measured_tp", "target_i", b"target_i", "target_offset", b"target_offset", "target_tp", b"target_tp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VolumeInfo: _TypeAlias = VolumeInfo  # noqa: Y015
