"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ModeType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ModeTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ModeType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NORMAL: _ModeType.ValueType  # 0
    """正常模式"""
    TEENAGERS: _ModeType.ValueType  # 1
    """青少年模式"""
    LESSONS: _ModeType.ValueType  # 2
    """课堂模式"""
    BASIC: _ModeType.ValueType  # 3
    """"""

class ModeType(_ModeType, metaclass=_ModeTypeEnumTypeWrapper):
    """模式类型"""

NORMAL: ModeType.ValueType  # 0
"""正常模式"""
TEENAGERS: ModeType.ValueType  # 1
"""青少年模式"""
LESSONS: ModeType.ValueType  # 2
"""课堂模式"""
BASIC: ModeType.ValueType  # 3
""""""
Global___ModeType: _TypeAlias = ModeType  # noqa: Y015

@_typing.final
class Restriction(_message.Message):
    """限制条件"""

    DESCRIPTOR: _descriptor.Descriptor

    TEENAGERS_MODE_FIELD_NUMBER: _builtins.int
    LESSONS_MODE_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    REVIEW_FIELD_NUMBER: _builtins.int
    DISABLE_RCMD_FIELD_NUMBER: _builtins.int
    BASIC_MODE_FIELD_NUMBER: _builtins.int
    teenagers_mode: _builtins.bool
    """青少年模式开关状态"""
    lessons_mode: _builtins.bool
    """课堂模式开关状态"""
    mode: Global___ModeType.ValueType
    """模式类型(旧版)"""
    review: _builtins.bool
    """app 审核review状态"""
    disable_rcmd: _builtins.bool
    """客户端是否选择关闭个性化推荐"""
    basic_mode: _builtins.bool
    """"""
    def __init__(
        self,
        *,
        teenagers_mode: _builtins.bool = ...,
        lessons_mode: _builtins.bool = ...,
        mode: Global___ModeType.ValueType = ...,
        review: _builtins.bool = ...,
        disable_rcmd: _builtins.bool = ...,
        basic_mode: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["basic_mode", b"basic_mode", "disable_rcmd", b"disable_rcmd", "lessons_mode", b"lessons_mode", "mode", b"mode", "review", b"review", "teenagers_mode", b"teenagers_mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Restriction: _TypeAlias = Restriction  # noqa: Y015
