"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PremiereStatusReq(_message.Message):
    """获取首播状态-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    EP_ID_FIELD_NUMBER: _builtins.int
    ep_id: _builtins.int
    """剧集epid"""
    def __init__(
        self,
        *,
        ep_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ep_id", b"ep_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PremiereStatusReq: _TypeAlias = PremiereStatusReq  # noqa: Y015

@_typing.final
class PremiereStatusReply(_message.Message):
    """获取首播状态-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    PROGRESS_FIELD_NUMBER: _builtins.int
    START_TIME_FIELD_NUMBER: _builtins.int
    DELAY_TIME_FIELD_NUMBER: _builtins.int
    ONLINE_COUNT_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    AFTER_PREMIERE_TYPE_FIELD_NUMBER: _builtins.int
    progress: _builtins.int
    """服务端播放进度 单位ms 用户实际播放进度：progress - delay_time"""
    start_time: _builtins.int
    """起播时间戳 单位ms"""
    delay_time: _builtins.int
    """延迟播放时长 单位ms"""
    online_count: _builtins.int
    """首播在线人数"""
    status: _builtins.int
    """首播状态
    1:预热 2:首播中 3:紧急停播 4:已结束
    """
    after_premiere_type: _builtins.int
    """首播结束后跳转类型
    1:下架 2:转点播
    """
    def __init__(
        self,
        *,
        progress: _builtins.int = ...,
        start_time: _builtins.int = ...,
        delay_time: _builtins.int = ...,
        online_count: _builtins.int = ...,
        status: _builtins.int = ...,
        after_premiere_type: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["after_premiere_type", b"after_premiere_type", "delay_time", b"delay_time", "online_count", b"online_count", "progress", b"progress", "start_time", b"start_time", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PremiereStatusReply: _TypeAlias = PremiereStatusReply  # noqa: Y015
