"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GetOnlineRankReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    RUID_FIELD_NUMBER: _builtins.int
    ROOM_ID_FIELD_NUMBER: _builtins.int
    PAGE_FIELD_NUMBER: _builtins.int
    PAGE_SIZE_FIELD_NUMBER: _builtins.int
    PLATFORM_FIELD_NUMBER: _builtins.int
    ruid: _builtins.int
    """"""
    room_id: _builtins.int
    """"""
    page: _builtins.int
    """"""
    page_size: _builtins.int
    """"""
    platform: _builtins.str
    """"""
    def __init__(
        self,
        *,
        ruid: _builtins.int = ...,
        room_id: _builtins.int = ...,
        page: _builtins.int = ...,
        page_size: _builtins.int = ...,
        platform: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["page", b"page", "page_size", b"page_size", "platform", b"platform", "room_id", b"room_id", "ruid", b"ruid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetOnlineRankReq: _TypeAlias = GetOnlineRankReq  # noqa: Y015

@_typing.final
class GetOnlineRankResp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class OnlineRankItem(_message.Message):
        """"""

        DESCRIPTOR: _descriptor.Descriptor

        UID_FIELD_NUMBER: _builtins.int
        UNAME_FIELD_NUMBER: _builtins.int
        FACE_FIELD_NUMBER: _builtins.int
        CONTINUE_WATCH_FIELD_NUMBER: _builtins.int
        MEDAL_INFO_FIELD_NUMBER: _builtins.int
        GUARD_LEVEL_FIELD_NUMBER: _builtins.int
        uid: _builtins.int
        """"""
        uname: _builtins.str
        """"""
        face: _builtins.str
        """"""
        continue_watch: _builtins.int
        """"""
        guard_level: _builtins.int
        """"""
        @_builtins.property
        def medal_info(self) -> Global___MedalInfo:
            """"""

        def __init__(
            self,
            *,
            uid: _builtins.int = ...,
            uname: _builtins.str = ...,
            face: _builtins.str = ...,
            continue_watch: _builtins.int = ...,
            medal_info: Global___MedalInfo | None = ...,
            guard_level: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["medal_info", b"medal_info"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["continue_watch", b"continue_watch", "face", b"face", "guard_level", b"guard_level", "medal_info", b"medal_info", "uid", b"uid", "uname", b"uname"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    ITEM_FIELD_NUMBER: _builtins.int
    ONLINE_NUM_FIELD_NUMBER: _builtins.int
    online_num: _builtins.int
    """"""
    @_builtins.property
    def item(self) -> Global___GetOnlineRankResp.OnlineRankItem:
        """"""

    def __init__(
        self,
        *,
        item: Global___GetOnlineRankResp.OnlineRankItem | None = ...,
        online_num: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["item", b"item"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["item", b"item", "online_num", b"online_num"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetOnlineRankResp: _TypeAlias = GetOnlineRankResp  # noqa: Y015

@_typing.final
class MedalInfo(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    GUARD_LEVEL_FIELD_NUMBER: _builtins.int
    MEDAL_COLOR_START_FIELD_NUMBER: _builtins.int
    MEDAL_COLOR_END_FIELD_NUMBER: _builtins.int
    MEDAL_COLOR_BORDER_FIELD_NUMBER: _builtins.int
    MEDAL_NAME_FIELD_NUMBER: _builtins.int
    LEVEL_FIELD_NUMBER: _builtins.int
    TARGET_ID_FIELD_NUMBER: _builtins.int
    IS_LIGHT_FIELD_NUMBER: _builtins.int
    guard_level: _builtins.int
    """"""
    medal_color_start: _builtins.int
    """"""
    medal_color_end: _builtins.int
    """"""
    medal_color_border: _builtins.int
    """"""
    medal_name: _builtins.str
    """"""
    level: _builtins.int
    """"""
    target_id: _builtins.int
    """"""
    is_light: _builtins.int
    """"""
    def __init__(
        self,
        *,
        guard_level: _builtins.int = ...,
        medal_color_start: _builtins.int = ...,
        medal_color_end: _builtins.int = ...,
        medal_color_border: _builtins.int = ...,
        medal_name: _builtins.str = ...,
        level: _builtins.int = ...,
        target_id: _builtins.int = ...,
        is_light: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["guard_level", b"guard_level", "is_light", b"is_light", "level", b"level", "medal_color_border", b"medal_color_border", "medal_color_end", b"medal_color_end", "medal_color_start", b"medal_color_start", "medal_name", b"medal_name", "target_id", b"target_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MedalInfo: _TypeAlias = MedalInfo  # noqa: Y015
