"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Arc(_message.Message):
    """稿件基本信息"""

    DESCRIPTOR: _descriptor.Descriptor

    AID_FIELD_NUMBER: _builtins.int
    VIDEOS_FIELD_NUMBER: _builtins.int
    TYPE_ID_FIELD_NUMBER: _builtins.int
    TYPE_NAME_FIELD_NUMBER: _builtins.int
    COPYRIGHT_FIELD_NUMBER: _builtins.int
    PIC_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    PUBDATE_FIELD_NUMBER: _builtins.int
    CTIME_FIELD_NUMBER: _builtins.int
    DESC_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    ACCESS_FIELD_NUMBER: _builtins.int
    ATTRIBUTE_FIELD_NUMBER: _builtins.int
    TAG_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    DURATION_FIELD_NUMBER: _builtins.int
    MISSION_ID_FIELD_NUMBER: _builtins.int
    ORDER_ID_FIELD_NUMBER: _builtins.int
    REDIRECT_URL_FIELD_NUMBER: _builtins.int
    FORWARD_FIELD_NUMBER: _builtins.int
    RIGHTS_FIELD_NUMBER: _builtins.int
    AUTHOR_FIELD_NUMBER: _builtins.int
    STAT_FIELD_NUMBER: _builtins.int
    REPORT_RESULT_FIELD_NUMBER: _builtins.int
    DYNAMIC_FIELD_NUMBER: _builtins.int
    FIRST_CID_FIELD_NUMBER: _builtins.int
    DIMENSION_FIELD_NUMBER: _builtins.int
    STAFF_INFO_FIELD_NUMBER: _builtins.int
    SEASON_ID_FIELD_NUMBER: _builtins.int
    ATTRIBUTE_V2_FIELD_NUMBER: _builtins.int
    SEASON_THEME_FIELD_NUMBER: _builtins.int
    SHORT_LINK_V2_FIELD_NUMBER: _builtins.int
    UP_FROM_V2_FIELD_NUMBER: _builtins.int
    FIRST_FRAME_FIELD_NUMBER: _builtins.int
    aid: _builtins.int
    """稿件avid"""
    videos: _builtins.int
    """稿件分P数"""
    type_id: _builtins.int
    """分区id"""
    type_name: _builtins.str
    """二级分区名"""
    copyright: _builtins.int
    """稿件类型
    1:原创 2:转载
    """
    pic: _builtins.str
    """稿件封面url"""
    title: _builtins.str
    """稿件标题"""
    pubdate: _builtins.int
    """稿件发布时间"""
    ctime: _builtins.int
    """用户投稿时间"""
    desc: _builtins.str
    """稿件简介"""
    state: _builtins.int
    """稿件状态"""
    access: _builtins.int
    """访问属性
    0:全部可见 10000:登录可见
    """
    attribute: _builtins.int
    """属性位配置(现在无了)"""
    tag: _builtins.str
    """空"""
    duration: _builtins.int
    """稿件总时长(单位为秒)"""
    mission_id: _builtins.int
    """参与的活动id"""
    order_id: _builtins.int
    """绑定的商单id"""
    redirect_url: _builtins.str
    """PGC稿件强制重定向url(如番剧、影视)"""
    forward: _builtins.int
    """空"""
    report_result: _builtins.str
    """空"""
    dynamic: _builtins.str
    """投稿时发送的动态内容"""
    first_cid: _builtins.int
    """稿件1P cid"""
    season_id: _builtins.int
    """UGC合集id"""
    attribute_v2: _builtins.int
    """新版属性位配置(也没用)"""
    short_link_v2: _builtins.str
    """"""
    up_from_v2: _builtins.int
    """"""
    first_frame: _builtins.str
    """"""
    @_builtins.property
    def tags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """空"""

    @_builtins.property
    def rights(self) -> Global___Rights:
        """控制标志"""

    @_builtins.property
    def author(self) -> Global___Author:
        """UP主信息"""

    @_builtins.property
    def stat(self) -> Global___Stat:
        """状态数"""

    @_builtins.property
    def dimension(self) -> Global___Dimension:
        """稿件1P 分辨率"""

    @_builtins.property
    def staff_info(self) -> _containers.RepeatedCompositeFieldContainer[Global___StaffInfo]:
        """合作组成员列表"""

    @_builtins.property
    def season_theme(self) -> Global___SeasonTheme:
        """"""

    def __init__(
        self,
        *,
        aid: _builtins.int = ...,
        videos: _builtins.int = ...,
        type_id: _builtins.int = ...,
        type_name: _builtins.str = ...,
        copyright: _builtins.int = ...,
        pic: _builtins.str = ...,
        title: _builtins.str = ...,
        pubdate: _builtins.int = ...,
        ctime: _builtins.int = ...,
        desc: _builtins.str = ...,
        state: _builtins.int = ...,
        access: _builtins.int = ...,
        attribute: _builtins.int = ...,
        tag: _builtins.str = ...,
        tags: _abc.Iterable[_builtins.str] | None = ...,
        duration: _builtins.int = ...,
        mission_id: _builtins.int = ...,
        order_id: _builtins.int = ...,
        redirect_url: _builtins.str = ...,
        forward: _builtins.int = ...,
        rights: Global___Rights | None = ...,
        author: Global___Author | None = ...,
        stat: Global___Stat | None = ...,
        report_result: _builtins.str = ...,
        dynamic: _builtins.str = ...,
        first_cid: _builtins.int = ...,
        dimension: Global___Dimension | None = ...,
        staff_info: _abc.Iterable[Global___StaffInfo] | None = ...,
        season_id: _builtins.int = ...,
        attribute_v2: _builtins.int = ...,
        season_theme: Global___SeasonTheme | None = ...,
        short_link_v2: _builtins.str = ...,
        up_from_v2: _builtins.int = ...,
        first_frame: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["author", b"author", "dimension", b"dimension", "rights", b"rights", "season_theme", b"season_theme", "stat", b"stat"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["access", b"access", "aid", b"aid", "attribute", b"attribute", "attribute_v2", b"attribute_v2", "author", b"author", "copyright", b"copyright", "ctime", b"ctime", "desc", b"desc", "dimension", b"dimension", "duration", b"duration", "dynamic", b"dynamic", "first_cid", b"first_cid", "first_frame", b"first_frame", "forward", b"forward", "mission_id", b"mission_id", "order_id", b"order_id", "pic", b"pic", "pubdate", b"pubdate", "redirect_url", b"redirect_url", "report_result", b"report_result", "rights", b"rights", "season_id", b"season_id", "season_theme", b"season_theme", "short_link_v2", b"short_link_v2", "staff_info", b"staff_info", "stat", b"stat", "state", b"state", "tag", b"tag", "tags", b"tags", "title", b"title", "type_id", b"type_id", "type_name", b"type_name", "up_from_v2", b"up_from_v2", "videos", b"videos"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Arc: _TypeAlias = Arc  # noqa: Y015

@_typing.final
class Author(_message.Message):
    """UP主信息"""

    DESCRIPTOR: _descriptor.Descriptor

    MID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    FACE_FIELD_NUMBER: _builtins.int
    mid: _builtins.int
    """UP主mid"""
    name: _builtins.str
    """UP主昵称"""
    face: _builtins.str
    """UP主头像url"""
    def __init__(
        self,
        *,
        mid: _builtins.int = ...,
        name: _builtins.str = ...,
        face: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["face", b"face", "mid", b"mid", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Author: _TypeAlias = Author  # noqa: Y015

@_typing.final
class Dimension(_message.Message):
    """分辨率"""

    DESCRIPTOR: _descriptor.Descriptor

    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    ROTATE_FIELD_NUMBER: _builtins.int
    width: _builtins.int
    """宽度"""
    height: _builtins.int
    """高度"""
    rotate: _builtins.int
    """方向
    0:横屏 1:竖屏
    """
    def __init__(
        self,
        *,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
        rotate: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "rotate", b"rotate", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Dimension: _TypeAlias = Dimension  # noqa: Y015

@_typing.final
class Page(_message.Message):
    """分P信息"""

    DESCRIPTOR: _descriptor.Descriptor

    CID_FIELD_NUMBER: _builtins.int
    PAGE_FIELD_NUMBER: _builtins.int
    FROM_FIELD_NUMBER: _builtins.int
    PART_FIELD_NUMBER: _builtins.int
    DURATION_FIELD_NUMBER: _builtins.int
    VID_FIELD_NUMBER: _builtins.int
    DESC_FIELD_NUMBER: _builtins.int
    WEBLINK_FIELD_NUMBER: _builtins.int
    DIMENSION_FIELD_NUMBER: _builtins.int
    FIRST_FRAME_FIELD_NUMBER: _builtins.int
    cid: _builtins.int
    """视频cid"""
    page: _builtins.int
    """分P序号"""
    part: _builtins.str
    """分P标题"""
    duration: _builtins.int
    """分P时长(单位为秒)"""
    vid: _builtins.str
    """外链vid"""
    desc: _builtins.str
    """分P简介"""
    webLink: _builtins.str
    """外链url"""
    first_frame: _builtins.str
    """"""
    @_builtins.property
    def dimension(self) -> Global___Dimension:
        """分P分辨率"""

    def __init__(
        self,
        *,
        cid: _builtins.int = ...,
        page: _builtins.int = ...,
        part: _builtins.str = ...,
        duration: _builtins.int = ...,
        vid: _builtins.str = ...,
        desc: _builtins.str = ...,
        webLink: _builtins.str = ...,
        dimension: Global___Dimension | None = ...,
        first_frame: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["dimension", b"dimension"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cid", b"cid", "desc", b"desc", "dimension", b"dimension", "duration", b"duration", "first_frame", b"first_frame", "from", b"from", "page", b"page", "part", b"part", "vid", b"vid", "webLink", b"webLink"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Page: _TypeAlias = Page  # noqa: Y015

@_typing.final
class Rights(_message.Message):
    """稿件控制标志"""

    DESCRIPTOR: _descriptor.Descriptor

    BP_FIELD_NUMBER: _builtins.int
    ELEC_FIELD_NUMBER: _builtins.int
    DOWNLOAD_FIELD_NUMBER: _builtins.int
    MOVIE_FIELD_NUMBER: _builtins.int
    PAY_FIELD_NUMBER: _builtins.int
    HD5_FIELD_NUMBER: _builtins.int
    NO_REPRINT_FIELD_NUMBER: _builtins.int
    AUTOPLAY_FIELD_NUMBER: _builtins.int
    UGC_PAY_FIELD_NUMBER: _builtins.int
    IS_COOPERATION_FIELD_NUMBER: _builtins.int
    UGC_PAY_PREVIEW_FIELD_NUMBER: _builtins.int
    NO_BACKGROUND_FIELD_NUMBER: _builtins.int
    ARC_PAY_FIELD_NUMBER: _builtins.int
    PAY_FREE_WATCH_FIELD_NUMBER: _builtins.int
    bp: _builtins.int
    """老版是否付费"""
    elec: _builtins.int
    """允许充电"""
    download: _builtins.int
    """允许下载"""
    movie: _builtins.int
    """是否电影"""
    pay: _builtins.int
    """PGC稿件需要付费"""
    hd5: _builtins.int
    """是否高码率"""
    no_reprint: _builtins.int
    """是否显示“禁止转载”标志"""
    autoplay: _builtins.int
    """是否允许自动播放"""
    ugc_pay: _builtins.int
    """UGC稿件需要付费(旧版)"""
    is_cooperation: _builtins.int
    """是否联合投稿"""
    ugc_pay_preview: _builtins.int
    """是否UGC付费预览"""
    no_background: _builtins.int
    """是否禁止后台播放"""
    arc_pay: _builtins.int
    """UGC稿件需要付费"""
    pay_free_watch: _builtins.int
    """是否已付费可自由观看"""
    def __init__(
        self,
        *,
        bp: _builtins.int = ...,
        elec: _builtins.int = ...,
        download: _builtins.int = ...,
        movie: _builtins.int = ...,
        pay: _builtins.int = ...,
        hd5: _builtins.int = ...,
        no_reprint: _builtins.int = ...,
        autoplay: _builtins.int = ...,
        ugc_pay: _builtins.int = ...,
        is_cooperation: _builtins.int = ...,
        ugc_pay_preview: _builtins.int = ...,
        no_background: _builtins.int = ...,
        arc_pay: _builtins.int = ...,
        pay_free_watch: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["arc_pay", b"arc_pay", "autoplay", b"autoplay", "bp", b"bp", "download", b"download", "elec", b"elec", "hd5", b"hd5", "is_cooperation", b"is_cooperation", "movie", b"movie", "no_background", b"no_background", "no_reprint", b"no_reprint", "pay", b"pay", "pay_free_watch", b"pay_free_watch", "ugc_pay", b"ugc_pay", "ugc_pay_preview", b"ugc_pay_preview"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Rights: _TypeAlias = Rights  # noqa: Y015

@_typing.final
class SeasonTheme(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BG_COLOR_FIELD_NUMBER: _builtins.int
    SELECTED_BG_COLOR_FIELD_NUMBER: _builtins.int
    TEXT_COLOR_FIELD_NUMBER: _builtins.int
    bg_color: _builtins.str
    """"""
    selected_bg_color: _builtins.str
    """"""
    text_color: _builtins.str
    """"""
    def __init__(
        self,
        *,
        bg_color: _builtins.str = ...,
        selected_bg_color: _builtins.str = ...,
        text_color: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bg_color", b"bg_color", "selected_bg_color", b"selected_bg_color", "text_color", b"text_color"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SeasonTheme: _TypeAlias = SeasonTheme  # noqa: Y015

@_typing.final
class StaffInfo(_message.Message):
    """合作成员信息"""

    DESCRIPTOR: _descriptor.Descriptor

    MID_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    ATTRIBUTE_FIELD_NUMBER: _builtins.int
    mid: _builtins.int
    """成员mid"""
    title: _builtins.str
    """成员角色"""
    attribute: _builtins.int
    """属性位
    0:普通 1:赞助商金色标志
    """
    def __init__(
        self,
        *,
        mid: _builtins.int = ...,
        title: _builtins.str = ...,
        attribute: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attribute", b"attribute", "mid", b"mid", "title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StaffInfo: _TypeAlias = StaffInfo  # noqa: Y015

@_typing.final
class Stat(_message.Message):
    """状态数"""

    DESCRIPTOR: _descriptor.Descriptor

    AID_FIELD_NUMBER: _builtins.int
    VIEW_FIELD_NUMBER: _builtins.int
    DANMAKU_FIELD_NUMBER: _builtins.int
    REPLY_FIELD_NUMBER: _builtins.int
    FAV_FIELD_NUMBER: _builtins.int
    COIN_FIELD_NUMBER: _builtins.int
    SHARE_FIELD_NUMBER: _builtins.int
    NOW_RANK_FIELD_NUMBER: _builtins.int
    HIS_RANK_FIELD_NUMBER: _builtins.int
    LIKE_FIELD_NUMBER: _builtins.int
    DISLIKE_FIELD_NUMBER: _builtins.int
    aid: _builtins.int
    """稿件avid"""
    view: _builtins.int
    """播放数(当屏蔽时为-1)"""
    danmaku: _builtins.int
    """弹幕数"""
    reply: _builtins.int
    """评论数"""
    fav: _builtins.int
    """收藏数"""
    coin: _builtins.int
    """投币数"""
    share: _builtins.int
    """分享数"""
    now_rank: _builtins.int
    """当前排名"""
    his_rank: _builtins.int
    """历史最高排名"""
    like: _builtins.int
    """点赞数"""
    dislike: _builtins.int
    """点踩数(前端不可见故恒为0)"""
    def __init__(
        self,
        *,
        aid: _builtins.int = ...,
        view: _builtins.int = ...,
        danmaku: _builtins.int = ...,
        reply: _builtins.int = ...,
        fav: _builtins.int = ...,
        coin: _builtins.int = ...,
        share: _builtins.int = ...,
        now_rank: _builtins.int = ...,
        his_rank: _builtins.int = ...,
        like: _builtins.int = ...,
        dislike: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aid", b"aid", "coin", b"coin", "danmaku", b"danmaku", "dislike", b"dislike", "fav", b"fav", "his_rank", b"his_rank", "like", b"like", "now_rank", b"now_rank", "reply", b"reply", "share", b"share", "view", b"view"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Stat: _TypeAlias = Stat  # noqa: Y015
