"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Metadata(_message.Message):
    """请求元数据
    gRPC头部:x-bili-metadata-bin
    """

    DESCRIPTOR: _descriptor.Descriptor

    ACCESS_KEY_FIELD_NUMBER: _builtins.int
    MOBI_APP_FIELD_NUMBER: _builtins.int
    DEVICE_FIELD_NUMBER: _builtins.int
    BUILD_FIELD_NUMBER: _builtins.int
    CHANNEL_FIELD_NUMBER: _builtins.int
    BUVID_FIELD_NUMBER: _builtins.int
    PLATFORM_FIELD_NUMBER: _builtins.int
    access_key: _builtins.str
    """登录 access_key"""
    mobi_app: _builtins.str
    """包类型, 如 `android`"""
    device: _builtins.str
    """运行设备, 留空即可"""
    build: _builtins.int
    """构建id, 如 `7380300`"""
    channel: _builtins.str
    """APP分发渠道, 如 `master`"""
    buvid: _builtins.str
    """设备唯一标识"""
    platform: _builtins.str
    """平台类型, 如 `android`"""
    def __init__(
        self,
        *,
        access_key: _builtins.str = ...,
        mobi_app: _builtins.str = ...,
        device: _builtins.str = ...,
        build: _builtins.int = ...,
        channel: _builtins.str = ...,
        buvid: _builtins.str = ...,
        platform: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["access_key", b"access_key", "build", b"build", "buvid", b"buvid", "channel", b"channel", "device", b"device", "mobi_app", b"mobi_app", "platform", b"platform"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Metadata: _TypeAlias = Metadata  # noqa: Y015
