"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ArchiveReply(_message.Message):
    """-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    ITEM_FIELD_NUMBER: _builtins.int
    COUNT_FIELD_NUMBER: _builtins.int
    EPISODIC_BUTTON_FIELD_NUMBER: _builtins.int
    ORDER_FIELD_NUMBER: _builtins.int
    count: _builtins.int
    """"""
    @_builtins.property
    def item(self) -> _containers.RepeatedCompositeFieldContainer[Global___BiliSpaceVideo]:
        """"""

    @_builtins.property
    def episodic_button(self) -> Global___EpisodicButton:
        """"""

    @_builtins.property
    def order(self) -> _containers.RepeatedCompositeFieldContainer[Global___OrderConfig]:
        """"""

    def __init__(
        self,
        *,
        item: _abc.Iterable[Global___BiliSpaceVideo] | None = ...,
        count: _builtins.int = ...,
        episodic_button: Global___EpisodicButton | None = ...,
        order: _abc.Iterable[Global___OrderConfig] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["episodic_button", b"episodic_button"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count", b"count", "episodic_button", b"episodic_button", "item", b"item", "order", b"order"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ArchiveReply: _TypeAlias = ArchiveReply  # noqa: Y015

@_typing.final
class ArchiveReq(_message.Message):
    """-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    VMID_FIELD_NUMBER: _builtins.int
    PN_FIELD_NUMBER: _builtins.int
    PS_FIELD_NUMBER: _builtins.int
    ORDER_FIELD_NUMBER: _builtins.int
    vmid: _builtins.int
    """"""
    pn: _builtins.int
    """"""
    ps: _builtins.int
    """"""
    order: _builtins.str
    """"""
    def __init__(
        self,
        *,
        vmid: _builtins.int = ...,
        pn: _builtins.int = ...,
        ps: _builtins.int = ...,
        order: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["order", b"order", "pn", b"pn", "ps", b"ps", "vmid", b"vmid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ArchiveReq: _TypeAlias = ArchiveReq  # noqa: Y015

@_typing.final
class Badge(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    TEXT_COLOR_FIELD_NUMBER: _builtins.int
    TEXT_COLOR_NIGHT_FIELD_NUMBER: _builtins.int
    BG_COLOR_FIELD_NUMBER: _builtins.int
    BG_COLOR_NIGHT_FIELD_NUMBER: _builtins.int
    BORDER_COLOR_FIELD_NUMBER: _builtins.int
    BORDER_COLOR_NIGHT_FIELD_NUMBER: _builtins.int
    BG_STYLE_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    """"""
    text_color: _builtins.str
    """"""
    text_color_night: _builtins.str
    """"""
    bg_color: _builtins.str
    """"""
    bg_color_night: _builtins.str
    """"""
    border_color: _builtins.str
    """"""
    border_color_night: _builtins.str
    """"""
    bg_style: _builtins.int
    """"""
    def __init__(
        self,
        *,
        text: _builtins.str = ...,
        text_color: _builtins.str = ...,
        text_color_night: _builtins.str = ...,
        bg_color: _builtins.str = ...,
        bg_color_night: _builtins.str = ...,
        border_color: _builtins.str = ...,
        border_color_night: _builtins.str = ...,
        bg_style: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bg_color", b"bg_color", "bg_color_night", b"bg_color_night", "bg_style", b"bg_style", "border_color", b"border_color", "border_color_night", b"border_color_night", "text", b"text", "text_color", b"text_color", "text_color_night", b"text_color_night"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Badge: _TypeAlias = Badge  # noqa: Y015

@_typing.final
class BiliSpaceVideo(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TITLE_FIELD_NUMBER: _builtins.int
    TNAME_FIELD_NUMBER: _builtins.int
    DURATION_FIELD_NUMBER: _builtins.int
    COVER_FIELD_NUMBER: _builtins.int
    URI_FIELD_NUMBER: _builtins.int
    PARAM_FIELD_NUMBER: _builtins.int
    DANMAKU_FIELD_NUMBER: _builtins.int
    PLAY_FIELD_NUMBER: _builtins.int
    CTIME_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    IS_POPULAR_FIELD_NUMBER: _builtins.int
    BADGES_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_FIELD_NUMBER: _builtins.int
    BVID_FIELD_NUMBER: _builtins.int
    IS_STEINS_FIELD_NUMBER: _builtins.int
    IS_UGCPAY_FIELD_NUMBER: _builtins.int
    IS_COOPERATION_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    """"""
    tname: _builtins.str
    """"""
    duration: _builtins.int
    """"""
    cover: _builtins.str
    """"""
    uri: _builtins.str
    """"""
    param: _builtins.str
    """"""
    danmaku: _builtins.str
    """"""
    play: _builtins.int
    """"""
    ctime: _builtins.int
    """"""
    state: _builtins.bool
    """"""
    is_popular: _builtins.bool
    """"""
    cover_right: _builtins.str
    """"""
    bvid: _builtins.str
    """"""
    is_steins: _builtins.bool
    """"""
    is_ugcpay: _builtins.bool
    """"""
    is_cooperation: _builtins.bool
    """"""
    @_builtins.property
    def badges(self) -> _containers.RepeatedCompositeFieldContainer[Global___Badge]:
        """"""

    def __init__(
        self,
        *,
        title: _builtins.str = ...,
        tname: _builtins.str = ...,
        duration: _builtins.int = ...,
        cover: _builtins.str = ...,
        uri: _builtins.str = ...,
        param: _builtins.str = ...,
        danmaku: _builtins.str = ...,
        play: _builtins.int = ...,
        ctime: _builtins.int = ...,
        state: _builtins.bool = ...,
        is_popular: _builtins.bool = ...,
        badges: _abc.Iterable[Global___Badge] | None = ...,
        cover_right: _builtins.str = ...,
        bvid: _builtins.str = ...,
        is_steins: _builtins.bool = ...,
        is_ugcpay: _builtins.bool = ...,
        is_cooperation: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["badges", b"badges", "bvid", b"bvid", "cover", b"cover", "cover_right", b"cover_right", "ctime", b"ctime", "danmaku", b"danmaku", "duration", b"duration", "is_cooperation", b"is_cooperation", "is_popular", b"is_popular", "is_steins", b"is_steins", "is_ugcpay", b"is_ugcpay", "param", b"param", "play", b"play", "state", b"state", "title", b"title", "tname", b"tname", "uri", b"uri"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BiliSpaceVideo: _TypeAlias = BiliSpaceVideo  # noqa: Y015

@_typing.final
class EpisodicButton(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    URI_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    """"""
    uri: _builtins.str
    """"""
    def __init__(
        self,
        *,
        text: _builtins.str = ...,
        uri: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["text", b"text", "uri", b"uri"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EpisodicButton: _TypeAlias = EpisodicButton  # noqa: Y015

@_typing.final
class OrderConfig(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TITLE_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    """"""
    value: _builtins.str
    """"""
    def __init__(
        self,
        *,
        title: _builtins.str = ...,
        value: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["title", b"title", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___OrderConfig: _TypeAlias = OrderConfig  # noqa: Y015
