# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: PbPageReqIdl.proto
# plugin: python-betterproto2
# This file has been @generated
# ruff: noqa: RUF009
from dataclasses import dataclass

import betterproto2

default_message_pool = betterproto2.MessagePool()
_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)

@dataclass(eq=False, repr=False)
class CommonReq(betterproto2.Message):
    """
    SOURCE FILE: CommonReq.proto
    """
    _client_type: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)
    _client_version: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    _client_id: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    _phone_imei: "str" = betterproto2.field(5, betterproto2.TYPE_STRING)
    _from: "str" = betterproto2.field(6, betterproto2.TYPE_STRING)
    cuid: "str" = betterproto2.field(7, betterproto2.TYPE_STRING)
    _timestamp: "int" = betterproto2.field(8, betterproto2.TYPE_INT64)
    model: "str" = betterproto2.field(9, betterproto2.TYPE_STRING)
    bduss: "str" = betterproto2.field(10, betterproto2.TYPE_STRING)
    tbs: "str" = betterproto2.field(11, betterproto2.TYPE_STRING)
    net_type: "int" = betterproto2.field(12, betterproto2.TYPE_INT32)
    pversion: "str" = betterproto2.field(24, betterproto2.TYPE_STRING)
    _os_version: "str" = betterproto2.field(25, betterproto2.TYPE_STRING)
    brand: "str" = betterproto2.field(26, betterproto2.TYPE_STRING)
    lego_lib_version: "str" = betterproto2.field(28, betterproto2.TYPE_STRING)
    applist: "str" = betterproto2.field(29, betterproto2.TYPE_STRING)
    stoken: "str" = betterproto2.field(30, betterproto2.TYPE_STRING)
    z_id: "str" = betterproto2.field(31, betterproto2.TYPE_STRING)
    cuid_galaxy2: "str" = betterproto2.field(32, betterproto2.TYPE_STRING)
    cuid_gid: "str" = betterproto2.field(33, betterproto2.TYPE_STRING)
    c3_aid: "str" = betterproto2.field(35, betterproto2.TYPE_STRING)
    sample_id: "str" = betterproto2.field(36, betterproto2.TYPE_STRING)
    scr_w: "int" = betterproto2.field(37, betterproto2.TYPE_INT32)
    scr_h: "int" = betterproto2.field(38, betterproto2.TYPE_INT32)
    scr_dip: "float" = betterproto2.field(39, betterproto2.TYPE_DOUBLE)
    q_type: "int" = betterproto2.field(40, betterproto2.TYPE_INT32)
    is_teenager: "int" = betterproto2.field(41, betterproto2.TYPE_INT32)
    sdk_ver: "str" = betterproto2.field(42, betterproto2.TYPE_STRING)
    framework_ver: "str" = betterproto2.field(43, betterproto2.TYPE_STRING)
    naws_game_ver: "str" = betterproto2.field(44, betterproto2.TYPE_STRING)
    active_timestamp: "int" = betterproto2.field(49, betterproto2.TYPE_INT64)
    first_install_time: "int" = betterproto2.field(50, betterproto2.TYPE_INT64)
    last_update_time: "int" = betterproto2.field(51, betterproto2.TYPE_INT64)
    event_day: "str" = betterproto2.field(53, betterproto2.TYPE_STRING)
    android_id: "str" = betterproto2.field(54, betterproto2.TYPE_STRING)
    cmode: "int" = betterproto2.field(55, betterproto2.TYPE_INT32)
    start_scheme: "str" = betterproto2.field(56, betterproto2.TYPE_STRING)
    start_type: "int" = betterproto2.field(57, betterproto2.TYPE_INT32)
    idfv: "str" = betterproto2.field(60, betterproto2.TYPE_STRING)
    extra: "str" = betterproto2.field(61, betterproto2.TYPE_STRING)
    user_agent: "str" = betterproto2.field(62, betterproto2.TYPE_STRING)
    personalized_rec_switch: "int" = betterproto2.field(63, betterproto2.TYPE_INT32)
    device_score: "str" = betterproto2.field(70, betterproto2.TYPE_STRING)

default_message_pool.register_message("", "CommonReq", CommonReq)

@dataclass(eq=False, repr=False)
class PbPageReqIdl(betterproto2.Message):
    """
    SOURCE FILE: PbPageReqIdl.proto
    """
    data: "PbPageReqIdlDataReq" = betterproto2.field(1, betterproto2.TYPE_MESSAGE)

default_message_pool.register_message("", "PbPageReqIdl", PbPageReqIdl)

@dataclass(eq=False, repr=False)
class PbPageReqIdlDataReq(betterproto2.Message):
    common: "CommonReq" = betterproto2.field(25, betterproto2.TYPE_MESSAGE)
    kz: "int" = betterproto2.field(4, betterproto2.TYPE_INT64)
    lz: "int" = betterproto2.field(5, betterproto2.TYPE_INT32)
    r: "int" = betterproto2.field(6, betterproto2.TYPE_INT32)
    pid: "int" = betterproto2.field(7, betterproto2.TYPE_INT64)
    with_floor: "int" = betterproto2.field(8, betterproto2.TYPE_INT32)
    floor_rn: "int" = betterproto2.field(9, betterproto2.TYPE_INT32)
    rn: "int" = betterproto2.field(13, betterproto2.TYPE_INT32)
    pn: "int" = betterproto2.field(18, betterproto2.TYPE_INT32)
    floor_sort_type: "int" = betterproto2.field(74, betterproto2.TYPE_INT32)

default_message_pool.register_message("", "PbPageReqIdl.DataReq", PbPageReqIdlDataReq)
