"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class RegionConfig(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    SCENES_NAME_FIELD_NUMBER: _builtins.int
    SCENES_TYPE_FIELD_NUMBER: _builtins.int
    scenes_name: _builtins.str
    """"""
    scenes_type: _builtins.str
    """"""
    def __init__(
        self,
        *,
        scenes_name: _builtins.str = ...,
        scenes_type: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["scenes_name", b"scenes_name", "scenes_type", b"scenes_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegionConfig: _TypeAlias = RegionConfig  # noqa: Y015

@_typing.final
class RegionInfo(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TID_FIELD_NUMBER: _builtins.int
    REID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    LOGO_FIELD_NUMBER: _builtins.int
    GOTO_FIELD_NUMBER: _builtins.int
    PARAM_FIELD_NUMBER: _builtins.int
    URI_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    IS_BANGUMI_FIELD_NUMBER: _builtins.int
    CHILDREN_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    tid: _builtins.int
    """"""
    reid: _builtins.int
    """"""
    name: _builtins.str
    """"""
    logo: _builtins.str
    """"""
    goto: _builtins.str
    """"""
    param: _builtins.str
    """"""
    uri: _builtins.str
    """"""
    type: _builtins.int
    """"""
    is_bangumi: _builtins.int
    """"""
    @_builtins.property
    def children(self) -> _containers.RepeatedCompositeFieldContainer[Global___RegionInfo]:
        """"""

    @_builtins.property
    def config(self) -> _containers.RepeatedCompositeFieldContainer[Global___RegionConfig]:
        """"""

    def __init__(
        self,
        *,
        tid: _builtins.int = ...,
        reid: _builtins.int = ...,
        name: _builtins.str = ...,
        logo: _builtins.str = ...,
        goto: _builtins.str = ...,
        param: _builtins.str = ...,
        uri: _builtins.str = ...,
        type: _builtins.int = ...,
        is_bangumi: _builtins.int = ...,
        children: _abc.Iterable[Global___RegionInfo] | None = ...,
        config: _abc.Iterable[Global___RegionConfig] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["children", b"children", "config", b"config", "goto", b"goto", "is_bangumi", b"is_bangumi", "logo", b"logo", "name", b"name", "param", b"param", "reid", b"reid", "tid", b"tid", "type", b"type", "uri", b"uri"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegionInfo: _TypeAlias = RegionInfo  # noqa: Y015

@_typing.final
class RegionReply(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    REGIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def regions(self) -> _containers.RepeatedCompositeFieldContainer[Global___RegionInfo]:
        """"""

    def __init__(
        self,
        *,
        regions: _abc.Iterable[Global___RegionInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["regions", b"regions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegionReply: _TypeAlias = RegionReply  # noqa: Y015

@_typing.final
class RegionReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    LANG_FIELD_NUMBER: _builtins.int
    lang: _builtins.str
    """"""
    def __init__(
        self,
        *,
        lang: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["lang", b"lang"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegionReq: _TypeAlias = RegionReq  # noqa: Y015
