"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from bilibili.app.card.v1 import common_pb2 as _common_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DoubleCards(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    SMALL_COVER_V2_FIELD_NUMBER: _builtins.int
    ONE_PIC_V2_FIELD_NUMBER: _builtins.int
    THREE_PIC_V2_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def small_cover_v2(self) -> Global___SmallCoverV2:
        """"""

    @_builtins.property
    def one_pic_v2(self) -> Global___OnePicV2:
        """"""

    @_builtins.property
    def three_pic_v2(self) -> Global___ThreePicV2:
        """"""

    def __init__(
        self,
        *,
        small_cover_v2: Global___SmallCoverV2 | None = ...,
        one_pic_v2: Global___OnePicV2 | None = ...,
        three_pic_v2: Global___ThreePicV2 | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["Card", b"Card", "one_pic_v2", b"one_pic_v2", "small_cover_v2", b"small_cover_v2", "three_pic_v2", b"three_pic_v2"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["Card", b"Card", "one_pic_v2", b"one_pic_v2", "small_cover_v2", b"small_cover_v2", "three_pic_v2", b"three_pic_v2"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_Card: _TypeAlias = _typing.Literal["small_cover_v2", "one_pic_v2", "three_pic_v2"]  # noqa: Y015
    _WhichOneofArgType_Card: _TypeAlias = _typing.Literal["Card", b"Card"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_Card) -> _WhichOneofReturnType_Card | None: ...

Global___DoubleCards: _TypeAlias = DoubleCards  # noqa: Y015

@_typing.final
class SmallCoverV2(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    COVER_GIF_FIELD_NUMBER: _builtins.int
    COVER_BLUR_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_2_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_2_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_TEXT_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_ICON_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_BACKGROUND_COLOR_FIELD_NUMBER: _builtins.int
    SUBTITLE_FIELD_NUMBER: _builtins.int
    BADGE_FIELD_NUMBER: _builtins.int
    RCMD_REASON_FIELD_NUMBER: _builtins.int
    DESC_FIELD_NUMBER: _builtins.int
    AVATAR_FIELD_NUMBER: _builtins.int
    OFFICIAL_ICON_FIELD_NUMBER: _builtins.int
    CAN_PLAY_FIELD_NUMBER: _builtins.int
    RCMD_REASON_STYLE_FIELD_NUMBER: _builtins.int
    RCMD_REASON_STYLE_V2_FIELD_NUMBER: _builtins.int
    LIKE_BUTTON_FIELD_NUMBER: _builtins.int
    cover_gif: _builtins.str
    """"""
    cover_blur: _builtins.int
    """"""
    cover_left_text_1: _builtins.str
    """"""
    cover_left_icon_1: _builtins.int
    """"""
    cover_left_text_2: _builtins.str
    """"""
    cover_left_icon_2: _builtins.int
    """"""
    cover_right_text: _builtins.str
    """"""
    cover_right_icon: _builtins.int
    """"""
    cover_right_background_color: _builtins.str
    """"""
    subtitle: _builtins.str
    """"""
    badge: _builtins.str
    """"""
    rcmd_reason: _builtins.str
    """"""
    desc: _builtins.str
    """"""
    official_icon: _builtins.int
    """"""
    can_play: _builtins.int
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    @_builtins.property
    def avatar(self) -> _common_pb2.Avatar:
        """"""

    @_builtins.property
    def rcmd_reason_style(self) -> _common_pb2.ReasonStyle:
        """"""

    @_builtins.property
    def rcmd_reason_style_v2(self) -> _common_pb2.ReasonStyle:
        """"""

    @_builtins.property
    def like_button(self) -> _common_pb2.LikeButton:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        cover_gif: _builtins.str = ...,
        cover_blur: _builtins.int = ...,
        cover_left_text_1: _builtins.str = ...,
        cover_left_icon_1: _builtins.int = ...,
        cover_left_text_2: _builtins.str = ...,
        cover_left_icon_2: _builtins.int = ...,
        cover_right_text: _builtins.str = ...,
        cover_right_icon: _builtins.int = ...,
        cover_right_background_color: _builtins.str = ...,
        subtitle: _builtins.str = ...,
        badge: _builtins.str = ...,
        rcmd_reason: _builtins.str = ...,
        desc: _builtins.str = ...,
        avatar: _common_pb2.Avatar | None = ...,
        official_icon: _builtins.int = ...,
        can_play: _builtins.int = ...,
        rcmd_reason_style: _common_pb2.ReasonStyle | None = ...,
        rcmd_reason_style_v2: _common_pb2.ReasonStyle | None = ...,
        like_button: _common_pb2.LikeButton | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["avatar", b"avatar", "base", b"base", "like_button", b"like_button", "rcmd_reason_style", b"rcmd_reason_style", "rcmd_reason_style_v2", b"rcmd_reason_style_v2"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["avatar", b"avatar", "badge", b"badge", "base", b"base", "can_play", b"can_play", "cover_blur", b"cover_blur", "cover_gif", b"cover_gif", "cover_left_icon_1", b"cover_left_icon_1", "cover_left_icon_2", b"cover_left_icon_2", "cover_left_text_1", b"cover_left_text_1", "cover_left_text_2", b"cover_left_text_2", "cover_right_background_color", b"cover_right_background_color", "cover_right_icon", b"cover_right_icon", "cover_right_text", b"cover_right_text", "desc", b"desc", "like_button", b"like_button", "official_icon", b"official_icon", "rcmd_reason", b"rcmd_reason", "rcmd_reason_style", b"rcmd_reason_style", "rcmd_reason_style_v2", b"rcmd_reason_style_v2", "subtitle", b"subtitle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SmallCoverV2: _TypeAlias = SmallCoverV2  # noqa: Y015

@_typing.final
class SmallCoverV3(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    AVATAR_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_BUTTON_FIELD_NUMBER: _builtins.int
    RCMD_REASON_FIELD_NUMBER: _builtins.int
    DESC_FIELD_NUMBER: _builtins.int
    OFFICIAL_ICON_FIELD_NUMBER: _builtins.int
    CAN_PLAY_FIELD_NUMBER: _builtins.int
    RCMD_REASON_STYLE_FIELD_NUMBER: _builtins.int
    cover_left_text: _builtins.str
    """"""
    rcmd_reason: _builtins.str
    """"""
    desc: _builtins.str
    """"""
    official_icon: _builtins.int
    """"""
    can_play: _builtins.int
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    @_builtins.property
    def avatar(self) -> _common_pb2.Avatar:
        """"""

    @_builtins.property
    def cover_right_button(self) -> _common_pb2.Button:
        """"""

    @_builtins.property
    def rcmd_reason_style(self) -> _common_pb2.ReasonStyle:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        avatar: _common_pb2.Avatar | None = ...,
        cover_left_text: _builtins.str = ...,
        cover_right_button: _common_pb2.Button | None = ...,
        rcmd_reason: _builtins.str = ...,
        desc: _builtins.str = ...,
        official_icon: _builtins.int = ...,
        can_play: _builtins.int = ...,
        rcmd_reason_style: _common_pb2.ReasonStyle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["avatar", b"avatar", "base", b"base", "cover_right_button", b"cover_right_button", "rcmd_reason_style", b"rcmd_reason_style"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["avatar", b"avatar", "base", b"base", "can_play", b"can_play", "cover_left_text", b"cover_left_text", "cover_right_button", b"cover_right_button", "desc", b"desc", "official_icon", b"official_icon", "rcmd_reason", b"rcmd_reason", "rcmd_reason_style", b"rcmd_reason_style"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SmallCoverV3: _TypeAlias = SmallCoverV3  # noqa: Y015

@_typing.final
class MiddleCoverV2(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    RATIO_FIELD_NUMBER: _builtins.int
    DESC_FIELD_NUMBER: _builtins.int
    BADGE_FIELD_NUMBER: _builtins.int
    ratio: _builtins.int
    """"""
    desc: _builtins.str
    """"""
    badge: _builtins.str
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        ratio: _builtins.int = ...,
        desc: _builtins.str = ...,
        badge: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["base", b"base"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["badge", b"badge", "base", b"base", "desc", b"desc", "ratio", b"ratio"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MiddleCoverV2: _TypeAlias = MiddleCoverV2  # noqa: Y015

@_typing.final
class LargeCoverV2(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    AVATAR_FIELD_NUMBER: _builtins.int
    BADGE_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_BUTTON_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_2_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_2_FIELD_NUMBER: _builtins.int
    RCMD_REASON_FIELD_NUMBER: _builtins.int
    OFFICIAL_ICON_FIELD_NUMBER: _builtins.int
    CAN_PLAY_FIELD_NUMBER: _builtins.int
    RCMD_REASON_STYLE_FIELD_NUMBER: _builtins.int
    SHOW_TOP_FIELD_NUMBER: _builtins.int
    SHOW_BOTTOM_FIELD_NUMBER: _builtins.int
    badge: _builtins.str
    """"""
    cover_left_text_1: _builtins.str
    """"""
    cover_left_icon_1: _builtins.int
    """"""
    cover_left_text_2: _builtins.str
    """"""
    cover_left_icon_2: _builtins.int
    """"""
    rcmd_reason: _builtins.str
    """"""
    official_icon: _builtins.int
    """"""
    can_play: _builtins.int
    """"""
    show_top: _builtins.int
    """"""
    show_bottom: _builtins.int
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    @_builtins.property
    def avatar(self) -> _common_pb2.Avatar:
        """"""

    @_builtins.property
    def cover_right_button(self) -> _common_pb2.Button:
        """"""

    @_builtins.property
    def rcmd_reason_style(self) -> _common_pb2.ReasonStyle:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        avatar: _common_pb2.Avatar | None = ...,
        badge: _builtins.str = ...,
        cover_right_button: _common_pb2.Button | None = ...,
        cover_left_text_1: _builtins.str = ...,
        cover_left_icon_1: _builtins.int = ...,
        cover_left_text_2: _builtins.str = ...,
        cover_left_icon_2: _builtins.int = ...,
        rcmd_reason: _builtins.str = ...,
        official_icon: _builtins.int = ...,
        can_play: _builtins.int = ...,
        rcmd_reason_style: _common_pb2.ReasonStyle | None = ...,
        show_top: _builtins.int = ...,
        show_bottom: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["avatar", b"avatar", "base", b"base", "cover_right_button", b"cover_right_button", "rcmd_reason_style", b"rcmd_reason_style"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["avatar", b"avatar", "badge", b"badge", "base", b"base", "can_play", b"can_play", "cover_left_icon_1", b"cover_left_icon_1", "cover_left_icon_2", b"cover_left_icon_2", "cover_left_text_1", b"cover_left_text_1", "cover_left_text_2", b"cover_left_text_2", "cover_right_button", b"cover_right_button", "official_icon", b"official_icon", "rcmd_reason", b"rcmd_reason", "rcmd_reason_style", b"rcmd_reason_style", "show_bottom", b"show_bottom", "show_top", b"show_top"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LargeCoverV2: _TypeAlias = LargeCoverV2  # noqa: Y015

@_typing.final
class ThreeItemV2(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    TITLE_ICON_FIELD_NUMBER: _builtins.int
    MORE_URI_FIELD_NUMBER: _builtins.int
    MORE_TEXT_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    title_icon: _builtins.int
    """"""
    more_uri: _builtins.str
    """"""
    more_text: _builtins.str
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___ThreeItemV2Item]:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        title_icon: _builtins.int = ...,
        more_uri: _builtins.str = ...,
        more_text: _builtins.str = ...,
        items: _abc.Iterable[Global___ThreeItemV2Item] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["base", b"base"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["base", b"base", "items", b"items", "more_text", b"more_text", "more_uri", b"more_uri", "title_icon", b"title_icon"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ThreeItemV2: _TypeAlias = ThreeItemV2  # noqa: Y015

@_typing.final
class ThreeItemV2Item(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_FIELD_NUMBER: _builtins.int
    DESC_TEXT_1_FIELD_NUMBER: _builtins.int
    DESC_ICON_1_FIELD_NUMBER: _builtins.int
    DESC_TEXT_2_FIELD_NUMBER: _builtins.int
    DESC_ICON_2_FIELD_NUMBER: _builtins.int
    BADGE_FIELD_NUMBER: _builtins.int
    cover_left_icon: _builtins.int
    """"""
    desc_text_1: _builtins.str
    """"""
    desc_icon_1: _builtins.int
    """"""
    desc_text_2: _builtins.str
    """"""
    desc_icon_2: _builtins.int
    """"""
    badge: _builtins.str
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        cover_left_icon: _builtins.int = ...,
        desc_text_1: _builtins.str = ...,
        desc_icon_1: _builtins.int = ...,
        desc_text_2: _builtins.str = ...,
        desc_icon_2: _builtins.int = ...,
        badge: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["base", b"base"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["badge", b"badge", "base", b"base", "cover_left_icon", b"cover_left_icon", "desc_icon_1", b"desc_icon_1", "desc_icon_2", b"desc_icon_2", "desc_text_1", b"desc_text_1", "desc_text_2", b"desc_text_2"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ThreeItemV2Item: _TypeAlias = ThreeItemV2Item  # noqa: Y015

@_typing.final
class SmallCoverV4(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    COVER_BADGE_FIELD_NUMBER: _builtins.int
    DESC_FIELD_NUMBER: _builtins.int
    TITLE_RIGHT_TEXT_FIELD_NUMBER: _builtins.int
    TITLE_RIGHT_PIC_FIELD_NUMBER: _builtins.int
    cover_badge: _builtins.str
    """"""
    desc: _builtins.str
    """"""
    title_right_text: _builtins.str
    """"""
    title_right_pic: _builtins.int
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        cover_badge: _builtins.str = ...,
        desc: _builtins.str = ...,
        title_right_text: _builtins.str = ...,
        title_right_pic: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["base", b"base"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["base", b"base", "cover_badge", b"cover_badge", "desc", b"desc", "title_right_pic", b"title_right_pic", "title_right_text", b"title_right_text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SmallCoverV4: _TypeAlias = SmallCoverV4  # noqa: Y015

@_typing.final
class TwoItemV2(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___TwoItemV2Item]:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        items: _abc.Iterable[Global___TwoItemV2Item] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["base", b"base"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["base", b"base", "items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TwoItemV2: _TypeAlias = TwoItemV2  # noqa: Y015

@_typing.final
class TwoItemV2Item(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    BADGE_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_1_FIELD_NUMBER: _builtins.int
    badge: _builtins.str
    """"""
    cover_left_text_1: _builtins.str
    """"""
    cover_left_icon_1: _builtins.int
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        badge: _builtins.str = ...,
        cover_left_text_1: _builtins.str = ...,
        cover_left_icon_1: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["base", b"base"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["badge", b"badge", "base", b"base", "cover_left_icon_1", b"cover_left_icon_1", "cover_left_text_1", b"cover_left_text_1"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TwoItemV2Item: _TypeAlias = TwoItemV2Item  # noqa: Y015

@_typing.final
class MultiItem(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    MORE_URI_FIELD_NUMBER: _builtins.int
    MORE_TEXT_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    more_uri: _builtins.str
    """"""
    more_text: _builtins.str
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___DoubleCards]:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        more_uri: _builtins.str = ...,
        more_text: _builtins.str = ...,
        items: _abc.Iterable[Global___DoubleCards] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["base", b"base"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["base", b"base", "items", b"items", "more_text", b"more_text", "more_uri", b"more_uri"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MultiItem: _TypeAlias = MultiItem  # noqa: Y015

@_typing.final
class ThreePicV2(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    LEFT_COVER_FIELD_NUMBER: _builtins.int
    RIGHT_COVER_1_FIELD_NUMBER: _builtins.int
    RIGHT_COVER_2_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_2_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_2_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_TEXT_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_ICON_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_BACKGROUND_COLOR_FIELD_NUMBER: _builtins.int
    BADGE_FIELD_NUMBER: _builtins.int
    RCMD_REASON_FIELD_NUMBER: _builtins.int
    DESC_FIELD_NUMBER: _builtins.int
    AVATAR_FIELD_NUMBER: _builtins.int
    RCMD_REASON_STYLE_FIELD_NUMBER: _builtins.int
    left_cover: _builtins.str
    """"""
    right_cover_1: _builtins.str
    """"""
    right_cover_2: _builtins.str
    """"""
    cover_left_text_1: _builtins.str
    """"""
    cover_left_icon_1: _builtins.int
    """"""
    cover_left_text_2: _builtins.str
    """"""
    cover_left_icon_2: _builtins.int
    """"""
    cover_right_text: _builtins.str
    """"""
    cover_right_icon: _builtins.int
    """"""
    cover_right_background_color: _builtins.str
    """"""
    badge: _builtins.str
    """"""
    rcmd_reason: _builtins.str
    """"""
    desc: _builtins.str
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    @_builtins.property
    def avatar(self) -> _common_pb2.Avatar:
        """"""

    @_builtins.property
    def rcmd_reason_style(self) -> _common_pb2.ReasonStyle:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        left_cover: _builtins.str = ...,
        right_cover_1: _builtins.str = ...,
        right_cover_2: _builtins.str = ...,
        cover_left_text_1: _builtins.str = ...,
        cover_left_icon_1: _builtins.int = ...,
        cover_left_text_2: _builtins.str = ...,
        cover_left_icon_2: _builtins.int = ...,
        cover_right_text: _builtins.str = ...,
        cover_right_icon: _builtins.int = ...,
        cover_right_background_color: _builtins.str = ...,
        badge: _builtins.str = ...,
        rcmd_reason: _builtins.str = ...,
        desc: _builtins.str = ...,
        avatar: _common_pb2.Avatar | None = ...,
        rcmd_reason_style: _common_pb2.ReasonStyle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["avatar", b"avatar", "base", b"base", "rcmd_reason_style", b"rcmd_reason_style"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["avatar", b"avatar", "badge", b"badge", "base", b"base", "cover_left_icon_1", b"cover_left_icon_1", "cover_left_icon_2", b"cover_left_icon_2", "cover_left_text_1", b"cover_left_text_1", "cover_left_text_2", b"cover_left_text_2", "cover_right_background_color", b"cover_right_background_color", "cover_right_icon", b"cover_right_icon", "cover_right_text", b"cover_right_text", "desc", b"desc", "left_cover", b"left_cover", "rcmd_reason", b"rcmd_reason", "rcmd_reason_style", b"rcmd_reason_style", "right_cover_1", b"right_cover_1", "right_cover_2", b"right_cover_2"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ThreePicV2: _TypeAlias = ThreePicV2  # noqa: Y015

@_typing.final
class OnePicV2(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_2_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_TEXT_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_ICON_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_BACKGROUND_COLOR_FIELD_NUMBER: _builtins.int
    BADGE_FIELD_NUMBER: _builtins.int
    RCMD_REASON_FIELD_NUMBER: _builtins.int
    AVATAR_FIELD_NUMBER: _builtins.int
    RCMD_REASON_STYLE_FIELD_NUMBER: _builtins.int
    cover_left_icon_1: _builtins.int
    """"""
    cover_left_text_2: _builtins.str
    """"""
    cover_right_text: _builtins.str
    """"""
    cover_right_icon: _builtins.int
    """"""
    cover_right_background_color: _builtins.str
    """"""
    badge: _builtins.str
    """"""
    rcmd_reason: _builtins.str
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    @_builtins.property
    def avatar(self) -> _common_pb2.Avatar:
        """"""

    @_builtins.property
    def rcmd_reason_style(self) -> _common_pb2.ReasonStyle:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        cover_left_icon_1: _builtins.int = ...,
        cover_left_text_2: _builtins.str = ...,
        cover_right_text: _builtins.str = ...,
        cover_right_icon: _builtins.int = ...,
        cover_right_background_color: _builtins.str = ...,
        badge: _builtins.str = ...,
        rcmd_reason: _builtins.str = ...,
        avatar: _common_pb2.Avatar | None = ...,
        rcmd_reason_style: _common_pb2.ReasonStyle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["avatar", b"avatar", "base", b"base", "rcmd_reason_style", b"rcmd_reason_style"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["avatar", b"avatar", "badge", b"badge", "base", b"base", "cover_left_icon_1", b"cover_left_icon_1", "cover_left_text_2", b"cover_left_text_2", "cover_right_background_color", b"cover_right_background_color", "cover_right_icon", b"cover_right_icon", "cover_right_text", b"cover_right_text", "rcmd_reason", b"rcmd_reason", "rcmd_reason_style", b"rcmd_reason_style"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___OnePicV2: _TypeAlias = OnePicV2  # noqa: Y015

@_typing.final
class LargeCoverV3(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    COVER_GIF_FIELD_NUMBER: _builtins.int
    AVATAR_FIELD_NUMBER: _builtins.int
    TOP_RCMD_REASON_STYLE_FIELD_NUMBER: _builtins.int
    BOTTOM_RCMD_REASON_STYLE_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_2_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_2_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_TEXT_FIELD_NUMBER: _builtins.int
    DESC_FIELD_NUMBER: _builtins.int
    OFFICIAL_ICON_FIELD_NUMBER: _builtins.int
    cover_gif: _builtins.str
    """"""
    cover_left_text_1: _builtins.str
    """"""
    cover_left_icon_1: _builtins.int
    """"""
    cover_left_text_2: _builtins.str
    """"""
    cover_left_icon_2: _builtins.int
    """"""
    cover_right_text: _builtins.str
    """"""
    desc: _builtins.str
    """"""
    official_icon: _builtins.int
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    @_builtins.property
    def avatar(self) -> _common_pb2.Avatar:
        """"""

    @_builtins.property
    def top_rcmd_reason_style(self) -> _common_pb2.ReasonStyle:
        """"""

    @_builtins.property
    def bottom_rcmd_reason_style(self) -> _common_pb2.ReasonStyle:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        cover_gif: _builtins.str = ...,
        avatar: _common_pb2.Avatar | None = ...,
        top_rcmd_reason_style: _common_pb2.ReasonStyle | None = ...,
        bottom_rcmd_reason_style: _common_pb2.ReasonStyle | None = ...,
        cover_left_text_1: _builtins.str = ...,
        cover_left_icon_1: _builtins.int = ...,
        cover_left_text_2: _builtins.str = ...,
        cover_left_icon_2: _builtins.int = ...,
        cover_right_text: _builtins.str = ...,
        desc: _builtins.str = ...,
        official_icon: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["avatar", b"avatar", "base", b"base", "bottom_rcmd_reason_style", b"bottom_rcmd_reason_style", "top_rcmd_reason_style", b"top_rcmd_reason_style"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["avatar", b"avatar", "base", b"base", "bottom_rcmd_reason_style", b"bottom_rcmd_reason_style", "cover_gif", b"cover_gif", "cover_left_icon_1", b"cover_left_icon_1", "cover_left_icon_2", b"cover_left_icon_2", "cover_left_text_1", b"cover_left_text_1", "cover_left_text_2", b"cover_left_text_2", "cover_right_text", b"cover_right_text", "desc", b"desc", "official_icon", b"official_icon", "top_rcmd_reason_style", b"top_rcmd_reason_style"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LargeCoverV3: _TypeAlias = LargeCoverV3  # noqa: Y015

@_typing.final
class ThreePicV3(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    LEFT_COVER_FIELD_NUMBER: _builtins.int
    RIGHT_COVER_1_FIELD_NUMBER: _builtins.int
    RIGHT_COVER_2_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_2_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_2_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_TEXT_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_ICON_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_BACKGROUND_COLOR_FIELD_NUMBER: _builtins.int
    BADGE_FIELD_NUMBER: _builtins.int
    RCMD_REASON_STYLE_FIELD_NUMBER: _builtins.int
    left_cover: _builtins.str
    """"""
    right_cover_1: _builtins.str
    """"""
    right_cover_2: _builtins.str
    """"""
    cover_left_text_1: _builtins.str
    """"""
    cover_left_icon_1: _builtins.int
    """"""
    cover_left_text_2: _builtins.str
    """"""
    cover_left_icon_2: _builtins.int
    """"""
    cover_right_text: _builtins.str
    """"""
    cover_right_icon: _builtins.int
    """"""
    cover_right_background_color: _builtins.str
    """"""
    badge: _builtins.str
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    @_builtins.property
    def rcmd_reason_style(self) -> _common_pb2.ReasonStyle:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        left_cover: _builtins.str = ...,
        right_cover_1: _builtins.str = ...,
        right_cover_2: _builtins.str = ...,
        cover_left_text_1: _builtins.str = ...,
        cover_left_icon_1: _builtins.int = ...,
        cover_left_text_2: _builtins.str = ...,
        cover_left_icon_2: _builtins.int = ...,
        cover_right_text: _builtins.str = ...,
        cover_right_icon: _builtins.int = ...,
        cover_right_background_color: _builtins.str = ...,
        badge: _builtins.str = ...,
        rcmd_reason_style: _common_pb2.ReasonStyle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["base", b"base", "rcmd_reason_style", b"rcmd_reason_style"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["badge", b"badge", "base", b"base", "cover_left_icon_1", b"cover_left_icon_1", "cover_left_icon_2", b"cover_left_icon_2", "cover_left_text_1", b"cover_left_text_1", "cover_left_text_2", b"cover_left_text_2", "cover_right_background_color", b"cover_right_background_color", "cover_right_icon", b"cover_right_icon", "cover_right_text", b"cover_right_text", "left_cover", b"left_cover", "rcmd_reason_style", b"rcmd_reason_style", "right_cover_1", b"right_cover_1", "right_cover_2", b"right_cover_2"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ThreePicV3: _TypeAlias = ThreePicV3  # noqa: Y015

@_typing.final
class OnePicV3(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_1_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_TEXT_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_ICON_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_BACKGROUND_COLOR_FIELD_NUMBER: _builtins.int
    BADGE_FIELD_NUMBER: _builtins.int
    RCMD_REASON_STYLE_FIELD_NUMBER: _builtins.int
    cover_left_text_1: _builtins.str
    """"""
    cover_left_icon_1: _builtins.int
    """"""
    cover_right_text: _builtins.str
    """"""
    cover_right_icon: _builtins.int
    """"""
    cover_right_background_color: _builtins.str
    """"""
    badge: _builtins.str
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    @_builtins.property
    def rcmd_reason_style(self) -> _common_pb2.ReasonStyle:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        cover_left_text_1: _builtins.str = ...,
        cover_left_icon_1: _builtins.int = ...,
        cover_right_text: _builtins.str = ...,
        cover_right_icon: _builtins.int = ...,
        cover_right_background_color: _builtins.str = ...,
        badge: _builtins.str = ...,
        rcmd_reason_style: _common_pb2.ReasonStyle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["base", b"base", "rcmd_reason_style", b"rcmd_reason_style"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["badge", b"badge", "base", b"base", "cover_left_icon_1", b"cover_left_icon_1", "cover_left_text_1", b"cover_left_text_1", "cover_right_background_color", b"cover_right_background_color", "cover_right_icon", b"cover_right_icon", "cover_right_text", b"cover_right_text", "rcmd_reason_style", b"rcmd_reason_style"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___OnePicV3: _TypeAlias = OnePicV3  # noqa: Y015

@_typing.final
class SmallCoverV7(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    DESC_FIELD_NUMBER: _builtins.int
    desc: _builtins.str
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        desc: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["base", b"base"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["base", b"base", "desc", b"desc"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SmallCoverV7: _TypeAlias = SmallCoverV7  # noqa: Y015

@_typing.final
class SmallCoverV9(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_2_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_2_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_TEXT_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_ICON_FIELD_NUMBER: _builtins.int
    CAN_PLAY_FIELD_NUMBER: _builtins.int
    RCMD_REASON_STYLE_FIELD_NUMBER: _builtins.int
    UP_FIELD_NUMBER: _builtins.int
    LEFT_COVER_BADGE_STYLE_FIELD_NUMBER: _builtins.int
    LEFT_BOTTOM_RCMD_REASON_STYLE_FIELD_NUMBER: _builtins.int
    cover_left_text_1: _builtins.str
    """"""
    cover_left_icon_1: _builtins.int
    """"""
    cover_left_text_2: _builtins.str
    """"""
    cover_left_icon_2: _builtins.int
    """"""
    cover_right_text: _builtins.str
    """"""
    cover_right_icon: _builtins.int
    """"""
    can_play: _builtins.int
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    @_builtins.property
    def rcmd_reason_style(self) -> _common_pb2.ReasonStyle:
        """"""

    @_builtins.property
    def up(self) -> _common_pb2.Up:
        """"""

    @_builtins.property
    def left_cover_badge_style(self) -> _common_pb2.ReasonStyle:
        """"""

    @_builtins.property
    def left_bottom_rcmd_reason_style(self) -> _common_pb2.ReasonStyle:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        cover_left_text_1: _builtins.str = ...,
        cover_left_icon_1: _builtins.int = ...,
        cover_left_text_2: _builtins.str = ...,
        cover_left_icon_2: _builtins.int = ...,
        cover_right_text: _builtins.str = ...,
        cover_right_icon: _builtins.int = ...,
        can_play: _builtins.int = ...,
        rcmd_reason_style: _common_pb2.ReasonStyle | None = ...,
        up: _common_pb2.Up | None = ...,
        left_cover_badge_style: _common_pb2.ReasonStyle | None = ...,
        left_bottom_rcmd_reason_style: _common_pb2.ReasonStyle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["base", b"base", "left_bottom_rcmd_reason_style", b"left_bottom_rcmd_reason_style", "left_cover_badge_style", b"left_cover_badge_style", "rcmd_reason_style", b"rcmd_reason_style", "up", b"up"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["base", b"base", "can_play", b"can_play", "cover_left_icon_1", b"cover_left_icon_1", "cover_left_icon_2", b"cover_left_icon_2", "cover_left_text_1", b"cover_left_text_1", "cover_left_text_2", b"cover_left_text_2", "cover_right_icon", b"cover_right_icon", "cover_right_text", b"cover_right_text", "left_bottom_rcmd_reason_style", b"left_bottom_rcmd_reason_style", "left_cover_badge_style", b"left_cover_badge_style", "rcmd_reason_style", b"rcmd_reason_style", "up", b"up"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SmallCoverV9: _TypeAlias = SmallCoverV9  # noqa: Y015

@_typing.final
class SmallCoverConvergeV2(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_1_FIELD_NUMBER: _builtins.int
    COVER_LEFT_TEXT_2_FIELD_NUMBER: _builtins.int
    COVER_LEFT_ICON_2_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_TEXT_FIELD_NUMBER: _builtins.int
    COVER_RIGHT_TOP_TEXT_FIELD_NUMBER: _builtins.int
    RCMD_REASON_STYLE_FIELD_NUMBER: _builtins.int
    RCMD_REASON_STYLE_V2_FIELD_NUMBER: _builtins.int
    cover_left_text_1: _builtins.str
    """"""
    cover_left_icon_1: _builtins.int
    """"""
    cover_left_text_2: _builtins.str
    """"""
    cover_left_icon_2: _builtins.int
    """"""
    cover_right_text: _builtins.str
    """"""
    cover_right_top_text: _builtins.str
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    @_builtins.property
    def rcmd_reason_style(self) -> _common_pb2.ReasonStyle:
        """"""

    @_builtins.property
    def rcmd_reason_style_v2(self) -> _common_pb2.ReasonStyle:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        cover_left_text_1: _builtins.str = ...,
        cover_left_icon_1: _builtins.int = ...,
        cover_left_text_2: _builtins.str = ...,
        cover_left_icon_2: _builtins.int = ...,
        cover_right_text: _builtins.str = ...,
        cover_right_top_text: _builtins.str = ...,
        rcmd_reason_style: _common_pb2.ReasonStyle | None = ...,
        rcmd_reason_style_v2: _common_pb2.ReasonStyle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["base", b"base", "rcmd_reason_style", b"rcmd_reason_style", "rcmd_reason_style_v2", b"rcmd_reason_style_v2"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["base", b"base", "cover_left_icon_1", b"cover_left_icon_1", "cover_left_icon_2", b"cover_left_icon_2", "cover_left_text_1", b"cover_left_text_1", "cover_left_text_2", b"cover_left_text_2", "cover_right_text", b"cover_right_text", "cover_right_top_text", b"cover_right_top_text", "rcmd_reason_style", b"rcmd_reason_style", "rcmd_reason_style_v2", b"rcmd_reason_style_v2"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SmallCoverConvergeV2: _TypeAlias = SmallCoverConvergeV2  # noqa: Y015

@_typing.final
class SmallChannelSpecial(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BASE_FIELD_NUMBER: _builtins.int
    BG_COVER_FIELD_NUMBER: _builtins.int
    DESC_1_FIELD_NUMBER: _builtins.int
    DESC_2_FIELD_NUMBER: _builtins.int
    BADGE_FIELD_NUMBER: _builtins.int
    RCMD_REASON_STYLE_2_FIELD_NUMBER: _builtins.int
    bg_cover: _builtins.str
    """"""
    desc_1: _builtins.str
    """"""
    desc_2: _builtins.str
    """"""
    badge: _builtins.str
    """"""
    @_builtins.property
    def base(self) -> _common_pb2.Base:
        """"""

    @_builtins.property
    def rcmd_reason_style_2(self) -> _common_pb2.ReasonStyle:
        """"""

    def __init__(
        self,
        *,
        base: _common_pb2.Base | None = ...,
        bg_cover: _builtins.str = ...,
        desc_1: _builtins.str = ...,
        desc_2: _builtins.str = ...,
        badge: _builtins.str = ...,
        rcmd_reason_style_2: _common_pb2.ReasonStyle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["base", b"base", "rcmd_reason_style_2", b"rcmd_reason_style_2"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["badge", b"badge", "base", b"base", "bg_cover", b"bg_cover", "desc_1", b"desc_1", "desc_2", b"desc_2", "rcmd_reason_style_2", b"rcmd_reason_style_2"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SmallChannelSpecial: _TypeAlias = SmallChannelSpecial  # noqa: Y015
