"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class BanUser(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    UID_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    TIME_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    uid: _builtins.int
    """用户mid"""
    limit: _builtins.int
    """封禁业务"""
    time: _builtins.int
    """封禁时间"""
    mode: _builtins.int
    """模式
    1:add 2:remove
    """
    def __init__(
        self,
        *,
        uid: _builtins.int = ...,
        limit: _builtins.int = ...,
        time: _builtins.int = ...,
        mode: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["limit", b"limit", "mode", b"mode", "time", b"time", "uid", b"uid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BanUser: _TypeAlias = BanUser  # noqa: Y015

@_typing.final
class ReqOpBlacklist(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    BAN_USERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ban_users(self) -> _containers.RepeatedCompositeFieldContainer[Global___BanUser]:
        """需要封禁/解封的用户信息"""

    def __init__(
        self,
        *,
        ban_users: _abc.Iterable[Global___BanUser] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ban_users", b"ban_users"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqOpBlacklist: _TypeAlias = ReqOpBlacklist  # noqa: Y015

@_typing.final
class RspOpBlacklist(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    FAILED_USERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def failed_users(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """"""

    def __init__(
        self,
        *,
        failed_users: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failed_users", b"failed_users"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspOpBlacklist: _TypeAlias = RspOpBlacklist  # noqa: Y015
