"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GenWebTicketRequest(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ContextEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CONTEXT_FIELD_NUMBER: _builtins.int
    KEY_ID_FIELD_NUMBER: _builtins.int
    HEXSIGN_FIELD_NUMBER: _builtins.int
    TOKEN_FIELD_NUMBER: _builtins.int
    key_id: _builtins.str
    """"""
    hexsign: _builtins.str
    """"""
    token: _builtins.str
    """"""
    @_builtins.property
    def context(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """"""

    def __init__(
        self,
        *,
        context: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        key_id: _builtins.str = ...,
        hexsign: _builtins.str = ...,
        token: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "hexsign", b"hexsign", "key_id", b"key_id", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GenWebTicketRequest: _TypeAlias = GenWebTicketRequest  # noqa: Y015

@_typing.final
class GenWebTicketResponse(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Context(_message.Message):
        """"""

        DESCRIPTOR: _descriptor.Descriptor

        V_VOUCHER_FIELD_NUMBER: _builtins.int
        v_voucher: _builtins.str
        """"""
        def __init__(
            self,
            *,
            v_voucher: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["v_voucher", b"v_voucher"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class Nav(_message.Message):
        """"""

        DESCRIPTOR: _descriptor.Descriptor

        IMG_FIELD_NUMBER: _builtins.int
        SUB_FIELD_NUMBER: _builtins.int
        img: _builtins.str
        """"""
        sub: _builtins.str
        """"""
        def __init__(
            self,
            *,
            img: _builtins.str = ...,
            sub: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["img", b"img", "sub", b"sub"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TICKET_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    TTL_FIELD_NUMBER: _builtins.int
    CONTEXT_FIELD_NUMBER: _builtins.int
    NAV_FIELD_NUMBER: _builtins.int
    ticket: _builtins.str
    """"""
    created_at: _builtins.int
    """"""
    ttl: _builtins.int
    """"""
    @_builtins.property
    def context(self) -> Global___GenWebTicketResponse.Context:
        """"""

    @_builtins.property
    def nav(self) -> Global___GenWebTicketResponse.Nav:
        """"""

    def __init__(
        self,
        *,
        ticket: _builtins.str = ...,
        created_at: _builtins.int = ...,
        ttl: _builtins.int = ...,
        context: Global___GenWebTicketResponse.Context | None = ...,
        nav: Global___GenWebTicketResponse.Nav | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "nav", b"nav"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "created_at", b"created_at", "nav", b"nav", "ticket", b"ticket", "ttl", b"ttl"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GenWebTicketResponse: _TypeAlias = GenWebTicketResponse  # noqa: Y015

@_typing.final
class GetTicketRequest(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ContextEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.bytes
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.bytes = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CONTEXT_FIELD_NUMBER: _builtins.int
    KEY_ID_FIELD_NUMBER: _builtins.int
    SIGN_FIELD_NUMBER: _builtins.int
    TOKEN_FIELD_NUMBER: _builtins.int
    key_id: _builtins.str
    """暂时固定为 ec01"""
    sign: _builtins.bytes
    """"""
    token: _builtins.str
    """暂时留空"""
    @_builtins.property
    def context(self) -> _containers.ScalarMap[_builtins.str, _builtins.bytes]:
        """包含: 
        + x-fingerprint(包含手机各类信息, 使用 datacenter.hakase.protobuf.AndroidDeviceInfo 生成)
        + x-exbadbasket(?)
        """

    def __init__(
        self,
        *,
        context: _abc.Mapping[_builtins.str, _builtins.bytes] | None = ...,
        key_id: _builtins.str = ...,
        sign: _builtins.bytes = ...,
        token: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "key_id", b"key_id", "sign", b"sign", "token", b"token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTicketRequest: _TypeAlias = GetTicketRequest  # noqa: Y015

@_typing.final
class GetTicketResponse(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Context(_message.Message):
        """"""

        DESCRIPTOR: _descriptor.Descriptor

        V_VOUCHER_FIELD_NUMBER: _builtins.int
        v_voucher: _builtins.str
        """"""
        def __init__(
            self,
            *,
            v_voucher: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["v_voucher", b"v_voucher"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TICKET_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    TTL_FIELD_NUMBER: _builtins.int
    CONTEXT_FIELD_NUMBER: _builtins.int
    ticket: _builtins.str
    """x-bili-ticket"""
    created_at: _builtins.int
    """有效期起"""
    ttl: _builtins.int
    """有效期"""
    @_builtins.property
    def context(self) -> Global___GetTicketResponse.Context:
        """"""

    def __init__(
        self,
        *,
        ticket: _builtins.str = ...,
        created_at: _builtins.int = ...,
        ttl: _builtins.int = ...,
        context: Global___GetTicketResponse.Context | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["context", b"context"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["context", b"context", "created_at", b"created_at", "ticket", b"ticket", "ttl", b"ttl"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTicketResponse: _TypeAlias = GetTicketResponse  # noqa: Y015
