# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bilibili/dynamic/interfaces/campus/v1/api.proto
# Protobuf Python Version: 7.34.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    2,
    '',
    'bilibili/dynamic/interfaces/campus/v1/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/bilibili/dynamic/interfaces/campus/v1/api.proto\x12%bilibili.dynamic.interfaces.campus.v1\"\x13\n\x11\x41\x63tionReportReply\"y\n\x0f\x41\x63tionReportReq\x12\x10\n\x08identity\x18\x01 \x01(\t\x12\x41\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x31.bilibili.dynamic.interfaces.campus.v1.ActionType\x12\x11\n\tcampus_id\x18\x03 \x01(\x03*=\n\nActionType\x12\x12\n\x0e\x41\x43TION_NOTHING\x10\x00\x12\x1b\n\x17\x41\x43TION_CLOSE_YELLOW_BAR\x10\x01\x32\x8b\x01\n\x06\x43\x61mpus\x12\x80\x01\n\x0c\x41\x63tionReport\x12\x36.bilibili.dynamic.interfaces.campus.v1.ActionReportReq\x1a\x38.bilibili.dynamic.interfaces.campus.v1.ActionReportReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bilibili.dynamic.interfaces.campus.v1.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIONTYPE']._serialized_start=234
  _globals['_ACTIONTYPE']._serialized_end=295
  _globals['_ACTIONREPORTREPLY']._serialized_start=90
  _globals['_ACTIONREPORTREPLY']._serialized_end=109
  _globals['_ACTIONREPORTREQ']._serialized_start=111
  _globals['_ACTIONREPORTREQ']._serialized_end=232
  _globals['_CAMPUS']._serialized_start=298
  _globals['_CAMPUS']._serialized_end=437
# @@protoc_insertion_point(module_scope)
