"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ActionType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ActionTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ActionType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ACTION_NOTHING: _ActionType.ValueType  # 0
    ACTION_CLOSE_YELLOW_BAR: _ActionType.ValueType  # 1

class ActionType(_ActionType, metaclass=_ActionTypeEnumTypeWrapper):
    """"""

ACTION_NOTHING: ActionType.ValueType  # 0
ACTION_CLOSE_YELLOW_BAR: ActionType.ValueType  # 1
Global___ActionType: _TypeAlias = ActionType  # noqa: Y015

@_typing.final
class ActionReportReply(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ActionReportReply: _TypeAlias = ActionReportReply  # noqa: Y015

@_typing.final
class ActionReportReq(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    IDENTITY_FIELD_NUMBER: _builtins.int
    ACTION_FIELD_NUMBER: _builtins.int
    CAMPUS_ID_FIELD_NUMBER: _builtins.int
    identity: _builtins.str
    """"""
    action: Global___ActionType.ValueType
    """"""
    campus_id: _builtins.int
    """"""
    def __init__(
        self,
        *,
        identity: _builtins.str = ...,
        action: Global___ActionType.ValueType = ...,
        campus_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "campus_id", b"campus_id", "identity", b"identity"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ActionReportReq: _TypeAlias = ActionReportReq  # noqa: Y015
