"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from bilibili.im.type import im_pb2 as _im_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ENUM_FOLD:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ENUM_FOLDEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ENUM_FOLD.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    FOLD_NO: _ENUM_FOLD.ValueType  # 0
    """"""
    FOLD_YES: _ENUM_FOLD.ValueType  # 1
    """"""
    FOLD_UNKNOWN: _ENUM_FOLD.ValueType  # 2
    """"""

class ENUM_FOLD(_ENUM_FOLD, metaclass=_ENUM_FOLDEnumTypeWrapper):
    """"""

FOLD_NO: ENUM_FOLD.ValueType  # 0
""""""
FOLD_YES: ENUM_FOLD.ValueType  # 1
""""""
FOLD_UNKNOWN: ENUM_FOLD.ValueType  # 2
""""""
Global___ENUM_FOLD: _TypeAlias = ENUM_FOLD  # noqa: Y015

class _ENUM_UNREAD_TYPE:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ENUM_UNREAD_TYPEEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ENUM_UNREAD_TYPE.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UNREAD_TYPE_ALL: _ENUM_UNREAD_TYPE.ValueType  # 0
    """"""
    UNREAD_TYPE_FOLLOW: _ENUM_UNREAD_TYPE.ValueType  # 1
    """"""
    UNREAD_TYPE_UNFOLLOW: _ENUM_UNREAD_TYPE.ValueType  # 2
    """"""
    UNREAD_TYPE_DUSTBIN: _ENUM_UNREAD_TYPE.ValueType  # 3
    """"""

class ENUM_UNREAD_TYPE(_ENUM_UNREAD_TYPE, metaclass=_ENUM_UNREAD_TYPEEnumTypeWrapper):
    """"""

UNREAD_TYPE_ALL: ENUM_UNREAD_TYPE.ValueType  # 0
""""""
UNREAD_TYPE_FOLLOW: ENUM_UNREAD_TYPE.ValueType  # 1
""""""
UNREAD_TYPE_UNFOLLOW: ENUM_UNREAD_TYPE.ValueType  # 2
""""""
UNREAD_TYPE_DUSTBIN: ENUM_UNREAD_TYPE.ValueType  # 3
""""""
Global___ENUM_UNREAD_TYPE: _TypeAlias = ENUM_UNREAD_TYPE  # noqa: Y015

class _SESSION_TYPE:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SESSION_TYPEEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SESSION_TYPE.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UNKNOWN: _SESSION_TYPE.ValueType  # 0
    """"""
    UN_FOLD_SESSION: _SESSION_TYPE.ValueType  # 1
    """"""
    UN_FOLLOW_SINGLE_SESSION: _SESSION_TYPE.ValueType  # 2
    """"""
    MY_GROUP_SESSION: _SESSION_TYPE.ValueType  # 3
    """"""
    ALL_SESSION: _SESSION_TYPE.ValueType  # 4
    """"""
    DUSTBIN_SESSION: _SESSION_TYPE.ValueType  # 5
    """"""

class SESSION_TYPE(_SESSION_TYPE, metaclass=_SESSION_TYPEEnumTypeWrapper):
    """"""

UNKNOWN: SESSION_TYPE.ValueType  # 0
""""""
UN_FOLD_SESSION: SESSION_TYPE.ValueType  # 1
""""""
UN_FOLLOW_SINGLE_SESSION: SESSION_TYPE.ValueType  # 2
""""""
MY_GROUP_SESSION: SESSION_TYPE.ValueType  # 3
""""""
ALL_SESSION: SESSION_TYPE.ValueType  # 4
""""""
DUSTBIN_SESSION: SESSION_TYPE.ValueType  # 5
""""""
Global___SESSION_TYPE: _TypeAlias = SESSION_TYPE  # noqa: Y015

@_typing.final
class DummyReq(_message.Message):
    """空请求"""

    DESCRIPTOR: _descriptor.Descriptor

    IDL_FIELD_NUMBER: _builtins.int
    idl: _builtins.int
    """"""
    def __init__(
        self,
        *,
        idl: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["idl", b"idl"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DummyReq: _TypeAlias = DummyReq  # noqa: Y015

@_typing.final
class DummyRsp(_message.Message):
    """空响应"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DummyRsp: _TypeAlias = DummyRsp  # noqa: Y015

@_typing.final
class EmotionInfo(_message.Message):
    """表情资源信息"""

    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    GIF_URL_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    """表情"""
    url: _builtins.str
    """表情url"""
    size: _builtins.int
    """表情大小
    0:未知 1:min 2:max
    """
    gif_url: _builtins.str
    """gif url"""
    def __init__(
        self,
        *,
        text: _builtins.str = ...,
        url: _builtins.str = ...,
        size: _builtins.int = ...,
        gif_url: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gif_url", b"gif_url", "size", b"size", "text", b"text", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EmotionInfo: _TypeAlias = EmotionInfo  # noqa: Y015

@_typing.final
class MsgDetail(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    MSG_KEY_FIELD_NUMBER: _builtins.int
    SEQNO_FIELD_NUMBER: _builtins.int
    msg_key: _builtins.int
    """"""
    seqno: _builtins.int
    """"""
    def __init__(
        self,
        *,
        msg_key: _builtins.int = ...,
        seqno: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["msg_key", b"msg_key", "seqno", b"seqno"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MsgDetail: _TypeAlias = MsgDetail  # noqa: Y015

@_typing.final
class MsgFeedUnreadRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class UnreadEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.int
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    UNREAD_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def unread(self) -> _containers.ScalarMap[_builtins.str, _builtins.int]:
        """"""

    def __init__(
        self,
        *,
        unread: _abc.Mapping[_builtins.str, _builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["unread", b"unread"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MsgFeedUnreadRsp: _TypeAlias = MsgFeedUnreadRsp  # noqa: Y015

@_typing.final
class ReqAckAssisMsg(_message.Message):
    """更新应援团小助手消息已拉取进度-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    ACK_SEQNO_FIELD_NUMBER: _builtins.int
    ack_seqno: _builtins.int
    """"""
    def __init__(
        self,
        *,
        ack_seqno: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ack_seqno", b"ack_seqno"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqAckAssisMsg: _TypeAlias = ReqAckAssisMsg  # noqa: Y015

@_typing.final
class ReqAckSessions(_message.Message):
    """拉取已读消息-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    BEGIN_TS_FIELD_NUMBER: _builtins.int
    END_TS_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    begin_ts: _builtins.int
    """"""
    end_ts: _builtins.int
    """"""
    size: _builtins.int
    """"""
    def __init__(
        self,
        *,
        begin_ts: _builtins.int = ...,
        end_ts: _builtins.int = ...,
        size: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["begin_ts", b"begin_ts", "end_ts", b"end_ts", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqAckSessions: _TypeAlias = ReqAckSessions  # noqa: Y015

@_typing.final
class ReqBatRmSess(_message.Message):
    """批量删除会话-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqBatRmSess: _TypeAlias = ReqBatRmSess  # noqa: Y015

@_typing.final
class ReqCloseClearUnreadUI(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqCloseClearUnreadUI: _TypeAlias = ReqCloseClearUnreadUI  # noqa: Y015

@_typing.final
class ReqGetMsg(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TALKER_ID_FIELD_NUMBER: _builtins.int
    SESSION_TYPE_FIELD_NUMBER: _builtins.int
    MSG_DETAIL_FIELD_NUMBER: _builtins.int
    talker_id: _builtins.int
    """"""
    session_type: _builtins.int
    """"""
    @_builtins.property
    def msg_detail(self) -> _containers.RepeatedCompositeFieldContainer[Global___MsgDetail]:
        """"""

    def __init__(
        self,
        *,
        talker_id: _builtins.int = ...,
        session_type: _builtins.int = ...,
        msg_detail: _abc.Iterable[Global___MsgDetail] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["msg_detail", b"msg_detail", "session_type", b"session_type", "talker_id", b"talker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqGetMsg: _TypeAlias = ReqGetMsg  # noqa: Y015

@_typing.final
class ReqGetSessions(_message.Message):
    """拉取会话记录列表-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    BEGIN_TS_FIELD_NUMBER: _builtins.int
    END_TS_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    SESSION_TYPE_FIELD_NUMBER: _builtins.int
    UNFOLLOW_FOLD_FIELD_NUMBER: _builtins.int
    GROUP_FOLD_FIELD_NUMBER: _builtins.int
    SORT_RULE_FIELD_NUMBER: _builtins.int
    TEENAGER_MODE_FIELD_NUMBER: _builtins.int
    LESSONS_MODE_FIELD_NUMBER: _builtins.int
    begin_ts: _builtins.int
    """"""
    end_ts: _builtins.int
    """"""
    size: _builtins.int
    """"""
    session_type: _builtins.int
    """"""
    unfollow_fold: _builtins.int
    """"""
    group_fold: _builtins.int
    """"""
    sort_rule: _builtins.int
    """"""
    teenager_mode: _builtins.int
    """青少年模式"""
    lessons_mode: _builtins.int
    """课堂模式"""
    def __init__(
        self,
        *,
        begin_ts: _builtins.int = ...,
        end_ts: _builtins.int = ...,
        size: _builtins.int = ...,
        session_type: _builtins.int = ...,
        unfollow_fold: _builtins.int = ...,
        group_fold: _builtins.int = ...,
        sort_rule: _builtins.int = ...,
        teenager_mode: _builtins.int = ...,
        lessons_mode: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["begin_ts", b"begin_ts", "end_ts", b"end_ts", "group_fold", b"group_fold", "lessons_mode", b"lessons_mode", "session_type", b"session_type", "size", b"size", "sort_rule", b"sort_rule", "teenager_mode", b"teenager_mode", "unfollow_fold", b"unfollow_fold"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqGetSessions: _TypeAlias = ReqGetSessions  # noqa: Y015

@_typing.final
class ReqGetSpecificSessions(_message.Message):
    """-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    TALKER_SESSIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def talker_sessions(self) -> _containers.RepeatedCompositeFieldContainer[Global___SimpleSession]:
        """具体会话详情"""

    def __init__(
        self,
        *,
        talker_sessions: _abc.Iterable[Global___SimpleSession] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["talker_sessions", b"talker_sessions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqGetSpecificSessions: _TypeAlias = ReqGetSpecificSessions  # noqa: Y015

@_typing.final
class ReqGroupAssisMsg(_message.Message):
    """应援团消息助手-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_SEQNO_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    client_seqno: _builtins.int
    """"""
    size: _builtins.int
    """"""
    def __init__(
        self,
        *,
        client_seqno: _builtins.int = ...,
        size: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_seqno", b"client_seqno", "size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqGroupAssisMsg: _TypeAlias = ReqGroupAssisMsg  # noqa: Y015

@_typing.final
class ReqLiveInfo(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    UID_FIELD_NUMBER: _builtins.int
    TALKER_ID_FIELD_NUMBER: _builtins.int
    uid: _builtins.int
    """"""
    talker_id: _builtins.int
    """"""
    def __init__(
        self,
        *,
        uid: _builtins.int = ...,
        talker_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["talker_id", b"talker_id", "uid", b"uid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqLiveInfo: _TypeAlias = ReqLiveInfo  # noqa: Y015

@_typing.final
class ReqNewSessions(_message.Message):
    """拉取新消息-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    BEGIN_TS_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    TEENAGER_MODE_FIELD_NUMBER: _builtins.int
    LESSONS_MODE_FIELD_NUMBER: _builtins.int
    begin_ts: _builtins.int
    """"""
    size: _builtins.int
    """"""
    teenager_mode: _builtins.int
    """"""
    lessons_mode: _builtins.int
    """课堂模式"""
    def __init__(
        self,
        *,
        begin_ts: _builtins.int = ...,
        size: _builtins.int = ...,
        teenager_mode: _builtins.int = ...,
        lessons_mode: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["begin_ts", b"begin_ts", "lessons_mode", b"lessons_mode", "size", b"size", "teenager_mode", b"teenager_mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqNewSessions: _TypeAlias = ReqNewSessions  # noqa: Y015

@_typing.final
class ReqRelationSync(_message.Message):
    """同步关系-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_RELATION_OPLOG_SEQNO_FIELD_NUMBER: _builtins.int
    client_relation_oplog_seqno: _builtins.int
    """客户端当前seqno"""
    def __init__(
        self,
        *,
        client_relation_oplog_seqno: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_relation_oplog_seqno", b"client_relation_oplog_seqno"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqRelationSync: _TypeAlias = ReqRelationSync  # noqa: Y015

@_typing.final
class ReqRemoveSession(_message.Message):
    """删除会话记录-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    TALKER_ID_FIELD_NUMBER: _builtins.int
    SESSION_TYPE_FIELD_NUMBER: _builtins.int
    talker_id: _builtins.int
    """"""
    session_type: _builtins.int
    """"""
    def __init__(
        self,
        *,
        talker_id: _builtins.int = ...,
        session_type: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["session_type", b"session_type", "talker_id", b"talker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqRemoveSession: _TypeAlias = ReqRemoveSession  # noqa: Y015

@_typing.final
class ReqSendMsg(_message.Message):
    """发送消息-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    MSG_FIELD_NUMBER: _builtins.int
    COOKIE_FIELD_NUMBER: _builtins.int
    COOKIE2_FIELD_NUMBER: _builtins.int
    ERROR_CODE_FIELD_NUMBER: _builtins.int
    DEV_ID_FIELD_NUMBER: _builtins.int
    cookie: _builtins.str
    """"""
    cookie2: _builtins.str
    """"""
    error_code: _builtins.int
    """"""
    dev_id: _builtins.str
    """"""
    @_builtins.property
    def msg(self) -> _im_pb2.Msg:
        """消息内容"""

    def __init__(
        self,
        *,
        msg: _im_pb2.Msg | None = ...,
        cookie: _builtins.str = ...,
        cookie2: _builtins.str = ...,
        error_code: _builtins.int = ...,
        dev_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["msg", b"msg"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cookie", b"cookie", "cookie2", b"cookie2", "dev_id", b"dev_id", "error_code", b"error_code", "msg", b"msg"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqSendMsg: _TypeAlias = ReqSendMsg  # noqa: Y015

@_typing.final
class ReqSessionDetail(_message.Message):
    """拉取会话详情-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    TALKER_ID_FIELD_NUMBER: _builtins.int
    SESSION_TYPE_FIELD_NUMBER: _builtins.int
    UID_FIELD_NUMBER: _builtins.int
    talker_id: _builtins.int
    """"""
    session_type: _builtins.int
    """"""
    uid: _builtins.int
    """"""
    def __init__(
        self,
        *,
        talker_id: _builtins.int = ...,
        session_type: _builtins.int = ...,
        uid: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["session_type", b"session_type", "talker_id", b"talker_id", "uid", b"uid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqSessionDetail: _TypeAlias = ReqSessionDetail  # noqa: Y015

@_typing.final
class ReqSessionDetails(_message.Message):
    """批量拉取会话详情-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    SESS_IDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def sess_ids(self) -> _containers.RepeatedCompositeFieldContainer[Global___ReqSessionDetail]:
        """会话详情请求列表"""

    def __init__(
        self,
        *,
        sess_ids: _abc.Iterable[Global___ReqSessionDetail] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sess_ids", b"sess_ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqSessionDetails: _TypeAlias = ReqSessionDetails  # noqa: Y015

@_typing.final
class ReqSessionMsg(_message.Message):
    """同步版本拉取消息-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    TALKER_ID_FIELD_NUMBER: _builtins.int
    SESSION_TYPE_FIELD_NUMBER: _builtins.int
    END_SEQNO_FIELD_NUMBER: _builtins.int
    BEGIN_SEQNO_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    ORDER_FIELD_NUMBER: _builtins.int
    DEV_ID_FIELD_NUMBER: _builtins.int
    talker_id: _builtins.int
    """"""
    session_type: _builtins.int
    """"""
    end_seqno: _builtins.int
    """"""
    begin_seqno: _builtins.int
    """"""
    size: _builtins.int
    """"""
    order: _builtins.int
    """"""
    dev_id: _builtins.str
    """"""
    def __init__(
        self,
        *,
        talker_id: _builtins.int = ...,
        session_type: _builtins.int = ...,
        end_seqno: _builtins.int = ...,
        begin_seqno: _builtins.int = ...,
        size: _builtins.int = ...,
        order: _builtins.int = ...,
        dev_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["begin_seqno", b"begin_seqno", "dev_id", b"dev_id", "end_seqno", b"end_seqno", "order", b"order", "session_type", b"session_type", "size", b"size", "talker_id", b"talker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqSessionMsg: _TypeAlias = ReqSessionMsg  # noqa: Y015

@_typing.final
class ReqSetTop(_message.Message):
    """置顶聊天-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    TALKER_ID_FIELD_NUMBER: _builtins.int
    SESSION_TYPE_FIELD_NUMBER: _builtins.int
    OP_TYPE_FIELD_NUMBER: _builtins.int
    talker_id: _builtins.int
    """"""
    session_type: _builtins.int
    """"""
    op_type: _builtins.int
    """
    0:置顶 1:取消置顶
    """
    def __init__(
        self,
        *,
        talker_id: _builtins.int = ...,
        session_type: _builtins.int = ...,
        op_type: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["op_type", b"op_type", "session_type", b"session_type", "talker_id", b"talker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqSetTop: _TypeAlias = ReqSetTop  # noqa: Y015

@_typing.final
class ReqShareList(_message.Message):
    """拉取最近私信分享列表-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    SIZE_FIELD_NUMBER: _builtins.int
    size: _builtins.int
    """分页大小 最大20"""
    def __init__(
        self,
        *,
        size: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["size", b"size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqShareList: _TypeAlias = ReqShareList  # noqa: Y015

@_typing.final
class ReqShowClearUnreadUI(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    UNREAD_TYPE_FIELD_NUMBER: _builtins.int
    SHOW_UNFOLLOW_LIST_FIELD_NUMBER: _builtins.int
    SHOW_DUSTBIN_FIELD_NUMBER: _builtins.int
    unread_type: _builtins.int
    """"""
    show_unfollow_list: _builtins.int
    """"""
    show_dustbin: _builtins.int
    """"""
    def __init__(
        self,
        *,
        unread_type: _builtins.int = ...,
        show_unfollow_list: _builtins.int = ...,
        show_dustbin: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["show_dustbin", b"show_dustbin", "show_unfollow_list", b"show_unfollow_list", "unread_type", b"unread_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqShowClearUnreadUI: _TypeAlias = ReqShowClearUnreadUI  # noqa: Y015

@_typing.final
class ReqSingleUnread(_message.Message):
    """未读私信数-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    UNREAD_TYPE_FIELD_NUMBER: _builtins.int
    SHOW_UNFOLLOW_LIST_FIELD_NUMBER: _builtins.int
    UID_FIELD_NUMBER: _builtins.int
    SHOW_DUSTBIN_FIELD_NUMBER: _builtins.int
    unread_type: _builtins.int
    """"""
    show_unfollow_list: _builtins.int
    """"""
    uid: _builtins.int
    """"""
    show_dustbin: _builtins.int
    """"""
    def __init__(
        self,
        *,
        unread_type: _builtins.int = ...,
        show_unfollow_list: _builtins.int = ...,
        uid: _builtins.int = ...,
        show_dustbin: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["show_dustbin", b"show_dustbin", "show_unfollow_list", b"show_unfollow_list", "uid", b"uid", "unread_type", b"unread_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqSingleUnread: _TypeAlias = ReqSingleUnread  # noqa: Y015

@_typing.final
class ReqSpecificSingleUnread(_message.Message):
    """-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    TALKER_SESSIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def talker_sessions(self) -> _containers.RepeatedCompositeFieldContainer[Global___SimpleSession]:
        """具体会话详情"""

    def __init__(
        self,
        *,
        talker_sessions: _abc.Iterable[Global___SimpleSession] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["talker_sessions", b"talker_sessions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqSpecificSingleUnread: _TypeAlias = ReqSpecificSingleUnread  # noqa: Y015

@_typing.final
class ReqSyncAck(_message.Message):
    """确认同步进度-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_SEQNO_FIELD_NUMBER: _builtins.int
    client_seqno: _builtins.int
    """"""
    def __init__(
        self,
        *,
        client_seqno: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_seqno", b"client_seqno"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqSyncAck: _TypeAlias = ReqSyncAck  # noqa: Y015

@_typing.final
class ReqTotalUnread(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    UNREAD_TYPE_FIELD_NUMBER: _builtins.int
    SHOW_UNFOLLOW_LIST_FIELD_NUMBER: _builtins.int
    UID_FIELD_NUMBER: _builtins.int
    SHOW_DUSTBIN_FIELD_NUMBER: _builtins.int
    SINGLEUNREAD_ON_FIELD_NUMBER: _builtins.int
    MSGFEED_ON_FIELD_NUMBER: _builtins.int
    SYSUP_ON_FIELD_NUMBER: _builtins.int
    unread_type: _builtins.int
    """"""
    show_unfollow_list: _builtins.int
    """"""
    uid: _builtins.int
    """"""
    show_dustbin: _builtins.int
    """"""
    singleunread_on: _builtins.int
    """"""
    msgfeed_on: _builtins.int
    """"""
    sysup_on: _builtins.int
    """"""
    def __init__(
        self,
        *,
        unread_type: _builtins.int = ...,
        show_unfollow_list: _builtins.int = ...,
        uid: _builtins.int = ...,
        show_dustbin: _builtins.int = ...,
        singleunread_on: _builtins.int = ...,
        msgfeed_on: _builtins.int = ...,
        sysup_on: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["msgfeed_on", b"msgfeed_on", "show_dustbin", b"show_dustbin", "show_unfollow_list", b"show_unfollow_list", "singleunread_on", b"singleunread_on", "sysup_on", b"sysup_on", "uid", b"uid", "unread_type", b"unread_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqTotalUnread: _TypeAlias = ReqTotalUnread  # noqa: Y015

@_typing.final
class ReqUpdateAck(_message.Message):
    """更新已读进度-请求"""

    DESCRIPTOR: _descriptor.Descriptor

    TALKER_ID_FIELD_NUMBER: _builtins.int
    SESSION_TYPE_FIELD_NUMBER: _builtins.int
    ACK_SEQNO_FIELD_NUMBER: _builtins.int
    talker_id: _builtins.int
    """聊天对象uid，可以为用户id或者为群id"""
    session_type: _builtins.int
    """会话类型"""
    ack_seqno: _builtins.int
    """已读的最大seqno"""
    def __init__(
        self,
        *,
        talker_id: _builtins.int = ...,
        session_type: _builtins.int = ...,
        ack_seqno: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ack_seqno", b"ack_seqno", "session_type", b"session_type", "talker_id", b"talker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqUpdateAck: _TypeAlias = ReqUpdateAck  # noqa: Y015

@_typing.final
class ReqUpdateIntercept(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    UID_FIELD_NUMBER: _builtins.int
    TALKER_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    uid: _builtins.int
    """"""
    talker_id: _builtins.int
    """"""
    status: _builtins.int
    """"""
    def __init__(
        self,
        *,
        uid: _builtins.int = ...,
        talker_id: _builtins.int = ...,
        status: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status", "talker_id", b"talker_id", "uid", b"uid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqUpdateIntercept: _TypeAlias = ReqUpdateIntercept  # noqa: Y015

@_typing.final
class ReqUpdateTotalUnread(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReqUpdateTotalUnread: _TypeAlias = ReqUpdateTotalUnread  # noqa: Y015

@_typing.final
class RspCloseClearUnreadUI(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspCloseClearUnreadUI: _TypeAlias = RspCloseClearUnreadUI  # noqa: Y015

@_typing.final
class RspGetMsg(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    MSG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def msg(self) -> _containers.RepeatedCompositeFieldContainer[_im_pb2.Msg]:
        """"""

    def __init__(
        self,
        *,
        msg: _abc.Iterable[_im_pb2.Msg] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["msg", b"msg"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspGetMsg: _TypeAlias = RspGetMsg  # noqa: Y015

@_typing.final
class RspLiveInfo(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    LIVE_STATUS_FIELD_NUMBER: _builtins.int
    JUMP_URL_FIELD_NUMBER: _builtins.int
    live_status: _builtins.int
    """"""
    jump_url: _builtins.str
    """"""
    def __init__(
        self,
        *,
        live_status: _builtins.int = ...,
        jump_url: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["jump_url", b"jump_url", "live_status", b"live_status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspLiveInfo: _TypeAlias = RspLiveInfo  # noqa: Y015

@_typing.final
class RspMyGroupUnread(_message.Message):
    """我创建的应援团未读数-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    UNREAD_COUNT_FIELD_NUMBER: _builtins.int
    unread_count: _builtins.int
    """未读消息数"""
    def __init__(
        self,
        *,
        unread_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["unread_count", b"unread_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspMyGroupUnread: _TypeAlias = RspMyGroupUnread  # noqa: Y015

@_typing.final
class RspRelationSync(_message.Message):
    """同步关系-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    FULL_FIELD_NUMBER: _builtins.int
    RELATION_LOGS_FIELD_NUMBER: _builtins.int
    FRIEND_LIST_FIELD_NUMBER: _builtins.int
    SERVER_RELATION_OPLOG_SEQNO_FIELD_NUMBER: _builtins.int
    GROUP_LIST_FIELD_NUMBER: _builtins.int
    full: _builtins.int
    """"""
    server_relation_oplog_seqno: _builtins.int
    """服务器端最大的relation seqno"""
    @_builtins.property
    def relation_logs(self) -> _containers.RepeatedCompositeFieldContainer[_im_pb2.RelationLog]:
        """增量日志"""

    @_builtins.property
    def friend_list(self) -> _containers.RepeatedCompositeFieldContainer[_im_pb2.FriendRelation]:
        """全量列表"""

    @_builtins.property
    def group_list(self) -> _containers.RepeatedCompositeFieldContainer[_im_pb2.GroupRelation]:
        """全量列表"""

    def __init__(
        self,
        *,
        full: _builtins.int = ...,
        relation_logs: _abc.Iterable[_im_pb2.RelationLog] | None = ...,
        friend_list: _abc.Iterable[_im_pb2.FriendRelation] | None = ...,
        server_relation_oplog_seqno: _builtins.int = ...,
        group_list: _abc.Iterable[_im_pb2.GroupRelation] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["friend_list", b"friend_list", "full", b"full", "group_list", b"group_list", "relation_logs", b"relation_logs", "server_relation_oplog_seqno", b"server_relation_oplog_seqno"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspRelationSync: _TypeAlias = RspRelationSync  # noqa: Y015

@_typing.final
class RspSendMsg(_message.Message):
    """发送消息-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    MSG_KEY_FIELD_NUMBER: _builtins.int
    E_INFOS_FIELD_NUMBER: _builtins.int
    MSG_CONTENT_FIELD_NUMBER: _builtins.int
    KEY_HIT_INFOS_FIELD_NUMBER: _builtins.int
    msg_key: _builtins.int
    """"""
    msg_content: _builtins.str
    """"""
    @_builtins.property
    def e_infos(self) -> _containers.RepeatedCompositeFieldContainer[Global___EmotionInfo]:
        """表情资源信息"""

    @_builtins.property
    def key_hit_infos(self) -> _im_pb2.KeyHitInfos:
        """"""

    def __init__(
        self,
        *,
        msg_key: _builtins.int = ...,
        e_infos: _abc.Iterable[Global___EmotionInfo] | None = ...,
        msg_content: _builtins.str = ...,
        key_hit_infos: _im_pb2.KeyHitInfos | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["key_hit_infos", b"key_hit_infos"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["e_infos", b"e_infos", "key_hit_infos", b"key_hit_infos", "msg_content", b"msg_content", "msg_key", b"msg_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspSendMsg: _TypeAlias = RspSendMsg  # noqa: Y015

@_typing.final
class RspSessionDetails(_message.Message):
    """批量拉取会话详情-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    SESS_INFOS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def sess_infos(self) -> _containers.RepeatedCompositeFieldContainer[_im_pb2.SessionInfo]:
        """会话详情列表"""

    def __init__(
        self,
        *,
        sess_infos: _abc.Iterable[_im_pb2.SessionInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sess_infos", b"sess_infos"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspSessionDetails: _TypeAlias = RspSessionDetails  # noqa: Y015

@_typing.final
class RspSessionMsg(_message.Message):
    """同步版本拉取消息-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    MESSAGES_FIELD_NUMBER: _builtins.int
    HAS_MORE_FIELD_NUMBER: _builtins.int
    MIN_SEQNO_FIELD_NUMBER: _builtins.int
    MAX_SEQNO_FIELD_NUMBER: _builtins.int
    E_INFOS_FIELD_NUMBER: _builtins.int
    has_more: _builtins.int
    """"""
    min_seqno: _builtins.int
    """"""
    max_seqno: _builtins.int
    """"""
    @_builtins.property
    def messages(self) -> _containers.RepeatedCompositeFieldContainer[_im_pb2.Msg]:
        """"""

    @_builtins.property
    def e_infos(self) -> _containers.RepeatedCompositeFieldContainer[Global___EmotionInfo]:
        """表情资源信息"""

    def __init__(
        self,
        *,
        messages: _abc.Iterable[_im_pb2.Msg] | None = ...,
        has_more: _builtins.int = ...,
        min_seqno: _builtins.int = ...,
        max_seqno: _builtins.int = ...,
        e_infos: _abc.Iterable[Global___EmotionInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["e_infos", b"e_infos", "has_more", b"has_more", "max_seqno", b"max_seqno", "messages", b"messages", "min_seqno", b"min_seqno"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspSessionMsg: _TypeAlias = RspSessionMsg  # noqa: Y015

@_typing.final
class RspSessions(_message.Message):
    """拉取消息-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SystemMsgEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        value: _builtins.int
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    SESSION_LIST_FIELD_NUMBER: _builtins.int
    HAS_MORE_FIELD_NUMBER: _builtins.int
    ANTI_DISTURB_CLEANING_FIELD_NUMBER: _builtins.int
    IS_ADDRESS_LIST_EMPTY_FIELD_NUMBER: _builtins.int
    SYSTEM_MSG_FIELD_NUMBER: _builtins.int
    SHOW_LEVEL_FIELD_NUMBER: _builtins.int
    has_more: _builtins.int
    """"""
    anti_disturb_cleaning: _builtins.bool
    """标记反垃圾会话是否在清理中"""
    is_address_list_empty: _builtins.int
    """当session_list为空时，会返回该字段用于判断通讯录是否为空，1表示空，0表示非空"""
    show_level: _builtins.bool
    """"""
    @_builtins.property
    def session_list(self) -> _containers.RepeatedCompositeFieldContainer[_im_pb2.SessionInfo]:
        """"""

    @_builtins.property
    def system_msg(self) -> _containers.ScalarMap[_builtins.int, _builtins.int]:
        """"""

    def __init__(
        self,
        *,
        session_list: _abc.Iterable[_im_pb2.SessionInfo] | None = ...,
        has_more: _builtins.int = ...,
        anti_disturb_cleaning: _builtins.bool = ...,
        is_address_list_empty: _builtins.int = ...,
        system_msg: _abc.Mapping[_builtins.int, _builtins.int] | None = ...,
        show_level: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["anti_disturb_cleaning", b"anti_disturb_cleaning", "has_more", b"has_more", "is_address_list_empty", b"is_address_list_empty", "session_list", b"session_list", "show_level", b"show_level", "system_msg", b"system_msg"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspSessions: _TypeAlias = RspSessions  # noqa: Y015

@_typing.final
class RspShareList(_message.Message):
    """拉取最近私信分享列表-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_LIST_FIELD_NUMBER: _builtins.int
    ISADDRESSLISTEMPTY_FIELD_NUMBER: _builtins.int
    IsAddressListEmpty: _builtins.int
    """"""
    @_builtins.property
    def session_list(self) -> _containers.RepeatedCompositeFieldContainer[Global___ShareSessionInfo]:
        """最近会话列表"""

    def __init__(
        self,
        *,
        session_list: _abc.Iterable[Global___ShareSessionInfo] | None = ...,
        IsAddressListEmpty: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["IsAddressListEmpty", b"IsAddressListEmpty", "session_list", b"session_list"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspShareList: _TypeAlias = RspShareList  # noqa: Y015

@_typing.final
class RspShowClearUnreadUI(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    DISPLAY_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    display: _builtins.bool
    """"""
    text: _builtins.str
    """"""
    def __init__(
        self,
        *,
        display: _builtins.bool = ...,
        text: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["display", b"display", "text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspShowClearUnreadUI: _TypeAlias = RspShowClearUnreadUI  # noqa: Y015

@_typing.final
class RspSingleUnread(_message.Message):
    """未读私信数-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    UNFOLLOW_UNREAD_FIELD_NUMBER: _builtins.int
    FOLLOW_UNREAD_FIELD_NUMBER: _builtins.int
    UNFOLLOW_PUSH_MSG_FIELD_NUMBER: _builtins.int
    DUSTBIN_PUSH_MSG_FIELD_NUMBER: _builtins.int
    DUSTBIN_UNREAD_FIELD_NUMBER: _builtins.int
    BIZ_MSG_UNFOLLOW_UNREAD_FIELD_NUMBER: _builtins.int
    BIZ_MSG_FOLLOW_UNREAD_FIELD_NUMBER: _builtins.int
    unfollow_unread: _builtins.int
    """未关注用户私信数"""
    follow_unread: _builtins.int
    """已关注用户私信数"""
    unfollow_push_msg: _builtins.int
    """未关注人列表是否有新业务通知"""
    dustbin_push_msg: _builtins.int
    """"""
    dustbin_unread: _builtins.int
    """"""
    biz_msg_unfollow_unread: _builtins.int
    """"""
    biz_msg_follow_unread: _builtins.int
    """"""
    def __init__(
        self,
        *,
        unfollow_unread: _builtins.int = ...,
        follow_unread: _builtins.int = ...,
        unfollow_push_msg: _builtins.int = ...,
        dustbin_push_msg: _builtins.int = ...,
        dustbin_unread: _builtins.int = ...,
        biz_msg_unfollow_unread: _builtins.int = ...,
        biz_msg_follow_unread: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["biz_msg_follow_unread", b"biz_msg_follow_unread", "biz_msg_unfollow_unread", b"biz_msg_unfollow_unread", "dustbin_push_msg", b"dustbin_push_msg", "dustbin_unread", b"dustbin_unread", "follow_unread", b"follow_unread", "unfollow_push_msg", b"unfollow_push_msg", "unfollow_unread", b"unfollow_unread"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspSingleUnread: _TypeAlias = RspSingleUnread  # noqa: Y015

@_typing.final
class RspSpecificSingleUnread(_message.Message):
    """-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TalkerUnreadCntEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.int
        value: _builtins.int
        def __init__(
            self,
            *,
            key: _builtins.int = ...,
            value: _builtins.int = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TALKERUNREADCNT_FIELD_NUMBER: _builtins.int
    ALLUNREADCNT_FIELD_NUMBER: _builtins.int
    allUnreadCnt: _builtins.int
    """总未读数"""
    @_builtins.property
    def talkerUnreadCnt(self) -> _containers.ScalarMap[_builtins.int, _builtins.int]:
        """key -> 用户uid, value ->未读数"""

    def __init__(
        self,
        *,
        talkerUnreadCnt: _abc.Mapping[_builtins.int, _builtins.int] | None = ...,
        allUnreadCnt: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allUnreadCnt", b"allUnreadCnt", "talkerUnreadCnt", b"talkerUnreadCnt"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspSpecificSingleUnread: _TypeAlias = RspSpecificSingleUnread  # noqa: Y015

@_typing.final
class RspSyncAck(_message.Message):
    """确认同步进度-响应"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspSyncAck: _TypeAlias = RspSyncAck  # noqa: Y015

@_typing.final
class RspTotalUnread(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    SESSION_SINGLE_UNREAD_FIELD_NUMBER: _builtins.int
    MSG_FEED_UNREAD_FIELD_NUMBER: _builtins.int
    SYS_MSG_INTERFACE_LAST_MSG_FIELD_NUMBER: _builtins.int
    TOTAL_UNREAD_FIELD_NUMBER: _builtins.int
    total_unread: _builtins.int
    """"""
    @_builtins.property
    def session_single_unread(self) -> Global___SessionSingleUnreadRsp:
        """"""

    @_builtins.property
    def msg_feed_unread(self) -> Global___MsgFeedUnreadRsp:
        """"""

    @_builtins.property
    def sys_msg_interface_last_msg(self) -> Global___SysMsgInterfaceLastMsgRsp:
        """"""

    def __init__(
        self,
        *,
        session_single_unread: Global___SessionSingleUnreadRsp | None = ...,
        msg_feed_unread: Global___MsgFeedUnreadRsp | None = ...,
        sys_msg_interface_last_msg: Global___SysMsgInterfaceLastMsgRsp | None = ...,
        total_unread: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["msg_feed_unread", b"msg_feed_unread", "session_single_unread", b"session_single_unread", "sys_msg_interface_last_msg", b"sys_msg_interface_last_msg"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["msg_feed_unread", b"msg_feed_unread", "session_single_unread", b"session_single_unread", "sys_msg_interface_last_msg", b"sys_msg_interface_last_msg", "total_unread", b"total_unread"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspTotalUnread: _TypeAlias = RspTotalUnread  # noqa: Y015

@_typing.final
class RspUpdateTotalUnread(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RspUpdateTotalUnread: _TypeAlias = RspUpdateTotalUnread  # noqa: Y015

@_typing.final
class SessionSingleUnreadRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    UNFOLLOW_UNREAD_FIELD_NUMBER: _builtins.int
    FOLLOW_UNREAD_FIELD_NUMBER: _builtins.int
    UNFOLLOW_PUSH_MSG_FIELD_NUMBER: _builtins.int
    DUSTBIN_PUSH_MSG_FIELD_NUMBER: _builtins.int
    DUSTBIN_UNREAD_FIELD_NUMBER: _builtins.int
    unfollow_unread: _builtins.int
    """"""
    follow_unread: _builtins.int
    """"""
    unfollow_push_msg: _builtins.int
    """"""
    dustbin_push_msg: _builtins.int
    """"""
    dustbin_unread: _builtins.int
    """"""
    def __init__(
        self,
        *,
        unfollow_unread: _builtins.int = ...,
        follow_unread: _builtins.int = ...,
        unfollow_push_msg: _builtins.int = ...,
        dustbin_push_msg: _builtins.int = ...,
        dustbin_unread: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dustbin_push_msg", b"dustbin_push_msg", "dustbin_unread", b"dustbin_unread", "follow_unread", b"follow_unread", "unfollow_push_msg", b"unfollow_push_msg", "unfollow_unread", b"unfollow_unread"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SessionSingleUnreadRsp: _TypeAlias = SessionSingleUnreadRsp  # noqa: Y015

@_typing.final
class ShareSessionInfo(_message.Message):
    """会话信息，用于私信分享"""

    DESCRIPTOR: _descriptor.Descriptor

    TALKER_ID_FIELD_NUMBER: _builtins.int
    TALKER_UNAME_FIELD_NUMBER: _builtins.int
    TALKER_ICON_FIELD_NUMBER: _builtins.int
    OFFICIAL_TYPE_FIELD_NUMBER: _builtins.int
    talker_id: _builtins.int
    """"""
    talker_uname: _builtins.str
    """"""
    talker_icon: _builtins.str
    """"""
    official_type: _builtins.int
    """认证信息
    -1: 无认证 0:个人认证 1:机构认证
    """
    def __init__(
        self,
        *,
        talker_id: _builtins.int = ...,
        talker_uname: _builtins.str = ...,
        talker_icon: _builtins.str = ...,
        official_type: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["official_type", b"official_type", "talker_icon", b"talker_icon", "talker_id", b"talker_id", "talker_uname", b"talker_uname"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ShareSessionInfo: _TypeAlias = ShareSessionInfo  # noqa: Y015

@_typing.final
class SimpleSession(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    TALKER_ID_FIELD_NUMBER: _builtins.int
    SESSION_TYPE_FIELD_NUMBER: _builtins.int
    talker_id: _builtins.int
    """聊天对象uid，可以为用户id或者为群id"""
    session_type: _builtins.int
    """会话类型"""
    def __init__(
        self,
        *,
        talker_id: _builtins.int = ...,
        session_type: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["session_type", b"session_type", "talker_id", b"talker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SimpleSession: _TypeAlias = SimpleSession  # noqa: Y015

@_typing.final
class SysMsgInterfaceLastMsgRsp(_message.Message):
    """"""

    DESCRIPTOR: _descriptor.Descriptor

    UNREAD_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    TIME_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    unread: _builtins.int
    """"""
    title: _builtins.str
    """"""
    time: _builtins.str
    """"""
    id: _builtins.int
    """"""
    def __init__(
        self,
        *,
        unread: _builtins.int = ...,
        title: _builtins.str = ...,
        time: _builtins.str = ...,
        id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "time", b"time", "title", b"title", "unread", b"unread"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SysMsgInterfaceLastMsgRsp: _TypeAlias = SysMsgInterfaceLastMsgRsp  # noqa: Y015
